### ISSUE TITLE
Nick Abbott - Image loading issue

### ISSUE THREAD

**Issue by nabbott98** [sei-ec-remote/project-1-issues#100]
### What's the problem you're trying to solve?

creating a workhorse function to display images call displayImage(ctx,...)

### Post any code you think might be relevant (one fenced block per file)
```
const duckShot = {name: 'duck-shot-b', location: `individual-assets/duck-shot-b.png`, posX: 100, posY: 200, adjX: 0, adjY: 0}

const displayImage = (ctx, img) => {
    board = new Image()
    board.src = img.location
    console.log(board)
    base_image.onload = function(){
        ctx.drawImage(board, 100,100,100,100)
    }
}

window.addEventListener('load', function(event) {
    let ctx = document.getElementById('canvas').getContext('2d')
    ctx.canvas.width = window.innerWidth
    ctx.canvas.height = window.innerWidth/2.14
    ctx.imageSmoothingEnabled = false
    displayImage(ctx, duckshot)
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The image is not being drawn. I have console.log every element I am inputing into the function drawImage() but it is not drwing image 

### What is your best guess as to the source of the problem?
So sort of understanding of how canvas works and how the computer proccesses the information. Maybe i'm forgetting to input something into the function

### What things have you already tried to solve the problem?
I have tried stripping the function down to just image location, and position
### Paste a link to your repository here
https://github.com/nabbott98/project1

**Comment by kestler01** [comment]
looks like maybe we're missing our render() method ?

**Comment by nabbott98** [comment]
Could you please elaborate? I have gotten other images to load into canvas without a render method

**Comment by kestler01** [comment]
I guess i'm just a little confused by your  display image function here, and so are you. lets try commenting each line to better understand what is going on and after lunch we can come together and properly pick it apart to figure out what's going on : sound good ?

**Comment by nabbott98** [comment]
Ok, after outcomes!

**Comment by nabbott98** [comment]
I figured out what was going on, but I do have some general questions about the way javascript/the computer process the code if you have time to hop into a breakout room?

**Comment by kestler01** [comment]
awesome - room 40

**Comment by kestler01** [comment]
would you post a brief summary of the resolution to the specific bug and close the issue ?
