### ISSUE TITLE
S.Barbee Game project issue(interval)

### ISSUE THREAD

**Issue by skbarbee** [sei-ec-remote/project-1-issues#102]
### What's the problem you're trying to solve?
How to stop my interval setting. 

### Post any code you think might be relevant (one fenced block per file)
```
const gamePlay = ()=>{
    
    // add eventlistener to see if player copied
gameBoard.addEventListener("click", (e)=>{
    // add click to player array
        //    console.log(e.target.id)
           playerTurn.push(e.target.id)
            console.log(playerTurn)
            console.log(computerTurn)
            setInterval(checkPattern,1500)        
})
}

//if player follows the pattern make a new pattern
        //need to make a time limit to follow 
const checkPattern = () =>{
            if(playerTurn[0] == computerTurn[0]){
                level += 1
                playerTurn = []
                computerTurn = []
                let newRandomChoices = choices[Math.floor(Math.random()* choices.length)]
                computerTurn.push(newRandomChoices)
                readOut.innerText = (computerTurn)
            }else{
                clearInterval(checkPattern)
                stopInterval (checkPattern)
                readOut.innerText = `DOOOH!  You got to level ${level}`
                console.log("you got to level", level)
                gameBoard.removeEventListener("click",()=>{
                   
                })
                }
            
}
const stopInterval = (pattern)=>{
    clearInterval(pattern)
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm not getting an error message, but I've tried clearInterval and the function and then I made a clearInterval function and called that too, but regardless it's not stop it's still going through the interval. 

I'm assuming it has something to do with WHERE the clearInterval is called, but it needs to stop once the player loses.

### What is your best guess as to the source of the problem?
I have no idea. I thought It was because at first I built it using an anonymous function, but then I  

### What things have you already tried to solve the problem?
I've tried making a new function,
I've tried setting the interval in If statement
I've tried returning false and just return

### Paste a link to your repository here
https://github.com/skbarbee/Boo-p-it-

**Comment by scarletpuma** [comment]
Have you tried having the clearInterval outside of the if statement just to make sure that it's working as expected?
