### ISSUE TITLE
Boxes 

### ISSUE THREAD

**Issue by amishizaki** [sei-ec-remote/project-1-issues#105]
### What's the problem you're trying to solve?
I'm trying to get my boxes to render

### Post any code you think might be relevant (one fenced block per file)
```
const game = document.getElementById('canvas')
// const movement = document.getElementById('movement')
// const message = document.getElementById('status')
const ctx = game.getContext('2d')
// const gravity = 1
// const friction =.99
let raf

// canvas.width = window.innerWidth;
// canvas.height = window.innerHeight;



game.setAttribute('width', getComputedStyle(game)['width'])
game.setAttribute('height', getComputedStyle(game)['height'])

const box = {
        x: 50,
        y: 300,
        vx: 5,
        vx: 5,
        color: 'pink',
        width: 120,
        height: 120,
        isFalling: true,
        isHeld: false,
        isStacked: false,
        draw () {
            ctx.beginPath();
            // ctx.arc(this.x, this.y, this.width, this.height, Math.PI * 2, true);
            ctx.closePath();
            ctx.fillStyle = this.color
            ctx.fill();
        }
    }

function draw() {
    ctx.fillStyle = 'rgba(255, 255, 255, .3)';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    box.draw();
    box.x += box.vx; 
    box.y += box.vy;
    box.vy *= .99;
    box.vy += .25;
    
    if (box.y + box.vy > canvas.height ||
        box.y + box.vy < 0) {
            box.vy =-box.vy;
        }
    if (box.x + box.xy > canvas.width ||
        box.x + box.xy < 0) {
            box.vy =-box.xy;
        }
    raf = window.requestAnimationFrame(draw);
}

canvas.addEventListener('mouseover', (e) => {
    raf = window.requestAnimationFrame(draw);
});
canvas.addEventListener('mouseout', (e) =>{
    window.cancelAnimationFrame(raf);
});

box.draw()
console.log('this is a box?', box)
console.log('this should be drawing the box', draw())

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The image is glitching. I console logged raf and it's constantly reloading.

### What is your best guess as to the source of the problem?
I think I have clashing code. 

### What things have you already tried to solve the problem?
I'm researching right now what else I can do.

### Paste a link to your repository here
https://github.com/amishizaki/Unit-One-Project

**Comment by kestler01** [comment]
~~to start : i think you should avoid function declaration and use function expressions instead ( set your functions to variables ).~~
what about your boxes is not loading : the entire game board ? 
also looks like you aren't evoking the draw function, needs ' () ' ?

**Comment by amishizaki** [comment]
Looks like the issue is partly due to the event listener. I made a few tweaks and now the draw function fully coincides with the event listener - which is currently tied to the mouse. Right now, when my mouse hovers over the canvas, it flashes quickly between white and the actual background of the image. 

Also, I do have a box.draw() - which should be evoking the function?

**Comment by kestler01** [comment]
is this still active ? and if so - lets meet up in break out room to 50

**Comment by amishizaki** [comment]
Issue solved:
- fixed box draw function
- evoked function within gameLoop
- organized the gameLoop (placed the clearEvent before the evoke function)
