### ISSUE TITLE
Trying to get the cards in the game board to adjust to different screen sizes

### ISSUE THREAD

**Issue by melsil11** [sei-ec-remote/project-1-issues#107]
### What's the problem you're trying to solve?
I noticed that the 3 bottom cards do not adjust like the gameboard does when the browser is resized. the cards will be out of the gameboard if browser is not opened to full screen 

### Post any code you think might be relevant (one fenced block per file)
```

.gameboard{
    position: relative;
    display: flex;
    justify-content: center;
    height: 100%;
    min-height: 500px;
    width: auto;
    border: 5px solid;
    padding: 20px; 
    
}

#match-card{
    display:flex;
    position: absolute;
    /* display: inline-block; */
    justify-content: center;
    margin-left: auto;
    margin-right: auto;
    /* width: 10%; */
    /* margin: 20px 450px 10px 840px; */
}



.cards {
   position: absolute;
   display: flex;
   padding: 100px;
   margin: 20px;
   /* width: 50%; */
   height: 100px;
   
   
}

.cards div{
    padding: 100px;
    margin: 20px;
    
  
    
}```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?


### What is your best guess as to the source of the problem?
width adjustment on the card div

### What things have you already tried to solve the problem?

 I have tried all kinds of widths, both px and %, position absolute, relative, margin adjustments, padding,, gap

### Paste a link to your repository here[
](https://github.com/melsil11/Find-the-Puppy)

**Comment by scarletpuma** [comment]
Make sure you're not using position: relative or position: absolute with flexbox!

**Comment by melsil11** [comment]
I removed the position absolute and it did not change anything

**Comment by melsil11** [comment]
I tried commenting things out and seeing if it changed anything and it didn't. When I commented out the match card poistion absolute it removed it so i put it back in, but the three bottom cards are still not aligning to the gameboard. Here is the updated code
.gameboard{
    /* position: relative; */
    display: flex;
    justify-content: center;
    height: 100%;
    min-height: 500px;
    width: auto;
    border: 5px solid;
    padding: 20px; 
    
}

#match-card{
    display:flex;
    position: absolute;
    /* display: inline-block; */
    justify-content: center;
    margin-left: auto;
    margin-right: auto;
    /* width: 10%; */
    /* margin: 20px 450px 10px 840px; */
}



.cards {
   display: flex;
   /* position: absolute; */
   /* justify-content: center; */
   /* width: auto; */
   padding: 100px;
   margin: 20px;
   /* width: 50%; */
   height: 100px;
   
   
}

.cards div{
    /* justify-content: center; */
    /* width: auto; */
    padding: 100px;
    margin: 20px;
    
  
    
}

**Comment by scarletpuma** [comment]
When you use relative or absolute positioning it no longer is a flex element, so I definitely would leave that out.

The problem may be the width on the parent div.

**Comment by melsil11** [comment]
I changed the parent div width and it sent the image off the game board,  I have tried resizing width , hight, margins and padding, but it wants to send everything to the right of make the spaces between the cards bigger

.gameboard{
    /* position: relative; */
    display: flex;
    justify-content: center;
    height: 100%;
    /* min-height: 100px; */
    max-height: 75%;
    width: 100%;
    border: 5px solid;
    /* padding: 20px;  */
    
}

#match-card{
    display: flex;
    /* position: absolute; */
    /* display: inline-block; */
    justify-content: center;
    /* margin-top: 20px; */
    margin-left: 50%;
    /* align-content: center; */
    
    height: 100%;
    width: 100%;
   
    padding: 20px;
    /* margin: 20px 450px 10px 840px; */
}



.cards {
   display: flex;
   /* position: absolute; */
   justify-content: center;
   /* width: auto; */
   padding: 100px;
   /* margin-top: 20px; */
   /* width: 50%; */
   height: 100%;
   
   
}

.cards div{
    justify-content: center;
    /* width: auto; */
    width: 100%;
    height: 100%;
    padding: 100px;
    margin: 20px;
    /* margin-left: 10%; */
    
  
    
}
