### ISSUE TITLE
Can't get timer to countdown, also it may stop at 31??

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-1-issues#11]
### What's the problem you're trying to solve?

I want to create a timer that counts down from 45 to 0. And i believe I'm utilizing setTimeout/clearTimeout correctly.
I'm using a replit to write it out first by the way. 

### Post any code you think might be relevant (one fenced block per file)
```js
const timer = setTimeout(countDown, 46000)
const countDown = () =>{
for (let i = 45; i > 0; i--){
  clearTimeout(timer);
  } countDown();
} 
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
ReferenceError: Cannot access 'countDown' before initialization
    at Object.<anonymous> (/home/runner/UsedImprobableEquations/index.js:48:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

### What is your best guess as to the source of the problem?
It says I'm attempting to call countDown without initialization.  

### What things have you already tried to solve the problem?
I've moved countDown around multiple times. 

### Paste a link to your repository here

https://github.com/thefrostyausty/Project-1-Austin

**Comment by tkolsrud** [comment]
I think you can actually simplify this a bit. Instead of having a 46000 millisecond setTimeout, why not have a 1000 millisecond setTimeout that displays the value of a variable called "time"?
