### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by AliSaleh19** [sei-ec-remote/project-1-issues#110]
### What's the problem you're trying to solve?
Not able to get my 

### Post any code you think might be relevant (one fenced block per file)
```
game.setAttribute('width', getComputedStyle(game)['width'])
game.setAttribute('height', getComputedStyle(game)['height'])

const snake = {
    x: 200,
    y: 100,
    color: "#bada55",
    width: 60,
    height: 120,
    alive: true,
    render: function () {
        ctx.fillStyle = this.color
        ctx.fillRect(this.x, this.y, this.width, this.height)
    }
}

snake.render()
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

index.js:9 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')

### What is your best guess as to the source of the problem?
Not to sure, went back and rewatch Tims lecture of canvas crawler and followed the steps

### What things have you already tried to solve the problem?
Rewatched the code along, tried to redefine my functions but not to sure where to go from here, I know how to get the keys working but I just cant get my object to appear in canvas

**Comment by scarletpuma** [comment]
Make sure you fill out the entire form so we can help you!
