### ISSUE TITLE
My game starts before I hit my start game button

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-1-issues#112]
### What's the problem you're trying to solve?
My game starts before I hit my start game button. I'm also trying to get my reset game button to reset the canvas but that is also not working.

### Post any code you think might be relevant (one fenced block per file)
```
I believe it has something to do with my game loop.
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
My game starts before I initialize it.

### What is your best guess as to the source of the problem?
I thought it was the event listener attached to 'DOM content loaded' but that's not it. Now I'm out of ideas

### What things have you already tried to solve the problem?
Moving my gameInterval function into my start button event listener. 

### Paste a link to your repository here[
](https://github.com/hewinsonj/PooPicker-Game)

**Comment by scarletpuma** [comment]
Where is the code for your start game button?

**Comment by hewinsonj** [comment]
Line 30

**Comment by hewinsonj** [comment]
I know it doesn't have any reset functionality to it currently but I've
tried a few things that didn't work so I've since removed it.

**Comment by scarletpuma** [comment]
Well the issue with the game starting is because it's starting on load right now instead of waiting for you to click your start button. You may want to have that let score = 0 before your start game function, and try to think if there's any other variables you want to be false/at 0 at the start of the game and move them so that they're that way on load.

**Comment by hewinsonj** [comment]
I got it! I had to create a variable called gameOn and have its default value set to false, then made it so the start button changed its value to true, and only allowed the dogs position to update if it was true. Thanks! I still can't get my reset button to work once the game is over, but that's for another day.
