### ISSUE TITLE
Console Error on Function Success

### ISSUE THREAD

**Issue by infinitelyann** [sei-ec-remote/project-1-issues#115]
### What's the problem you're trying to solve?
Trying to get key value from object - am able to get values but also get an error, inhibiting the next function to be functioned

### Post any code you think might be relevant (one fenced block per file)
```
let playerSum = ()=>{

    for(let i = 0; i <= player.length; i++){
        let values = player[i].value
        console.log(values)
    }
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
<img width="239" alt="Screen Shot 2022-09-21 at 3 38 19 PM" src="https://user-images.githubusercontent.com/68655342/191597776-29bc0a68-cfec-4b8e-9b44-7d76bc7c87be.png">

### What is your best guess as to the source of the problem?
I am honestly not sure. I understand that the 'undefined reading of .value' has something to do with the array (ex. player[i].value)
But it console logs the values so thats why I'm confused

you have to click the player button and then my stand button to see error

### What things have you already tried to solve the problem?
I have re written many functions in different ways to solve the problem, I get the same outcome 

### Paste a link to your repository here
https://github.com/infinitelyann/Project-1

**Comment by infinitelyann** [comment]
<img width="239" alt="Screen Shot 2022-09-21 at 3 38 19 PM" src="https://user-images.githubusercontent.com/68655342/191597147-63d8c334-17ef-4cf7-b859-b187fabd5835.png">
<img width="407" alt="Screen Shot 2022-09-21 at 3 38 47 PM" src="https://user-images.githubusercontent.com/68655342/191597162-ff967889-e4a2-4a0d-9dd7-8b27562e2147.png">

**Comment by kestler01** [comment]
Hey there Stephanie, it looks like array.value isn't a function 
can you share what we expect the player array to look like here ? 
also, are you trying to sum the values ?

**Comment by infinitelyann** [comment]
I am eventually trying to get the sum of the values; 
I successfully have a player array, with .value as a key. 
When I run a for loop, trying to get those values, I see them in the console, followed with my error message. I have screenshots for you, but unfortunately they are from two different decks. I hope I explained that decently! 

<img width="1462" alt="Screen Shot 2022-09-21 at 4 21 18 PM" src="https://user-images.githubusercontent.com/68655342/191604134-7f65aff0-19c0-4885-ab1e-cbd52b005013.png">

here is an example of the player array 

<img width="1455" alt="Screen Shot 2022-09-21 at 4 22 55 PM" src="https://user-images.githubusercontent.com/68655342/191604262-25b3944e-79f6-4c02-9b0d-d5fa215ccf56.png">



here is after the array is passed through a function with a for-loop to gather of all the 'value' values in the array. I can  see those values in the console, but the error is throwing me off.

**Comment by kestler01** [comment]
![Screen Shot 2022-09-21 at 4 37 05 PM](https://user-images.githubusercontent.com/16964576/191605573-6b7eb246-2deb-4d21-a6aa-80c4ba405fbd.png)

the last index of your array is ``` board:#player``` either reduce the loop length or remove that from the array

**Comment by infinitelyann** [comment]
HA! That fixed it! thank you so much!
