### ISSUE TITLE
Nick Abbott - Function running too quickly

### ISSUE THREAD

**Issue by nabbott98** [sei-ec-remote/project-1-issues#117]
### What's the problem you're trying to solve?
I need to run a sequence/chain of functions that call the next one in line 10 times per round of my game. 

To control this I thought that I could utilize concentric while loops

while (round not over){
     while (duck release < 10){
          sequence/chain of functions to run ten times
     }
}

this does not run as i'd like as it does not wait for the sequence to be done before it does the next thing. And I can't get the inner one to work. 

### Post any code you think might be relevant (one fenced block per file)
```
while{
    hunting(ctx)
    console.log(duckNum)
    duckNum++
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message, but all my animations get sped up and don't run correctly

### What is your best guess as to the source of the problem?
My function is allowing itself to be run synchronously when I need it to be async

### What things have you already tried to solve the problem?
While loop, for loop, I am about to try digging into the async documentation, then maybe a .then promise chain

### Paste a link to your repository here
https://github.com/nabbott98/project1

**Comment by kestler01** [comment]
interesting, I know we didn't really cover asynchronous functions in unit one, so why don't we meet up and go over a simple implementation to get you past this blocker - room 40 😁

**Comment by nabbott98** [comment]
Andrew and I talked about implementing a main game loop instead of a bunch of functions with loops inside, also to use an array to push an active duck into and defining a class that is a duck

notes:

// ?
// Make main main game loop to manage all my game animations and timings together
// ?

// This looks like: a setInterval function that calls a very long game loop function every 500ms
// Our main game loop function starts by clearing the entire board and then starts rendering all of the basic game assets 
// Runs our game logic move functions and
// we can use arrays to make rendering this large collection of assets easier/ more dry with iteration methods
// for example
// we can have a ducks array tht represents all of the active ducks which we will render for every game loop at the locked in time
// when a new duck starts to be hunted we push it into the array and when duck is no longer active ( shot or time ran out) we remove it from the array
// 

// implementing this game loop with standardize the time across all of the game logic, but require removing redundant code from our many render functions
