### ISSUE TITLE
Drawing a rectangle in CSS

### ISSUE THREAD

**Issue by cloudedl** [sei-ec-remote/project-1-issues#12]
### What's the problem you're trying to solve?
Trying to draw a rectangle using CSS. 

### Post any code you think might be relevant (one fenced block per file)
```HTML
  <div id="battleBox" style="display: none;">
        <p id='fireElementalHealth'>Elemental Health: 40</p>
        <p id="wizardHealth">Wizard Health: 40</p>
        <button id="fireBall">FireBall</button>
        <button id="waterJet">Water Jet</button>
        <button id="heal">Heal</button>
        <button id="vineWhip">Vine Whip</button>
        <p id="combatLog"></p>
    </div>
```

```CSS
#battlebox {
    border: 10px solid #00B506;
    padding: 30px; 
    margin: 0;
    width: 800px;
    height: 600px;
    
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
When I click my button that reveals the hidden elements everything shows up. Even if I remove the display = None statement I do not get a different result. 

### What is your best guess as to the source of the problem?
I must have some CSS formatting wrong.

### What things have you already tried to solve the problem?

I am following https://www.w3schools.com/css/css_boxmodel.asp
To my eyes my code appears the same. 

### Paste a link to your repository here
https://github.com/cloudedl/Wizards-Quest

**Comment by cloudedl** [comment]
"When I click my button that reveals the hidden elements everything shows up. Even if I remove the display = None statement I do not get a different result."

Everything with the exception of a rectangle. This was unclear in my original phrasing.

**Comment by cory-yonomi** [comment]
Check your CSS selector's capitalization.

**Comment by cloudedl** [comment]
I saw that a moment before you posted it. I do have border elements being drawn now. Thank you.
