### ISSUE TITLE
match function is not recognizing the match 

### ISSUE THREAD

**Issue by melsil11** [sei-ec-remote/project-1-issues#123]
### What's the problem you're trying to solve?
my match function is not matching the correct choice.  the choices randomize but no matter what choice is on the first card it chooses that as the match 

### Post any code you think might be relevant (one fenced block per file)
```
function shuffleArray(choices) {

    for (let i = choices.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        //   fisher yates randomizer
        [choices[i], choices[j]] = [choices[j], choices[i]];
    }
    
    for ( let i = 0; i < choices.length; i++) {
        if (choices[i] === 'faceCard1')   { 
            const card1 = document.createElement('img')
            card1.src = 'images/faceCard.jpeg'
            card1.style.width = '150px'
            card1.alt = 'faceCard1'
            card1.id = 'faceCard1'
            document.getElementsByClassName('cards')[0].appendChild(card1) 
            console.log(document.getElementsByClassName('cards')[0]);
      
        } else if (choices[i] === 'faceCard2') {  
            const card2 = document.createElement('img')
            card2.src = 'images/faceCard.jpeg'
            card2.style.width = '150px'
            card2.alt = 'faceCard2'
            card2.id = 'faceCard2'
            document.getElementsByClassName('cards')[0].appendChild(card2) 
            console.log(document.getElementsByClassName('cards')[0]);

        } else  {  
            const card3 = document.createElement('img')
            card3.src = 'images/faceCard.jpeg'
            card3.style.width = '150px'
            card3.alt = 'faceCard3'
            card3.id = 'faceCard3'
            document.getElementsByClassName('cards')[0].appendChild(card3) 
            console.log(document.getElementsByClassName('cards')[0]);
   
        }
    console.log(choices)
    }
}
shuffleArray(choices);

const matchCheck = (event) => {
    console.log(event.target.id)
    let selection = event.target.id
    if (selection == choices[0]) {
        result = 'match';
       
    } else  {
        result = 'computers turn';
    } 
    console.log(result)
}
```

### What is your best guess as to the source of the problem?
not calling on the correct element in the matchCheck function

### What things have you already tried to solve the problem?
I have changed the index number in the created elements function to correspond with the correct index number but that did not change it, I then  went into the match function and changed the choices index to a match faceCard1, or card1 and it still did not work. 

### Paste a link to your repository here[
](https://github.com/melsil11/Find-the-Puppy)

**Comment by melsil11** [comment]
I tried  
const cardChoices = getElementsByClassNames('cards') to grab the cards and change the match function to correspond but I am getting an error messageUncaught ReferenceError: getElementsByClassName is not defined
    at index.js:68:21. but it is defined in the html and we used to create the images

**Comment by kestler01** [comment]
i think you may be missing the ```document``` part of `getElementsByClassNames('cards')`

**Comment by melsil11** [comment]
I am still not getting a match

**Comment by kestler01** [comment]
```
let selection = event.target.id
    if (selection == choices[0]
```
what does your choices array look like ?

Also - we should be using strict equality instead of loose equality whenever possible - but that isn't the source of your issue 
( == can lead to unintended consequences , === is safer )

**Comment by melsil11** [comment]
const choices = ['faceCard1', 'faceCard2', 'faceCard3'];

**Comment by melsil11** [comment]
I moved the randomizer to the bottom of the function and I am able to get  it to claim a match but its no the correct match

**Comment by kestler01** [comment]
did we change to strict equality  `===`

**Comment by melsil11** [comment]
yes and its till not matching the way it  should

**Comment by melsil11** [comment]
we made the console.logs more specific and changed the matchCheck function to match the id 'faceCard1' and not the array index of choices[0]
