### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by sheikdon** [sei-ec-remote/project-1-issues#128]
### What's the problem you're trying to solve?
so im stuck on the part where i need to have the board loaded and ive hit a wall and cant figure out how to pass through it.

### Post any code you think might be relevant (one fenced block per file)
```
`board = [
      [0, 0, 0, 0, 0, 0], 
      [0, 0, 0, 0, 0, 0],  
      [0, 0, 0, 0, 0, 0],  
      [0, 0, 0, 0, 0, 0],  
      [0, 0, 0, 0, 0, 0], 
      [0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0],

    ];`
```

### What is your best guess as to the source of the problem?

i think i need to start a if then statement or add event listeners but im still not sure where to go from there.
### What things have you already tried to solve the problem?
i tried using addeventlisteners for my squares but on the console nothing shows and the clicks arent working.

**Comment by scarletpuma** [comment]
Make sure you fill out the entire issue form when you submit an issue!
