### ISSUE TITLE
Difficulty getting "clearInterval" to reset the game loop

### ISSUE THREAD

**Issue by joshdoyle94** [sei-ec-remote/project-1-issues#139]
### What's the problem you're trying to solve?
My clearInterval method doesn't appear to work, so when the game is restarted the setInterval that begins the game keeps compounding instead of starting at its first set point.

### Post any code you think might be relevant (one fenced block per file)
```
restart.addEventListener('click', (event) => {
    if (gameStart != true) {
    const gameWonText = document.querySelector('#game-Won-Text')
    const closingStoryText = document.querySelector('#closing-story-text')
    start.style.display = 'initial'
    game.style.display  = 'initial'
    message.style.display = 'initial'
    score.style.display = 'initial'
    healthText.style.display = 'initial'
    gameWonText.remove()
    closingStoryText.remove()
    **clearInterval(gameLoop)**
    restart.style.display = 'none'
    start.innerText = 'Pause'
    start.style.justifyContent = 'center'
    start.style.textAlign = 'center'
    start.style.alignContent = 'center'
    start.style.fontSize = '25px'
    start.style.marginTop = '50px'
    startGame()
    } 
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message, but I am expecting the speed of the computer players set by setInterval to be reset instead of compounded.

### What is your best guess as to the source of the problem?
I think I may be using the clearInterval method wrong in this case, but I can't seem to pinpoint the issue.

### What things have you already tried to solve the problem?
Using the clearInterval method in different locations and calling it differently than on my (gameLoop) function.

### Paste a link to your repository here
https://github.com/joshdoyle94/Game-Project-1

**Comment by ejparnell** [comment]
@joshdoyle94 Great job here. So when setting an interval and clearing it you will need to save the interval id to a var. So have something like `let gameTimer = setInterval()` and to clear that interval you need to pass `clearInterval()` that id. So something like `clearInterval(gameTimer)`. Check out docs [here](https://developer.mozilla.org/en-US/docs/Web/API/setInterval#return_value)

**Comment by joshdoyle94** [comment]
thank you @ejparnell !!
