### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/project-1-issues#141]
### What's the problem you're trying to solve?
trying to loop my game without a dom reset. Would like my RESTART button to work. then long term, have it automatically restart after the player loses 1 life. plan is to give them three lives. 

### Post any code you think might be relevant (one fenced block per file)
```
// Restart button is taking a life but is not restarting the ball in correct position
restartBoard.addEventListener('click', function () {
    stopGameLoop()
    message.textContent = 'LOST LIFE, PRESS UP TO START AGAIN'
    gameInterval
        // Take from  lives counter
        // Counter starts at three. Takes 1 here each time hits bottom. Posts in the inner HTML of that box. 
        livesCount.innerHTML = counterForLives - 1
        counterForLives = counterForLives - 1
        if (counterForLives === 0) {
            window.location.replace("endPage.html")
        }
})
```

### Paste a link to your repository here

https://github.com/tthephas/Pong-game

**Comment by tthephas** [comment]
Also a quick question about best practices for creating branches to work on , outside of the main. Naming conventions and where to place them in the folders locally.

**Comment by timmshinbone** [comment]
I feel like part of the issue is stopping and restarting the game loop, without seeing the rest of your code, I assume that the lives counter et al start when the game loop begins. I feel like you might need to rework things for starting again after losing a life, and separate the functionalities of an actual _restart_ button, which should restart the entire game(ok to do DOM reset) and the functionality of a lost life(probably don't want to reset DOM or game loop)

**Comment by tthephas** [comment]
i think the issue i'm having is trying to figure out the trigger for when the game ends. in my case, its when the ball passes the paddle and hits the floor. i have the ball disappear , which means it hits a certain x or y coordinate off the screen. i cannot figure out how to use that as a trigger, to restart the game/dom. if i can figure that out, i am sure i can reconfigure the counter to sit outside of that and count down a life.

**Comment by timmshinbone** [comment]
Ok, let me ask this, when the ball passes the paddle and hits the floor, is that the end of the **game**, or is that just the end of one **round** of the game?

**Comment by tthephas** [comment]
for the MVP, just trying to end the game (go to the end game page) after one life. for later, i'd like the player to have three lives. after each life, the life counter goes down, the ball restarts to start position, then the up arrow would be the trigger to start the ball in motion again (or , just get the game loop to stop, then start again).

**Comment by timmshinbone** [comment]
Ok, I hear ya, set up a counter for your lives, and in your gameLoop make the transition based on that counter, for the time being it should say something like :
```js
if (counter === 1) {
     // end game loop
     // change to endGame animation
} else {
     // run game loop
}
```
After that's in there, it's fairly easy to switch the counter to 3 or 5 or however many lives you want a player to have.

**Comment by tthephas** [comment]
i basically tried to recreate your code from the DOM content loading part, that started the game, onto a button. here was the hero/ogre code, then my new code. but the start button is not putting the ball back up top and restarting the game loop. even if i had taht stop game loop code un commented

document.addEventListener('DOMContentLoaded', function () {
    // here is our game loop interval
    gameInterval
    message.textContent = 'PRESS UP ARROW TO START'
})

then mine
const restartBoard = document.getElementById('resetButton')

// Restart button is taking a life but is not restarting the ball in correct position
restartBoard.addEventListener('click', function () {
    //stopGameLoop()
    message.textContent = 'LOST LIFE, PRESS UP TO START AGAIN'
    gameInterval
        // Take from  lives counter
        // Counter starts at three. Takes 1 here each time hits bottom. Posts in the inner HTML of that box. 
        livesCount.innerHTML = counterForLives - 1
        counterForLives = counterForLives - 1
        if (counterForLives === 0) {
            window.location.replace("endPage.html")
        }
})

**Comment by tthephas** [comment]
ok i'll try that counter idea first

**Comment by timmshinbone** [comment]
Remember, even static screens are a type of animation when working with a canvas. And you'll need to program your elements on that page accordingly. It's almost like a completely different loop function(actually it could be a completely different loop function if you code it out that way).

**Comment by tthephas** [comment]
not sure i follow there. i will keep messing around with it. i think my biggest struggle is not understanding the  " gameinterval " variable and if i need to rework that differently for my game, vs  the hero/ogre game

**Comment by timmshinbone** [comment]
Ok, yeah, keep playing around with it and we can chat later about it if you find yourself stuck

**Comment by tthephas** [comment]
i just cannot get the ball to render again. i dont understand what the difference between these two are. i got the loop to STOP properly (kinda). but i dont see why it wont restart with this button. its exactly what dom content load does. 

```js
// Restart button is taking a life but is not restarting the ball in correct position
restartBoard.addEventListener('click', function () {
    //stopGameLoop()
    // message.textContent = 'LOST LIFE, PRESS UP TO START AGAIN'
    gameInterval
    console.log('trying to restart game with this button')
        // Take from  lives counter
        // Counter starts at three. Takes 1 here each time hits bottom. Posts in the inner HTML of that box. 
        // livesCount.innerHTML = counterForLives - 1
        // counterForLives = counterForLives - 1
        // if (counterForLives === 0) {
        //     window.location.replace("endPage.html")
        // }
})

// Add an event listener, when DOM loads, run the game on an interval
document.addEventListener('DOMContentLoaded', function () {
    // here is our game loop interval
    gameInterval
    message.textContent = 'PRESS UP ARROW TO START'
})
```

**Comment by tthephas** [comment]
I am still stuck on this. I tried many ways to move it around or remake the function but i cannot get it to work.

**Comment by timmshinbone** [comment]
Did you try what I recommended where everything you need is in one file using a `hidden` class and changing the view based on that instead of using multiple HTML files?

**Comment by tthephas** [comment]
i just got done fixing the looping issue and score counter. tying up some loose ends on that and the messaging. then i'm going to tackle the html and hiding issues. lastly trying to make the ball an actual sphere.

**Comment by tthephas** [comment]
was able to get everything into one js file and hide screens with the dom. thx. closing.
