### ISSUE TITLE
Game project issue - Slotmachine

### ISSUE THREAD

**Issue by blkurd** [sei-ec-remote/project-1-issues#144]
### What's the problem you're trying to solve?
I am trying to make the emojis display in the boxes when I click on the button "Play" and I am not sure if I am using the right methods or right code to make it work. 

### Post any code you think might be relevant (one fenced block per file)

```
const boxesEls = document.querySelectorAll("#boxes");

play.addEventListener("click", (eo) => {
  play.style.backgroundColor = "red";
  play.boxesEls.innerHtml = items
});

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

Uncaught TypeError: Cannot set properties of undefined (setting 'innerHtml')
 at HTMLButtonElement.<anonymous> (app.js:12:27)

### What is your best guess as to the source of the problem?

Not sure! 

### What things have you already tried to solve the problem?

Trying for loop and if statements. 

### Paste a link to your repository here

https://github.com/blkurd/slotmachine

**Comment by asands94** [comment]
It looks like you are looking for an element with an ID of boxes.

1. you have nothing in your HTML that has an ID of boxes
2. You can only use an ID name once, so if you want multiple things to have the ID boxes, they need to actually be classes instead.

Remember classes are `.class-name` and id's are `#id-name`

**Comment by blkurd** [comment]
I figured it out and this is my solution:

I have cashed the play button in JS and I wrote this function that will randomly return the emojis in the following array = ["🍭", "😻", "💵"] to the boxes I created in the html divs. 

`

function getRandomEmojis() {
  const emojis = ["🍭", "😻", "💵"];
  const randomIndex = Math.floor(Math.random() * (2 - 0 + 1)) + 0;
  return emojis[randomIndex];
}`
