### ISSUE TITLE
Game project issue 

### ISSUE THREAD

**Issue by brianaleew** [sei-ec-remote/project-1-issues#145]
### Post any code you think might be relevant (one fenced block per file)
```

class Projectile {
    constructor (x, y, width, height, radius, velocity) {
        this.x = x
        this.y = y 
        this.width = width 
        this.height = height 
        this.radius = radius 
        this.velocity = velocity 
        this.color = 'black' 
       
    }
    draw() {
        ctx.beginPath()
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI *2, false)
        ctx.fillStyle = this.color
        ctx.fill()
    }
   
}

const projectileMaker = () => {
    for (let i = 0; i < 8; i++) {
        let randomNumber = Math.floor(Math.random() * 120)
        let randomProjectile = new Projectile(x * randomNumber, y * randomNumber, 10, 10, 8, 50)
    }
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
"x is not defined" 

### What is your best guess as to the source of the problem?
It has to have something to do with my constructor variables being defined inside of the class, but if I dont put them there, I'm not sure where I would put them for it to make sense?

### What things have you already tried to solve the problem?
I tried making a Projectile class and calling each one. It works but it is tedious and repetitive. I then tried making a projectile maker function that includes a for loop and links to the Projectile Class.

### Paste a link to your repository here
https://github.com/brianaleew/Project-1

**Comment by timmshinbone** [comment]
This line: 
```js
let randomProjectile = new Projectile(x * randomNumber, y * randomNumber, 10, 10, 8, 50)
```
Should just use randomNumber in place where x and y should go. Not `x * randomNumber`. There is no context where x is defined within this function so your code doesn't know what it is. In this instance you're defining the x value with the variable `randomNumber`, same thing goes for y.

**Comment by brianaleew** [comment]
Makes sense. Thank you!
