### ISSUE TITLE
Game project issue - Dungeon of Yendor, DRY issue

### ISSUE THREAD

**Issue by mqpiffle** [sei-ec-remote/project-1-issues#147]
### What's the problem you're trying to solve?
I would like to DRY my movement code but I'm running into an issue when passing a method containing a variable defined in the same method - the console is throwing an exception saying it can't access the variable, even though I'm accessing it in other methods in the same class.  In the following example, I'm trying to implement the `move()` method shown by using `this.targUp`, `this.boundUp` (these would potentially become objects defining each direction), and the delta methods shown.  Current implementation is each direction has its own method like the `moveUp()`at the end of the example - and this implementation is 100% working.

Thank you!!!

### Post any code you think might be relevant (one fenced block per file)
```js
class MobileObject extends GameObject {
    constructor (uid, actorListArrayPos, gridPos, canvas, ctx, width, height) {
        super(canvas, ctx, width, height)
        this.uid = uid
        this.gridPos = gridPos
        this.actorListArrayPos = actorListArrayPos
        this.xPos = this.gridPos[0]
        this.yPos = this.gridPos[1]
        this.gridX = this.xPos / gridSize + tileCenter
        this.gridY = this.yPos / gridSize + tileCenter
        this.characterType = 'MOB'
        this.alive = true
        this.baseHealth = 100
        this.baseEnergy = 100
        this.baseAttack = 10
        this.attackType = ''
        this.basePhysResist = 0
        this.baseMagResist = 0
        this.targUp = [this.xPos, this.yPos - gridSize]
        this.boundUp = this.yPos > tileCenter
    }
    
    // this deltaUp is causing the issue!!
    deltaUp = function() {
        console.log(`y: ${this.yPos}`)
        this.yPos -= gridSize
        return this.yPos
    }

    deltaDown = function() {
        return this.yPos += gridSize
    }

    deltaRight = function() {
        return this.xPos += gridSize
    }

    deltaLeft = function() {
        return this.xPos -= gridSize
    }

    //***I feel like these can be refactored into one 'move' function, maybe later***
    move = function(targPos, boundCheck, moveDir1, moveDir2) {
        const targetAt = actorAt(targPos[0], targPos[1])
        if (!isCollision(targPos[0], targPos[1]) && boundCheck) {
            moveDir1()
        } else if (isCollision(targPos[0], targPos[1]) && this.enemyType === targetAt.characterType) {
            targetAt.baseHealth = this.meleeAttack(targetAt)
            console.log(targetAt.baseHealth)
            if (targetAt.characterType === 'ENEMY' && targetAt.baseHealth <= 0) {
                enemyDefeat(targetAt)
            }
        }
    }

    // meleeAttack = function(target)  {
    //     let defenderHealth = target.baseHealth
    //     const incomingDamage = this.baseAttack - (this.baseAttack * target.basePhysResist)
    //     defenderHealth = defenderHealth - incomingDamage
    //     console.log(`${this.uid} deals ${incomingDamage} to ${target.uid}`)
    //     return defenderHealth
    // }

    moveUp = function() {
        const targetAt = actorAt(this.xPos, this.yPos - gridSize)
        if (!isCollision(this.xPos, this.yPos - gridSize) && this.yPos > tileCenter) {
            this.yPos -= gridSize
        } else if (isCollision(this.xPos, this.yPos - gridSize) && this.enemyType === targetAt.characterType) {
            targetAt.baseHealth = this.meleeAttack(targetAt)
            console.log(targetAt.baseHealth)
            if (targetAt.characterType === 'ENEMY' && targetAt.baseHealth <= 0) {
                enemyDefeat(targetAt)
            }
        }
        // console.log('up')
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Will update with exact message...basically unable to access `this.yPos` at the `deltaUp()` method

### What is your best guess as to the source of the problem?
I'm not sure why I can't access the `this.yPos` from the deltaUp method, when it's working in my other methods

### What things have you already tried to solve the problem?
cried, pulled my hair out, stress eating...seriously though, this one has me baffled.  Actually in the deltaUp() you can see me trying to play with things to get it to work.

### Paste a link to your repository here
https://github.com/mqpiffle/Project-1-Yendor

**Comment by timmshinbone** [comment]
Only issue I'm seeing with this code has to do with the variable `gridSize`, is that a global variable, or is that part of the parent class you're extending? If it's global then we've got some kinda weird issue here. If it's part of the parent(extended) class then I think you still need to use the keyword `this` as in, `this.gridSize`. Share a screenshot or copy and paste the error message in a reply here.

**Comment by mqpiffle** [comment]
![image](https://user-images.githubusercontent.com/69863751/210806270-0a2bea5a-3b79-4322-b0d2-00c72955d1de.png)

**Comment by mqpiffle** [comment]
And yes `gridSize` is currently global, been using it without issue so far.

**Comment by mqpiffle** [comment]
And here's my move handler function fwiw:
```
movementHandler = function(key) {
        // we'll use the numPad for movement and explicitly define the diagonals
        if (key === 56) {
            // this.moveUp()
            this.move(this.targUp, this.boundUp, this.deltaUp)
            // console.log(`x: ${this.xPos}, y: ${this.yPos}`)
        }
        if (key === 57) {
            this.moveUpRight()
        }
        if (key === 54) {            
            this.moveRight()
        }
        if (key === 51) {
            this.moveDownRight()
        }
        if (key === 50) {
            this.moveDown()
        }
        if (key === 49) {
            this.moveDownLeft()
        }
        if (key === 52) {
            this.moveLeft()
        }
        if (key === 55) {
            this.moveUpLeft()
        }
        this.endTurn()
    }
```

**Comment by timmshinbone** [comment]
Ok, when you instantiate an instance of the MobileObject class are you making sure to pass in an array in the place of the parameter `gridPos`?

**Comment by timmshinbone** [comment]
Wait, it's having an issue with the PlayerCharacter class, is that an extension of MobileObject?

**Comment by mqpiffle** [comment]
Yes, with the `pcSpawnCoordinates()` method shown here
```
class PlayerCharacter extends MobileObject {
    ...
}

class GameWorld extends GameObject {
    constructor(canvas, ctx) {
        super(canvas, ctx)
    }

    pcSpawnCoordinates = () => {
        //spawn pc within 3 tiles of any edge
        let coordinateTest = false
        let rndX = Math.floor(Math.random() * (this.width / gridSize))
        // console.log(`initial pc x: ${rndX}`)
        let rndY = Math.floor(Math.random() * (this.height / gridSize))
        // console.log(`initial pc y: ${rndY}`)
        // console.log(`width within middle ${rndWidth >= 3 && rndWidth <= (game.width / gridSize) - 3}`)
        // console.log(`height within middle ${rndHeight >= 3 && rndHeight <= (game.width / gridSize) - 3}`)
        // console.log(`width within middle and height within middle ${(rndWidth >= 3 && rndWidth <= (game.width / gridSize) - 3) && (rndHeight >= 3 && rndHeight <= (game.height / gridSize) - 3)}`)
        let coordinates = []
        while (!coordinateTest) {
            if ((rndX >= 3 && rndX < (this.width / gridSize) - 3) && (rndY >= 3 && rndY <= (this.height / gridSize) - 3)) {
                rndX = Math.floor(Math.random() * (this.width / gridSize))
                // console.log(`new pc x: ${rndX}`)
            } else {
                coordinateTest = true
            }
        }
        
        coordinates = [rndX * gridSize + tileCenter, rndY * gridSize + tileCenter]
        // console.log(`pc coordinates ${coordinates}`)
        return coordinates
    }

   ...
}

...
// *********** UI STUFF ***********

// we'll need this a lot, like a lot a lot
const body = document.getElementById('body')

const initializeGame = () => {
    gameUI()
    // hmmm...now the game can't figure out canvas? because it doesn't exist
    const floorOne = new GameWorld()
    floorOne.mapDraw()

    playerCharacter = new PlayerCharacter(`pc0`, 0, floorOne.pcSpawnCoordinates())
    playerCharacter.render()
    actorList.push(playerCharacter)
    floorOne.enemySpawn(5)
}
```

**Comment by timmshinbone** [comment]
Ok, if that's the case, then you have these parameters that all need args when instantiating: `uid, actorListArrayPos, gridPos, canvas, ctx, width, height` and when you're building your `playerCharacter` you're only giving it 3
```js
  playerCharacter = new PlayerCharacter(`pc0`, 0, floorOne.pcSpawnCoordinates())  
```
That could be why it's having trouble reading those missing variables.

**Comment by mqpiffle** [comment]
Hmmm, yeah.  So do you think I would be better off just making & defining each class separately instead of extending them?  I was thinking the `extends` would make things more concise, but I'm not sure it's working the way I would like.  Unless I'm just not completely understanding the interaction between `constructor()` and `super()`, and how properties from lower in the tree branch out.

The thing is, everything is working nicely in the non-DRY implementation...

**Comment by timmshinbone** [comment]
Class extension is fine to use, but not at the cost of sacrificing working code. Same thing with DRY implementation, I'd rather you have 2,000,000,000 lines of repeating code that works than 200 lines of code that doesn't work. I think it's more important to keep it simple and build something that works in a way that makes sense to you than to try to get fancy. Also, when it comes to class extension, the tricky part is figuring out where it begins and ends, and that comes with time and practice. 
For example, I could come up with a high level explanation of why a human and a motorcycle are similar and should extend the same class(they both move around, they both require fuel to move around) but, when you zoom in, there are more differences than there are similarities which means it's probably better to build a class for each of them.

**Comment by mqpiffle** [comment]
This all makes sense.  I will just stick with what I have and carry on, thank you!
