### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by ShadowXG** [sei-ec-remote/project-1-issues#148]
### What's the problem you're trying to solve?
I'm trying restart the game

### Post any code you think might be relevant (one fenced block per file)
```
    createEnemies() {
        this.enemyMap.forEach((row, rowIndex) => {
            this.enemyRows[rowIndex] = []
            row.forEach((enemyNumber, enemyIndex) => {
                if (enemyNumber > 0) {
                    this.enemyRows[rowIndex].push(
                        new Enemy(enemyIndex * 150, rowIndex * 75, enemyNumber))
                }
            })
        })
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The enemies resume from there last position

### What is your best guess as to the source of the problem?
The enemy rows don't get reset so I'm trying to figure that out, also the position of the rows doesn't get reset

### What things have you already tried to solve the problem?
Not much Been just trying to reset the rows in any way I can.

### Paste a link to your repository here 
https://github.com/ShadowXG/Project-One

**Comment by scarletpuma** [comment]
Have you tried setting it so there's no enemies at the very beginning of your start game function so that it's forced to replace new ones?

**Comment by ShadowXG** [comment]
I guess that's kinda the problem I tried finding out how to do that with no luck.

**Comment by ShadowXG** [comment]
> Have you tried setting it so there's no enemies at the very beginning of your start game function so that it's forced to replace new ones?

I guess that's kinda the problem I tried finding out how to do that with no luck.

**Comment by scarletpuma** [comment]
You can just clear out what enemies you have, probably by emptying the array. It depends on how you have them set up

**Comment by ShadowXG** [comment]
> You can just clear out what enemies you have, probably by emptying the array. It depends on how you have them set up

I have and array of numbers that get rid of the number when it gets hit, that is declared in enemyRows which is a flat so it's easier to refer to them, I believe that the create enemies if could reset that, I'm not sure how to go about emptying my array.

**Comment by scarletpuma** [comment]
[Check this out!](https://stackoverflow.com/questions/1232040/how-do-i-empty-an-array-in-javascript)

**Comment by ShadowXG** [comment]
> [Check this out!](https://stackoverflow.com/questions/1232040/how-do-i-empty-an-array-in-javascript)

I've tried implementing this. The problem is, I'm having trouble on how to implement it and where.

**Comment by asands94** [comment]
Are you still having issues?

**Comment by ShadowXG** [comment]
Tim helped a bit gave some work but ultimately still haven't figured it out.
