### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by brianaleew** [sei-ec-remote/project-1-issues#149]
### What's the problem you're trying to solve?
I am trying to give my projectiles movement while following a  walkthrough so im a bit confused on where my values should go since I have a class involved...

### Post any code you think might be relevant (one fenced block per file)
```
 //original
class Projectile {
    constructor (x, y, width, height, radius, velocity) {
        this.x = x
        this.y = y 
        this.width = width 
        this.height = height 
        this.radius = radius 
        this.velocity = velocity 
        this.color = 'black' 
       
    }
    draw() {
        ctx.beginPath()
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI *2, false)
        ctx.fillStyle = this.color
        ctx.fill()
    }
   
//    setInterval(draw, 10);
}
     //trying to add values from tutorial 
// class Projectile {
//     constructor (x, y, dx, dy, width, height, radius, velocity) {
//          this.x = gameplayArea.width / 2
//          this.y = gameplayArea.height - 30
//         dx = 2
//         dy = -2 
//         this.width = width 
//         this.height = height 
//         this.radius = radius 
//         this.velocity = velocity 
//         this.color = 'black' 
       
//     }
//     draw() {
//         ctx.beginPath()
//         ctx.arc(this.x, this.y, this.radius, 0, Math.PI *2, false)
//         ctx.fillStyle = this.color
//         ctx.fill()
//         ctx.closePath()
//         x += dx 
//         y += dy 
//     }
//    setInterval(draw, 10);
// }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Another "x is not defined" 

### What is your best guess as to the source of the problem?
My variables are in the wrong place again...just not sure where they should be because I figured they should be inside the class.

### What things have you already tried to solve the problem?
I added the new variables in my class constructor and moved the variables around inside the class. 

### Paste a link to your repository here
https://github.com/brianaleew/Project-1

**Comment by timmshinbone** [comment]
in your draw method you're missing the keyword `this` as in `this.x` and `this.y`

**Comment by timmshinbone** [comment]
looks like it's missing from `dx` and `dy` as well in the constructor.

**Comment by brianaleew** [comment]
okay noted. I am still kind of confused. I think my brain just isnt connecting the logic behind projectiles. my projectiles went from going in a diagonal line to now all being stacked on top of each other. This is my current code
 ```js
class Projectile {
    constructor (x, y, dx, dy, width, height, radius, velocity) {
         this.x = gameplayArea.width / 2
         this.y = gameplayArea.height - 30
        this.dx = 2
        this.dy = -2 
        this.width = width 
        this.height = height 
        this.radius = radius 
        this.velocity = velocity 
        this.color = 'black' 
       
    }
    draw() {
        ctx.beginPath()
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI *2, false)
        ctx.fillStyle = this.color
        ctx.fill()
        ctx.closePath()
        this.x += this.dx 
        this.y += this.dy 
    }
 //  setInterval(draw)
}

// Trying  to create 8 random projectiles
const projectileMaker = () => {
    for (let i = 0; i < 8; i++) {
        let randomNumber = Math.floor(Math.random() * 120)
        let randomProjectile = new Projectile(randomNumber, randomNumber, randomNumber, randomNumber, 10, 10, 8, 50)
        randomProjectile.draw()
        //console.log('hi')


        // projectiles overlap! 
    }
}
```

**Comment by timmshinbone** [comment]
Briana, you should edit your last comment so that the code actually looks like code. Please add three backticks with js attached(```js) at the beginning of your code block and then three backticks at the end to close it. it'll help me read your code and respond accordingly

**Comment by brianaleew** [comment]
Thank you I was wondering why it did that. just updated it

**Comment by timmshinbone** [comment]
got it! So, your class isn't setting your x and y as random numbers like you think it is. That's because you've hard coded the coordinates in your class with these two lines:
```js
  this.x = gameplayArea.width / 2
  this.y = gameplayArea.height - 30
```

Those aren't using the x and y parameters of the constructor function at all. Rework it and you wont have them doubling up anymore!

**Comment by brianaleew** [comment]
okay so i decided to hard code the y value to one so all my projectiles can start at the top of the screen.  However, after playing around with values I still get overlap on some of my dots although they all arent on top of each other anymore. 
```js
class Projectile {
    constructor (x, y, dx, dy, width, height, radius, velocity) {
         this.x = x 
         this.y = 1
        this.dx = 2
        this.dy = -2 
        this.width = width 
        this.height = height 
        this.radius = radius 
        this.velocity = velocity 
        this.color = 'black' 
       
    }
    draw() {
        ctx.beginPath()
        ctx.arc(this.x, this.y, this.radius, 0, Math.PI *2, false)
        ctx.fillStyle = this.color
        ctx.fill()
        ctx.closePath()
        this.x += this.dx 
        this.y += this.dy 
    }
   
}
```

**Comment by brianaleew** [comment]
Closed once I got movement. Reopened because in doing that I made my player icon disappear. I think it has something to do with clearRect  clearing the canvas maybe. I tried changing the order of the game loop but it didnt help. heres how my game loop looks right now
```js
const gameLoop = () => {
    
    // check if player is alive
    // if alive make sure they arent getting hit
    if (playerStatus() === true) {
            //hit detector function here

    }
    // clear the canvas for better animation
    ctx.clearRect(0,0, gameplayArea.width, gameplayArea.height)
     // redisplay player
    playerIcon.render() 
     //loop over projectile array and call the update/move function 
    projArray.forEach((proj) => {
        proj.update()
        // console.log(projArray)
    })
        //  (velocity = amount of pixels per interval)
    

}
  gameLoop(); 
```

**Comment by brianaleew** [comment]
Hi, Alys helped resolve the icon disappearing and they were great. However, they told me to tell you they broke other things in process unfortunately. we ran out of time in office hours so im just posting the error for now so we can continue in the morning.

the error reads the following : 
"app.js:191 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at hitDetector (app.js:191:27)
    at gameLoop (app.js:249:13)
    at app.js:270:3" 

My hitDetector code is here if that helps : 
```js
 function hitDetector (thing) {
//the big if statement

 if (playerIcon.x < thing.x + thing.width
    && playerIcon.x + playerIcon.width > thing.x
    && playerIcon.y < thing.y + thing.height
    && playerIcon.y + playerIcon.height > thing.y) {
        console.log('HIT!')
        thing.alive = false
    }

}
```

Im not sure what the problem is considering that both playerIcon and thing (projectiles) have x, y, width and height properties defined.

**Comment by timmshinbone** [comment]
Show me the code where you're calling the hitDetector function, I have a suspicion that it's having trouble figuring out what the x value of the parameter `thing` is.

**Comment by brianaleew** [comment]
Also came to a similar conclusion. I tried inputting the projectile class inside as the parameter and it stopped displaying my playerIcon. hit detect param was initially empty like so : 
```js 
const gameLoop = () => {
    
    // check if player is alive
    // if alive make sure they arent getting hit
    if (playerIcon.alive === true) {
        
            //hit detector function here
            hitDetector()

    }
    // clear the canvas for better animation
    ctx.clearRect(0,0, gameplayArea.width, gameplayArea.height)
     // redisplay player
     console.log('rendering player')
     playerIcon.render() 
     //loop over projectile array and call the update/move function 
    projArray.forEach((proj) => {
        proj.update()
        // console.log(projArray)
        if (proj.y > 280) {
            projArray.splice(0, Infinity)
            console.log(projArray)
        }
    })
```

**Comment by timmshinbone** [comment]
This code is where you need to call your hit detection:
```js
projArray.forEach((proj) => {
        proj.update()
        // console.log(projArray)
        if (proj.y > 280) {
            projArray.splice(0, Infinity)
            console.log(projArray)
        }
    })
 ```
 Your `hitDetector()` function will never work unless you pass an argument in the parenthesis. So, in order to get this to work you must call that function in a place where you can refer to individual projectiles, which makes your forEach loop the perfect place to do this, so, after the line `proj.update()` add the line `hitDetector(proj)`

**Comment by brianaleew** [comment]
Wow! that makes sense.  Thank you.
