### ISSUE TITLE
Liam's Game Project - Rendering Walls

### ISSUE THREAD

**Issue by lyee197** [sei-ec-remote/project-1-issues#15]
## What's the problem you're trying to solve?
On lines 50 and 51 of JavaScript, I was trying to create a wall to start my maze but in index.html, 2 purple rectangles wouldn't appear. I tried making them their own class but I'm not sure if that was the right idead.
## Post any code you think might be relevant (one fenced block per file)
``` js
const game = document.getElementById('gameboard')
const movement = document.getElementById('movement')

const ctx = game.getContext('2d')

console.log('game befor browser attributes: \n', game)

game.setAttribute('width', getComputedStyle(game)['width'])
game.setAttribute('height', getComputedStyle(game)['width'])

console.log('wtf is ctx: \n', ctx)
console.log('game \n', game)


class Runner {
    constructor(x, y, color, height, width) {
        this.x = x,
        this.y = y,
        this.color = color,
        this.height = height,
        this.width = width,
        this.alive = true,
        this.render = function () {
            ctx.fillStyle = this.color
            ctx.fillRect(this.x, this.y, this.height, this.width)
        }
    }
}
class Wall {
    constructor(x, y, color, height, width) {
        this.x = x,
        this.y = y,
        this.color = color,
        this.height = height,
        this.width = width,
        this.alive = true,
        this.render = function () {
            ctx.fillStyle = this.color
            ctx.fillRect(this.x, this.y, this.height, this.width)
        }
    }
}


let player = new Runner(50, 200, 'red', 8, 8)
let end = new Runner(740, 200, 'blue', 8, 8)
let frontT = new Wall(50, 100, 'purple', 50, 8)
let frontB = new Wall(50, 300, 'purple', 50, 8)
```

## If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I didn't see any change whatso ever in console or html
## What is your best guess as to the source of the problem?
I need to create a new layer or maybe a new class set with different tags
## What things have you already tried to solve the problem?
I tried adjusting the height and width of the Wall, the color, new class and the position
## Paste a link to your repository here
[Repository](https://github.com/lyee197/game-project)

**Comment by tkolsrud** [comment]
It looks like the issue is that you're not running `Wall.render()` in your game loop. So the wall's are being created, but not actually rendered inside the game board

**Comment by lyee197** [comment]
Yes, that was the problem! thank you!
