### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by bruceabrigo** [sei-ec-remote/project-1-issues#150]
### What's the problem you're trying to solve?
I'm having trouble getting started on a function that will generate/animate objects from one side of the screen to the other.

### Post any code you think might be relevant (one fenced block per file)
```
class Mouse {
  constructor(x, y, width, height, color, speed) {
    this.x = x
    this.y = y
    this.width = width
    this.height = height
    this.color = color
    this.alive = true;
    // give Mouse spawn functionality form right side of canvas

    //  render contents (for now, create a rectangle)
    this.speed = 5
    // create movement functionality 

    this.dx = 1 * this.speed

    this.render = function () {
      ctx.fillStyle = this.color
      ctx.fillRect(this.x, this.y, this.width, this.height)
    }

    x = x + 1
    console.log(x)

    this.generateMice = function () {
      if (gameRunning == 'true') {
        this.x -= this.speed

        if(this.x <= 0) {
          this.x = 0
        }
      } 

    }
  }
}

  let xpos = 250
  let animate = setInterval(function(){
    xpos += 1 * 0.05
  }, 10)
  
  const target1 = new Mouse(xpos, 150, 16, 16, 'purple')
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
My thought process here was that by using an interval to continuously add to the X position, the x position will shift with the interval. I was unable to make the enemy class shift.

### What is your best guess as to the source of the problem?
Currently I'm still using canvas drawn objects over png images, to make sure I can create a functioning page. My best guess, as I used a console.log outside of my interval function, thus disabling the x variable to be returned outside globally.

### What things have you already tried to solve the problem?
I was able to use a request animation function, however this in turn would remove my player class. 

### Paste a link to your repository here
https://github.com/bruceabrigo/ratch-me-if-you-can

**Comment by asands94** [comment]
Hi Bruce, I think you're on the right track. To get an object to move from one side of the screen to the other, you'll need to change the value of `this.x` which I see you have done. Have you been able to put that into a function inside of your class, then run the function? If so what is the behavior?

**Comment by bruceabrigo** [comment]
By this, would you mean to add an interval within my mouse class that would add the integer value for x?

**Comment by asands94** [comment]
Yes exactly

**Comment by bruceabrigo** [comment]
I was able to add that loop. However, I'm having trouble finding a way to reassign that this.x value to the loop value

**Comment by asands94** [comment]
Can you share the code you have now?

**Comment by bruceabrigo** [comment]
`class Mouse {
  constructor(x, y, width, height, color, speed) {
    // this.x = x
    this.y = y
    this.width = width
    this.height = height
    this.color = color
    this.alive = true;
    // give Mouse spawn functionality form right side of canvas

    //  render contents (for now, create a rectangle)
    this.speed = 5
    // create movement functionality 

    this.dx = 1 * this.speed
  

    this.render = function () {
      ctx.fillStyle = this.color
      ctx.fillRect(this.x, this.y, this.width, this.height)
    }

    let MoveX = 0
    this.x = setInterval(function(){
      MoveX += 0.085
      console.log(MoveX)
      return MoveX
    }, 60)
  }
}

const target1 = new Mouse(150, 150, 16, 16, 'purple')`

**Comment by bruceabrigo** [comment]
Sorry about the code block, I'm still getting used to the proper way to messages as a code block.

**Comment by asands94** [comment]
it's ok! It could help to put the part where you want the x value to change inside of a function, then later you call that function

**Comment by bruceabrigo** [comment]
I very well could have misunderstood you. However I'd like to see if I'm understanding correctly or going backward. It seems as though my return value isn't returning the increment functionality I added. Though when I manually change the value, the, x position changes and remains sstationary.



`class Mouse {
  constructor(x, y, width, height, color, speed) {
    this.x = x
    this.y = y
    this.width = width
    this.height = height
    this.color = color
    this.alive = true;
    // give Mouse spawn functionality form right side of canvas

    //  render contents (for now, create a rectangle)
    this.speed = 5
    // create movement functionality 

    this.render = function () {
      ctx.fillStyle = this.color
      ctx.fillRect(this.x, this.y, this.width, this.height)
    }

  }
}

let counter = 0
const addNum = () => {
  // counter += 0.085
  // let total = counter
  // console.log(total)
  // console.log(counter)
  return counter += 0.085
}

setInterval(addNum, 60)
const target1 = new Mouse(addNum(game.width), 150, 16, 16, 'purple')
`

**Comment by asands94** [comment]
For example, you can create a function inside of your class not outside, similar to the this.render function you created. The you would call that function
