### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by AlexMcBex** [sei-ec-remote/project-1-issues#151]
### What's the problem you're trying to solve?
I'm trying to change a CSS display value of a <div> to none when a variable "gameOn" is true. if gameOn is false the game is paused  / not started and the div is supposed to give instructions when the game is launched, a pause screen when the screen is paused or a gameover screen if the game is over but it should not be visible when the game is on.

Also when the game is paused the game loop is stopped like planned, but I would like to make another interval that switches on and off the render of the object in the canvas, simulating a blinking effect.

### Post any code you think might be relevant (one fenced block per file)
```
const scoreBoard = document.getElementById("scoreBoardContainer")
if (gameOn){
    scoreBoard.style.display = "none"
}
////////////

if(!gameOn){
    const clearInterval = () =>{
         setTimeout(ctx.clearRect(0, 0, game.width, game.height), 250)
     }
    const pauseInterval = setInterval(() =>{
         clearInterval()
         stopGameLoop()
        goodFish.render()
        bombFish.render()
        player.render()
     }, 1000)
} 
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
the div remains visible when the game is on but no error message is shown
I don't know how to activate the interval for the paused game

### What is your best guess as to the source of the problem?
I'm probably using the wrong syntaxes or I'm placing the if statements in the wrong spot

### What things have you already tried to solve the problem?
for the div I tried to change the z-index to -1 to place it behind the other elements but it doesn't work either

for the interval I tried to put it in and out the game loop function, when it's out it doesn't work, when it's in the blinking effect looks too glitchy, I guess because it is an interval nested inside another interval

### Paste a link to your repository here
https://github.com/AlexMcBex/Fish-in-a-Bucket---Project-1

**Comment by asands94** [comment]
Sometimes it helps to do a console log to see whats happening. For example, you can do a console log for `scoreBoard.style.display` and see what that value is and if it's actually switching to none when you expect it to

**Comment by AlexMcBex** [comment]
I nested the if statement for the div display in another function and now it works! I'm working on it now. 
I could still use some help with the Interval
Thank you!

**Comment by asands94** [comment]
You want to create blinking objects? If so, try looking up some animation effects that you can then manipulate in your JS file

**Comment by AlexMcBex** [comment]
I'll try the animation then, thank you very much!
