### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by bruceabrigo** [sei-ec-remote/project-1-issues#160]
### What's the problem you're trying to solve?
Need to push target/enemy array into canvas

### Post any code you think might be relevant (one fenced block per file)
```js
class Mouse {
  constructor(x, y, width, height, color) {
    this.x = x
    this.y = y
    this.width = width
    this.height = height
    this.color = color
    this.alive = true;
    // add this.img
    // give Mouse spawn functionality form right side of canvas

    //  render contents (for now, create a rectangle)
    this.speed = 4
    // create movement functionality 
  }
    render () {
      ctx.fillStyle = this.color
      ctx.fillRect(this.x, this.y, this.width, this.height)
      
    }

    // create function that makes an array 
    // push the array into canvas 
    // use for loop to generate an array

    displayMiceArmy () {
      this.x -= this.speed

      miceArray.forEach(obj => {
        this.render()
        this.animateMouse()
      })
    }

     animateMouse(timsestamp) {
      this.x -= this.speed

      if(this.x <= -20) {
        for (let i = 0; miceArray < 5; i++) {
          miceArray.push(new Mouse())
          console.log(miceArray)
        }
        this.x = 600
        this.y = Math.floor(Math.random() * game.height) - 10
      }
    }
    
  }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
the target class is printing out at an unexpected speed when the initial class object reaches the end of the canvas and eventually covers the entire canvas.

### What is your best guess as to the source of the problem?
could be the function lacks a timer to print each mouse array item

### What things have you already tried to solve the problem?
i've tried moving for loop into various different functions to try and change result

### Paste a link to your repository here
https://github.com/bruceabrigo/ratch-me-if-you-can

**Comment by timmshinbone** [comment]
Share the code for your game loop

**Comment by bruceabrigo** [comment]
`function gameLoop () {

  /* --- Foh da Character!--- */
  ctx.clearRect(0, 0, game.width, game.height)
  player.render()
  player.moveCat()
  mouse.render()
  mouse.animateMouse()
  rat.render()
  rat.animateMouse()
  trap.render()
  trap.revealTrap()
  /* --- Collision Detection --- */
  if(mouse.alive) {
    rat.render()
    collisionDetection(mouse)
    ratPoints(rat)
    theseHurt(trap)
  }
}`

**Comment by bruceabrigo** [comment]
```js
function gameLoop () {

  /* --- Foh da Character!--- */
  ctx.clearRect(0, 0, game.width, game.height)
  player.render()
  player.moveCat()
  mouse.render()
  mouse.animateMouse()
  rat.render()
  rat.animateMouse()
  trap.render()
  trap.revealTrap()
  /* --- Collision Detection --- */
  if(mouse.alive) {
    rat.render()
    collisionDetection(mouse)
    ratPoints(rat)
    theseHurt(trap)
  }
}
```

**Comment by bruceabrigo** [comment]
Before we go head out for lunch I was able to create a new function in my Mouse class
```
    newMouse() {
      this.miceArray.push(new Mouse(600, Math.floor(Math.random() * game.height) - 25, 30, 16, 'purple'))
        console.log(this.miceArray)
      this.render()
    }
```
This allowed me to add to the array, but without an input. I console logged the array and its printing a new mouse object to the array, per the gameLoop interval.

**Comment by timmshinbone** [comment]
What you need is a function that just pushes mice into an array that lives in the global scope, then inside your gameloop you can loop over that array and call render on each mouse.

**Comment by bruceabrigo** [comment]
I'm having trouble understanding how to properly loop through the array.

However I was able to create the array

![Screen Shot 2023-01-06 at 1 33 16 PM](https://user-images.githubusercontent.com/109409601/211086043-9efc537a-4e10-4cad-8244-0e2619354acf.png)

I tried using a for loop in the gameLoop and it crashed my broswer

**Comment by bruceabrigo** [comment]
This is my function 
```js
  function newMice () {

   miceArray.push(new Mouse(600, Math.floor(Math.random() * game.height) - 25, 30, 16, 'purple'))
   console.log(miceArray)
 }

```

**Comment by timmshinbone** [comment]
I'd say try a forEach instead, I'll slack ya soon and we can take a look in a breakout room
