### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by tthephas** [sei-ec-remote/project-1-issues#163]
### What's the problem you're trying to solve?
trying to make my "ball" , a sphere and not a rectangle. using the arc feature. i got it to render (in the render part of the ball build) as a sphere. and i can get it to move fine. but , its not bouncing off the paddle or registering a loss. so i'm sure i missing some fix to other code, after changing the rectangle to a sphere. just cant see where or why

### Post any code you think might be relevant (one fenced block per file)
```
        this.render = function () {
            //ctx.fillStyle = this.color
            //ctx.fillRect(this.x, this.y, this.width, this.height)
            
            /// does this make a ball? yes! LOOKS LIKE ONE. DOESNT MOVE THOUGH
            ctx.beginPath()
            // put THIS for all these and then fix in constructor too
            //ctx.arc(400, 50, 10, 0, Math.PI * 2)
            // x , y , radius, start angle, end angle
            ctx.arc(this.x, this.y, this.radius, this.sAngle, this.eAngle)
            ctx.fill()

more code for the ball build
const ballOne = new Ball(400, 50, 8, 0, Math.PI * 2, 'black')


```

### What is your best guess as to the source of the problem?
something in the detect hit function, or render function, that worked for rectangle and not sphere. possibly. now that the ball has a radius? but i'm confused b/c it still has an x, y as it moves. so the detect hit and bounce, i'd think woudl still work, b/c those just go off the x and y coming together. 

### What things have you already tried to solve the problem?
confirmed ball is a sphere, it moves on my key down listener just fine, it moves in teh right direction. it just doesnt stop

### Paste a link to your repository here
https://github.com/tthephas/New-Pong-Game (had to start a new repository due to an odd folder error that ashley helped with. that is why you only see 2 commits)

**Comment by timmshinbone** [comment]
Share your detectHit functionality here

**Comment by tthephas** [comment]
i might have found the spot. changed width/height to radius. i'm testing those fixes now. brb if still an issue

**Comment by tthephas** [comment]
fixed. it was just some width/height instances i needed to change to radius. ball bouncing now and is a sphere. super cool. thx !
