### ISSUE TITLE
Grid suddenly renders as line

### ISSUE THREAD

**Issue by smsgoldberg** [sei-ec-remote/project-1-issues#165]
### What's the problem you're trying to solve?
The game squares on my board were in a nice grid pattern over the weekend. When I run the file today, they display as a single line of squares -- despite being explicitly set to grid in the CSS. I have made no changes to the CSS that I can recall since Friday or Saturday. 

### Post any code you think might be relevant (one fenced block per file)
```  <div class="gameCard">
   <header>Stay Golden</header>
   <div class="scoreboard"><h2>Placeholder Text</h2></div>
   <section id="board">
        <div class="circles" id="circle-0"></div>
        <div class="circles" id="circle-1"></div>
        <div class="circles" id="circle-2"></div>
        <div class="circles" id="circle-3"></div>
        <div class="circles" id="circle-4"></div>
        <div class="circles" id="circle-5"></div>
        <div class="circles" id="circle-6"></div>
        <div class="circles" id="circle-7"></div>
        <div class="circles" id="circle-8"></div>
        <div class="circles" id="circle-9"></div>
        <div class="circles" id="circle-10"></div>
        <div class="circles" id="circle-11"></div>
        <div class="circles" id="circle-12"></div>
        <div class="circles" id="circle-13"></div>
        <div class="circles" id="circle-14"></div>
        <div class="circles" id="circle-15"></div>
    </section>
    <button id="btn">Play Again</button>
  </div>

```

```
body {
    display: flex;
    align-items: center;
    flex-direction: column;
    height: 100vmin;
}


.gameCard {
    display: flex;
    align-items: center;
    flex-direction: column;
    border: 5px solid #A63429;
    background-color: #F2A518;
}


.scoreboard {
    border: 3px solid #A63429;
    border-radius: 10px;
    background-color: #F2A518;
}

header {
    display: flex;
    align-items: center;
    flex-direction: column;
    border: 1px solid black;
    font-family: 'Grand Hotel', cursive;
    font-size: 72px;
    color: #A63429;
    text-align: center;
}

section {
    border: 1px solid black;
    display: grid;
}

.circles {
    display: grid;
    border: 1px solid black;
    padding: 30px;
    grid-template-columns: repeat(4, 15vmin);
    grid-template-rows: repeat(4, 15vmin)
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I have one minor JS syntactical error but it doesn't appear to be relevant -- see answer below. 

### What is your best guess as to the source of the problem?
I can't help but think it must be CSS-related. I actually posted both HTML and CSS code to another IDE, sans JavaScript, to see if my fiddling around with JS is the source of the problem -- only to have the same error pop up. 

### What things have you already tried to solve the problem?

I tried deleting <img> tags from my HTML and commenting out the img styling from my CSS. It doesn't seem to have been particularly effective. 

### Paste a link to your repository here
https://github.com/smsgoldberg/StayGolden/commits/main

**Comment by nabi-cloud** [comment]
Hi @smsgoldberg! I think you're missing a semicolon **;** on the `grid-template-rows` property.

**Comment by smsgoldberg** [comment]
> Hi @smsgoldberg! I think you're missing a semicolon **;** on the `grid-template-rows` property.

Thanks! I actually just caught that. Not sure how that happened since I don't recall tinkering with the CSS at all yesterday. Some things must remain a mystery.

**Comment by nabi-cloud** [comment]
No worries! Have fun coding 🙂
