### ISSUE TITLE
Game project issue/ can't attach images to my div classes

### ISSUE THREAD

**Issue by Kateattardo** [sei-ec-remote/project-1-issues#169]
### What's the problem you're trying to solve?
Can't attach images to my div classes.  The images are for my cards in the game concentration.  Yesterday I uploaded all the images to Imugr and had those links in my HTML.  I wasn't able to attach them yesterday.  This morning I added them to my already exsisting image folder and tried to link them directly form there.

### Post any code you think might be relevant (one fenced block per file)
```
<div class="cards">
  <div class="card a1card front![Augie](images/Images for cards/IMG_Augie.JPG) "onclick="flip">
</div>

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
This is the only error message in my console:
Uncaught SyntaxError: Unexpected identifier 'on'

### What is your best guess as to the source of the problem?
I suspect it's all the extra words for the image folder but don't want to lose any more time to this.

### Paste a link to your repository here
https://github.com/Kateattardo/Concentration-A-simple-game.git

**Comment by timmshinbone** [comment]
You should place `<img>` tags inside of those divs and use the image link as the `src` attribute. This syntax you've used here: `![Augie](images/Images for cards/IMG_Augie.JPG)` is only for markdown (`.md`) type files like the README.

**Comment by timmshinbone** [comment]
Furthermore, when you get to the DOM manipulation aspect, you'll be targeting and changing the `src` attribute accordingly, very similar to how we did this in the Rock, Paper, Scissors codealong

**Comment by Kateattardo** [comment]
Okay great thank you!

**Comment by Kateattardo** [comment]
Sorry one more question I use src followed by the image info in my images folder correct?

**Comment by timmshinbone** [comment]
That's right, the src attribute [should path to an image file](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#try_it). Whether the path is a link or a file location, it should be set up just like the example on MDN
