### ISSUE TITLE
Getting objects into array --Nikki

### ISSUE THREAD

**Issue by NikPurvis** [sei-ec-remote/project-1-issues#17]
### What's the problem you're trying to solve?
I can't get the objects I'm trying to create to go into their array so I can call on them throughout the game.

### Post any code you think might be relevant (one fenced block per file)
```javascript
const game = {
    
    wokeItems: [],

    startGame() {
        this.makeWoke();
    },

    makeWoke() {
        // Creation of the "woke" canvaspieces (to be replaced with
        // images) with the declared values: (wokeName, wokeColor,
        // wokeWidth, wokeHeight, wokeDropRate, wokeValue)
        if (gameOver === false) {
            const refill = new WokeItem("refill", "rgb(92, 47, 17)", 37, 28, 50, 10)
            const energyDrink = new WokeItem("energyDrink", "silver", 25, 75, 100, 50)
            const molecule = new WokeItem("molecule", "teal", 100, 75, 30, 100)
            // Create one of the items at random
            random = randomNum(1, 3)
            if (random === 1) {
                this.wokeItems.push(refill)
            } else if (random === 2) {
                this.wokeItems.push(energyDrink)
            } else if (random === 3) {
                this.wokeItems.push(molecule)
            }
        }
        console.log("contents of wokeItems", this.wokeItems)
    },
}   // game Object end bracket
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Uncaught ReferenceError: startGame is not defined
    at script.js:169:1
(anonymous) @ script.js:169

Which is the current version, but I've had an assortment of "not defined" messages as I tried to get this to go.

### What is your best guess as to the source of the problem?

There's something fundamental I'm not getting about how to get the stuff I'm creating to go into the array as an object. By my understanding, what I have SHOULD work, but here we are.

### What things have you already tried to solve the problem?
I've only just put the makeWoke function into a blanket object, so -- I THOUGHT -- I could call on it from anywhere inside that object with "this.". I had everything working okay when I was hard coding the numbers, but obviously that isn't the solution I ultimately want, or need as my projects get more complicated.

### Paste a link to your repository here
 https://github.com/NikPurvis/game-project

**Comment by tkolsrud** [comment]
Two thoughts:

1.) This object/method is actually working properly you just need to call it with `game.startGame()` on line 169.

2.) Having an array that randomly fills with one of three items is a good idea, but if it's something that's continuously happening throughout the game, having it run as a startGame function doesn't necessarily make the most sense? It seems like something that should be running inside of your game loop.

**Comment by NikPurvis** [comment]
Great suggestions, I'll definitely see about implementing those. In the meantime, I've added ```game.startGame()``` so of course now I'm back with another array problem.

```
script.js:159 Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at makeWoke (script.js:159:32)
```

I'll push my updated js with the above change.

**Comment by tkolsrud** [comment]
I think the issue you're running into is that `game` should really be a class that you extend into an object. I think the program's upset because you're assigning a variable inside of a variable declaration -- bc everything's functioning correctly, except that `wokeItems` isn't successfully being defined.

**Comment by tkolsrud** [comment]
You could also just make `wokeItems` a gobal variable and `makeWoke()` etc could just be functions instead of methods*

**Comment by NikPurvis** [comment]
Yeah, I think I'll try using those options to make this work. Lots of things to streamline it, which (ideally!) will either get it working, or help me narrow down specifically what the problem is besides just "thingie no worky".

Thanks a bunch! I'll work on that and open a new issue if needed. Hopefully not needed. I appreciate it!
