### ISSUE TITLE
Cannot render background images visible on click

### ISSUE THREAD

**Issue by smsgoldberg** [sei-ec-remote/project-1-issues#170]
### What's the problem you're trying to solve?
I'm trying to have the images for my matching game hidden by default, with the images only becoming visible on click. 

### Post any code you think might be relevant (one fenced block per file)
```
img {
    border-radius: 50%;
    border: 1px solid #A63429
    height: 100%;
    width: 50%;
    visibility: hidden;
}
```

```
 function handleMove(event) {
  const tileIdx = tiles.indexOf(event.target);
  console.log('this is tileIdx in handleMove', tileIdx);
  //the below code does not work in terms of rendering individual images visible
 // tiles[tileIdx].backgroundImage = 'visible';
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
_Cannot set properties of undefined (setting 'backgroundImage')
    at HTMLElement.handleMove_

I'm also noticing that clicking on the tile containing the image does give the correct tile index, while clicking on the image itself returns a value of -1. (If we comment out the visibility on the img CSS tag, this is a non-issue)

### What is your best guess as to the source of the problem?
I think I'm not accessing the element correctly. 

### What things have you already tried to solve the problem?

I had tried fiddling with the syntax in the handleMove function -- trying .img, .backgroundImage, adding and subtracting .style. 
I suspect my problem is fundamentally logical or a lack of quite understanding what it is I'm doing. 

### Paste a link to your repository here
https://github.com/smsgoldberg/StayGolden

**Comment by asands94** [comment]
Make sure when you are setting a style in your JS file, that you use `.style` before the property you want to change. So something like `div.style.visibility = "visible"`

**Comment by smsgoldberg** [comment]
Thanks!  I've tried both 
 tiles[tileIdx].img.style.visibility = 'visible';

and

 tiles[tileIdx].backgroundImage.style.visibility = "visible"

 but I'm still not having much luck.

**Comment by asands94** [comment]
I would do a console log for `tiles[tilesdx]` and see what properties you have. For example, do you see `img` when you do that console log and see a list of properties available?

**Comment by asands94** [comment]
I just looked at your code and I see that `img` is a child of the tile so you need to access the child using `.children` for example, before you can play around with the styling of it.

**Comment by smsgoldberg** [comment]
Interesting! So far I haven't been successful with .children but I'll keep trying. I'm wondering if the HTML is ultimately the problem here? Because this program relies on being able to randomize the image array on each playthrough, I haven't actually fixed any src attribute to any of my image files.

**Comment by asands94** [comment]
What specifically did you try with `.children`? I tried it out with your code and it worked for me. OH I forget to mention, you're missing a semicolon in your CSS around line 79

**Comment by smsgoldberg** [comment]
Thanks for letting me know about the CSS! I'm trying

tiles[tileIdx].children.style.visibility = "visible"; 

but not getting the desired behavior from it.

**Comment by asands94** [comment]
Let's jump into room 15 for a moment, part of the problem is when you have children you have a list so you have to select a specific index like `children[0].style`
