### ISSUE TITLE
Broken Display

### ISSUE THREAD

**Issue by smsgoldberg** [sei-ec-remote/project-1-issues#172]
### What's the problem you're trying to solve?
I tried to add the game tokens that appeared in my wireframe -- and doing so appears to break the game display altogether

### Post any code you think might be relevant (one fenced block per file)
```html
<section id="board">
        <div class="circles" id="circle-0"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-1"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-2"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-3"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-4"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-5"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-6"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-7"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-8"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-9"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-10"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-11"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-12"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-13"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-14"><div class="game-token"><img></div></div>
        <div class="circles" id="circle-15"><div class="game-token"><img></div></div>
    </section>
```
```js
//supposed to hide token over dog image-- but it doesn't work yet 
function hideToken(tileIdx) {
  tiles[tileIdx].children[0].style.visibility="hidden";
}

 function handleMove(event) {
  const tileIdx = tiles.indexOf(event.target);
  console.log('this is tileIdx in handleMove', tileIdx);
  console.log(tiles[tileIdx]);
  //tiles[tileIdx].children[0].style.visibility = "visible";
  if (!firstClickChoice) {
    firstClickChoice = tiles[tileIdx].children[1];
    hideToken(tileIdx);
    tiles[tileIdx].children[1].style.visibility = "visible";
    console.log('this is firstClickChoice', firstClickChoice) 
  } else {
    secondClickChoice = tiles[tileIdx].children[1];
    hideToken(tileIdx);
    tiles[tileIdx].children[1].style.visibility = "visible";
    console.log('this is secondClickChoice', secondClickChoice);
  }
  compareChoices(firstClickChoice, secondClickChoice);
}
```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

main.js:139 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at HTMLElement.handleMove (main.js:139:32)

### What is your best guess as to the source of the problem?
I honestly don't know. There is a recurring issue with all images moving one space to the right, or else not displaying at all. 

### What things have you already tried to solve the problem?
I tried changing tiles[tileIdx].children to [1] where images were concerned since the new div would presumably be children[0]

### Paste a link to your repository here
https://github.com/smsgoldberg/StayGolden

**Comment by smsgoldberg** [comment]
So line 159 is doing some interesting stuff. I get "cannot read properties of undefined (reading children)" if use
tiles[titleIdx].children[1].style.visibility = "visible" 

but I get  "cannot read properties of undefined (reading style)" if I remove it

**Comment by timmshinbone** [comment]
That means the function doesn't know what `tiles` are, try console logging them right at the top of the function, you should see that they're undefined, so, it begs the question, how can you get that function to read your tiles?
