### ISSUE TITLE
Can't create a copy of an array of objects

### ISSUE THREAD

**Issue by lucas-richards** [sei-ec-remote/project-1-issues#173]
### What's the problem you're trying to solve?
my main array of objects variable is not being initialized. the flip property of flipped cards is still set to true.

### Post any code you think might be relevant (one fenced block per file)
```javascript

const deck = [
{name:'hK', click:false, flip:false},
{name:'hQ', click:false, flip:false},
{name:'hJ', click:false, flip:false},
{name:'h10', click:false, flip:false},
{name:'h09', click:false, flip:false},
{name:'h08', click:false, flip:false},
{name:'h07', click:false, flip:false},
{name:'h06', click:false, flip:false},
{name:'h05', click:false, flip:false},
{name:'h04', click:false, flip:false},
{name:'h03', click:false, flip:false},
{name:'h02', click:false, flip:false},
]



function init(){
    //create a copy of the deck
    let newDeck = deck.slice()//this does not create copy, is the same object
    
    //initialize variables
    clickedCardStr = null

    winner = 0

    topPiles = [
        {name:'ph',cards:[{name:'h', click:false, flip:true}]},
        {name:'pc',cards:[{name:'c', click:false, flip:true}]},
        {name:'pd',cards:[{name:'d', click:false, flip:true}]},
        {name:'ps',cards:[{name:'s', click:false, flip:true}]},
    ]

    midPiles = [
        {name:'p0',cards:[]},
        {name:'p1',cards:[]},
        {name:'p2',cards:[]},
        {name:'p3',cards:[]},
        {name:'p4',cards:[]},
        {name:'p5',cards:[]},
        {name:'p6',cards:[]},
    ]
    
    botPiles = [
        {name:'bp0',cards:[]},
        {name:'bp1',cards:[]},
    ]

    deal(newDeck)

    render()
    
}

//deal function distributes the cards on the table 1,2,3,4,5,6,7 and 24 
function deal(newDeck){
    // migth use this for random numbers
    // console.log(Math.floor(Math.random()*Number(deck.length)))
    num = 1
    midPiles.forEach((pile)=>{
        for(let i=0; i < num; i++){
            pile.cards.push(newDeck.pop())
        }
        pile.cards[pile.cards.length-1].flip = true
        num++
    })

    botPiles[0].cards = newDeck

    console.log(midPiles)

}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
newDeck is becaming a copy of deck but the properties values are the same.

### What is your best guess as to the source of the problem?
the mothod doesn't create a copy of the properties

### What things have you already tried to solve the problem?
I have tried the spread operator and setting all the properties to false when init() runs

### Paste a link to your repository here
https://github.com/lucas-richards/Solitaire-with-cards

**Comment by timmshinbone** [comment]
When you `console.log` the `newDeck` what does it show? Also, can you share all of the contents of your `init` function here?

**Comment by lucas-richards** [comment]
Array before init 
: 
Array(7)
0
: 
{name: 's09', click: false, flip: false}
1
: 
{name: 's10', click: false, flip: false}
2
: 
{name: 'sJ', click: false, flip: false}
3
: 
{name: 'sQ', click: false, flip: false}
4
: 
{name: 'sK', click: false, flip: false}
5
: 
{name: 'dA', click: false, flip: false}
6
: 
{name: 'd02', click: false, flip: true}
length
: 
7

Array after init 
: 
Array(7)
0
: 
{name: 's09', click: false, flip: false}
1
: 
{name: 's10', click: false, flip: false}
2
: 
{name: 'sJ', click: false, flip: false}
3
: 
{name: 'sQ', click: false, flip: false}
4
: 
{name: 'sK', click: false, flip: false}
5
: 
{name: 'dA', click: false, flip: true}
6
: 
{name: 'd02', click: false, flip: true}
length
: 
7

**Comment by lucas-richards** [comment]
> 
![Screen Shot 2023-08-09 at 06 50 52 AM](https://github.com/sei-ec-remote/project-1-issues/assets/126919073/7f2feeab-8cee-45d2-9446-f11bd35aa981)

**Comment by lucas-richards** [comment]
I just solved it using
let newDeck = JSON.parse(JSON.stringify(deck))
This one safely copies deeply nested objects/arrays!
Thank you

**Comment by timmshinbone** [comment]
Great! Glad you got it worked out!
