### ISSUE TITLE
Git push issue

### ISSUE THREAD

**Issue by noahD0zer** [sei-ec-remote/project-1-issues#175]
### What's the problem you're trying to solve?
pushing to git it says everything up to date but it is not

### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?
something to do with remote origin?

### What things have you already tried to solve the problem?
stackoverflow

### Paste a link to your repository here
https://git.generalassemb.ly/noahdozer/777

**Comment by asands94** [comment]
The github repo you just shared with us is your github enterprise, you should be using your regular github account. 

Make sure you're in the right folder when pushing up your code.

**Comment by asands94** [comment]
Are you still haveing github issues?
