### ISSUE TITLE
minesweeper 

### ISSUE THREAD

**Issue by kxiside** [sei-ec-remote/project-1-issues#176]
### What's the problem you're trying to solve?
Setting flags that stop any actions from going through

### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?
missing a function or if statement 

### What things have you already tried to solve the problem?
iv tried adding different statements and even a function but i cant get it to work correctly

### Paste a link to your repository here
https://github.com/kxiside/starsweeper

**Comment by timmshinbone** [comment]
We need to see some code here so we have some more context, share your flag placing function, or the game object, or whatever aspects of your code are associated with this feature so we can look and get you the guidance that you need.

**Comment by kxiside** [comment]
```
 // setting ships and removing them from cells
    if(shipSet) {
        if (cell.innerText == "") {
            cell.innerText = "ship"
        } else if (cell.innerText == "ship") {
            cell.innerText = ""
        }
        return
```

**Comment by kxiside** [comment]
```
function renderShip() {

    // setting ship background color depending on true or false
    shipSet = !shipSet;

    // ship marker is tied to html element "ship"
    // if ship button is darkgray its set on otherwise its off
    document.getElementById("ship").style.backgroundColor = shipSet ? "darkgray" : "lightgrey";
  }
```

**Comment by kxiside** [comment]
```
if(cell.innerText === "ship") {
        return
    }
```
adding this to the cellPress function allowed the proper use for flags. They now prevent extra clicks when placed.
