### ISSUE TITLE
Images not showing after deployed

### ISSUE THREAD

**Issue by jadewang425** [sei-ec-remote/project-1-issues#177]
### What's the problem you're trying to solve?
Images not showing on GitHub page, but everything works fine in VS Code preview...

### Post any code you think might be relevant (one fenced block per file)
```
animal.style.backgroundImage = `url(/imgs/${animalAtt}.png)`
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
- Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
- goat.png:1     GET https://jadewang425.github.io/imgs/goat.png 404

### What is your best guess as to the source of the problem?
Image location?

### What things have you already tried to solve the problem?
I'm not sure how to...

### Paste a link to your repository here
https://github.com/jadewang425/memory-game
https://jadewang425.github.io/memory-game/

**Comment by asands94** [comment]
Where you're referencing your images, try changing it to `./imgs/` instead of `/imgs/`

**Comment by jadewang425** [comment]
Hi Ashley, I added the . and push it. In GitHub JS file, the line is not updated, but in VS code terminal, it says the file is updated...

**Comment by asands94** [comment]
I see it's updated on line 121 on github. Was there another line you want updated?

**Comment by jadewang425** [comment]
But the period didn't show in front of /imgs/ 
Is it possible that the change is just too small for GitHub to notice...?

**Comment by jadewang425** [comment]
I think I finally see the updates just now. Thanks for the help!

**Comment by asands94** [comment]
I dont think so, I see the change on github. Are you not seeing it? I'm looking at your main branch
