### ISSUE TITLE
Ongoing Issue 

### ISSUE THREAD

**Issue by smsgoldberg** [sei-ec-remote/project-1-issues#178]
### What's the problem you're trying to solve?
I'm trying to add additional game logic and getting more TypeErrors.

main.js:132 Uncaught ReferenceError: titleIdx is not defined
    at evaluatePairs (main.js:132:27)
    at HTMLElement.handleMove (main.js:166:3)
2main.js:154 Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at HTMLElement.handleMove (main.js:154:18)
main.js:116 Uncaught TypeError: Cannot read properties of undefined (reading 'src')
    at compareChoices (main.js:116:40)
    at HTMLElement.handleMove (main.js:165:16)

### Post any code you think might be relevant (one fenced block per file)
```
 //compare the user's choices
 function compareChoices(firstChoice, secondChoice) {
  if (firstChoice.src === secondChoice.src) {
    console.log('Match');
    match = true;
  } else {
    console.log('Not a match');
    match = false;
  }
   return match;
}

function evaluatePairs(firstChoice, secondChoice, match) {
  console.log('this is evaluate pairs', evaluatePairs);
  if (match === true) {
    matchedPairsArray.push(firstChoice);
    matchedPairsArray.push(secondChoice);
  } else {
    showToken(firstChoice[titleIdx]);
    showToken(secondChoice[titleIdx]);
  }
  console.log('this is matched pairs array', matchedPairsArray)
}


//display token
function showToken(tileIdx) {
  tiles[tileIdx].children[0].style.visibility="visible";
  console.log(tiles[tileIdx].children[0]);
}


//hide token
function hideToken(tileIdx) {
  tiles[tileIdx].children[0].style.visibility="hidden";
}


 function handleMove(event) {
  const tileIdx = tiles.indexOf(event.target);
  tiles[tileIdx].children[0].children[0].style.visibility = "visible";
  if (!firstClickChoice) {
    firstClickChoice = tiles[tileIdx].children[0].children[0];
   hideToken(tileIdx);
   showDog(firstClickChoice);
  } else {
    secondClickChoice = tiles[tileIdx].children[0].children[0];
    hideToken(tileIdx);
    showDog(secondClickChoice);
    tiles[tileIdx].children[0].children[0].style.visibility = "visible";
  }
  let result = compareChoices(firstClickChoice, secondClickChoice);
  evaluatePairs(firstClickChoice, secondClickChoice, result);
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

main.js:132 Uncaught ReferenceError: titleIdx is not defined
    at evaluatePairs (main.js:132:27)
    at HTMLElement.handleMove (main.js:166:3)
2main.js:154 Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at HTMLElement.handleMove (main.js:154:18)
main.js:116 Uncaught TypeError: Cannot read properties of undefined (reading 'src')
    at compareChoices (main.js:116:40)
    at HTMLElement.handleMove (main.js:165:16)

### What is your best guess as to the source of the problem?
 I'm completely flummoxed on this one. 

### What things have you already tried to solve the problem?
Adding and removing .children properties was what I assumed the solution must be since it seemed to work for us the first time. Trying the same trick here doesn't seem to work. 

### Paste a link to your repository here
https://github.com/smsgoldberg/StayGolden

**Comment by asands94** [comment]
This means `titleIdx` does not exist as a variable in the context that you're using it in. Make sure that you have defined and are using it in the right spot.
```js
main.js:132 Uncaught ReferenceError: titleIdx is not defined
at evaluatePairs (main.js:132:27)
```

With the other errors, I suggest doing console logs to see if the variables you're using have the information you're expecting. For example if the code you have is `titleIdx.children` do a console log for `titleIdx` because whatever comes before `children` is what currently is undefined.

**Comment by smsgoldberg** [comment]
If I take out children to avoid the undefined (reading children) error it gives me Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at showToken (main.js:141:18)
    at evaluatePairs (main.js:132:5)
    at HTMLElement.handleMove (main.js:167:3)

**Comment by asands94** [comment]
Don't just remove children and keep style, remove children and everything you have after it and do a console log to see what data is being returned
