### ISSUE TITLE
Play Again Button Doesn't Work 

### ISSUE THREAD

**Issue by smsgoldberg** [sei-ec-remote/project-1-issues#179]
### What's the problem you're trying to solve?
My 'play again' button pops up at the end of the game as it's supposed to, but then doesn't respond at all. 

### Post any code you think might be relevant (one fenced block per file)
```
function populateBoard() {
 //we should probably use forEach to populate the board elements 
  tiles.forEach((circle, circleIdx) => {
    console.log('this is circle', circle);
    console.log('this is circleIdx', circleIdx);
     tiles[circleIdx].style.backgroundImage = shuffledTiles[circleIdx].backgroundImage; 
     tiles[circleIdx].querySelector('img').setAttribute('src', shuffledTiles[circleIdx].backgroundImage);
    //  tiles[circleIdx].children[0].children[0].style.visibility = 'hidden';
    hideDog(circleIdx);
    showToken(circleIdx);
   //  console.log( tiles[circleIdx].querySelector('img').setAttribute('src', shuffledTiles[circleIdx].backgroundImage));
  });
    playAgainButton.visibility = 'hidden';
 }
```
```
 function renderButton() {
  playAgainButton.style.visibility = (win !== null) ? 'visible' : 'hidden';
 }
```
```
/* --- event listeners ---  */
//enables player to reset the board for a new game
playAgainButton.addEventListener('click', initializeGame);
//allows the player to click on a tile to make a move
document.getElementById('board').addEventListener('click', handleMove);

/*----functions----*/

initializeGame();

//this function initializes each new game 
function initializeGame() {
  //the win condition will be set to null
 match = null;
 endCondition = null;
 //shuffle the tiles
 shuffledTiles = shuffleTiles(mergedDogArray)
 console.log(shuffledTiles);
 //populate the game board
  populateBoard();
  //start the clock
  renderClock(() => {
    checkWinner();
  }
  );
}

```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm not seeing any error message, but the button doesn't seem to restart the clock. The board does appear to be reshuffling like it's supposed to.

### What is your best guess as to the source of the problem?
I feel like a function isn't being called somewhere

### What things have you already tried to solve the problem?
I tried adding renderClock() to the event listener and also tried adding it to renderButton()

### Paste a link to your repository here
https://github.com/smsgoldberg/StayGolden

**Comment by timmshinbone** [comment]
Share the code for the function `renderClock` and make sure your `initialize` function is resetting ALL of the state of your app that's required for a new game. For example, it doesn't seem to reset the `win` variable.

**Comment by smsgoldberg** [comment]
```js
//timer function that expires after 60 seconds 
 function renderClock(cbFunc) {
  count = 60;
  messageEl.style.visibility = 'visible';
  messageEl.innerText = count; 
  const timerID = setInterval(() => {
   count--
   if (count  && gameOver===false) {
    messageEl.innerText = count;
   } else {
    clearInterval(timerID)
    // messageEl.style.visibility = 'hidden';
    cbFunc();
   }
  }, 600)

 } 
```
At present, I've used the basic code from the rock, paper, scissors project, modified a bit for this project. I also discovered that I had left myself a note last night about setting win to null within initializeFunction, though actually implementing it there doesn't seem to make any difference in terms of the clock remaining frozen when I hit the play again button.

```js
initializeGame();

//this function initializes each new game 
function initializeGame() {
 win = null;
 match = null;
 //shuffle the tiles
 shuffledTiles = shuffleTiles(mergedDogArray)
 console.log(shuffledTiles);
 //populate the game board
  populateBoard();
  //start the clock
  renderClock(() => {
    checkWinner();
  }
  );
}

```

**Comment by timmshinbone** [comment]
It's understandable to start with Rock Paper Scissors code as a baseline example, but, aren't the two clocks serving different purposes? The R.P.S. clock counts down from 3 before revealing player/computer selections. Your clock is supposed to run for one entire game, correct? It also appears as though the only thing that will stop the clock from running is the condition: `count  && gameOver===false` which is saying "If the count is positive, and gameOver is false", which means you need to set the count to 0 somewhere outside of the `renderClock` function(impossible) **OR** you need to change the `gameOver` to `true` **SOMEWHERE** in your code, and then call the clock function again.

**Comment by smsgoldberg** [comment]
Yes, my clock is supposed to run for one entire game cycle before, after which the message board should let the player know if they've met the basic win conditions (i.e. matchedPairsArray.length = 16 before the clock runs out.)  renderClock is supposed to call the checkWinner function that resets gameOver to true, but it doesn't seem to be working as intended. 

I have found one _very _ interesting bug while trying to fix this. On a hunch I set gameOver to false within initializeFunction in the hopes that it would reset the clock when the play again button is clicked. This actually does reset the clock -- but it seems to set the countdown to an interval of 2 (e.g. from 60 to 58 seconds instead of 60 -> 59 - 58 ->) and continues the count into the negative numbers after the clock hits zero.

**Comment by timmshinbone** [comment]
So I think what you need to do is declare the timerId outside of renderClock `let timerId`, then inside render clock, instead of `const timerId`, just set it to `timerId = <setInterval code here>`, that way you can call `clearInterval(timerId)` anywhere you want to inside of your code(which should happen first in your `initialize` function, then start the clock over again.

**Comment by smsgoldberg** [comment]
I tried declaring timerId outside of the function and calling it with in initializeGame but it doesn't seem to have any effect so far. Is there something I'm missing logically or syntactically? 

```js
/*-----state variables ----*/
let board = [];
let player;
let win = null;
let count = 60;
let gameOver = false;
let firstClickChoice;
let secondClickChoice;
let firstClickChoiceIdx;
let secondClickChoiceIdx;
let match;
let timerId;
//holds our matched pairs when we find a match
let matchedPairsArray = [];
```
```js
function initializeGame() {
 win = null;
 match = null;
 shuffledTiles = shuffleTiles(mergedDogArray)
 console.log(shuffledTiles);
 //populate the game board
  populateBoard();
  //start the clock
  clearInterval(timerId);
  renderClock(() => {
    checkWinner();
  }
  );
}
```
```js
 //timer function that expires after 60 seconds 
 function renderClock(cbFunc) {
  count = 60;
  messageEl.style.visibility = 'visible';
  messageEl.innerText = count; 
  timerId = setInterval(() => {
   count--
   if (count && gameOver===false) {
    messageEl.innerText = count;
   } else {
    clearInterval(timerId);
    cbFunc();
   }
  }, 600)

 }
```

**Comment by smsgoldberg** [comment]
Interestingly enough, the combination of setting gameOver to false within initializeGame and calling clearInterval actually does restart the clock if what I tried just now is any indication,  but with the unhappy effect that the count starts decrementing by 2 seconds instead of one. It also counts down into the negative numbers.

**Comment by timmshinbone** [comment]
That means your timer is running twice when the game starts, so I think we should dig into why that's happening. If you're not able to find out why, let's take a look after lunch.

**Comment by smsgoldberg** [comment]
So in the end, the fix simply involved removing a second invocation of renderClock() from the event listener for playAgainButton. The renderClock() function is still called in initializeGame() so the timer will reset it self at the appropriate interval when playAgainButton is clicked.
