### ISSUE TITLE
Game project issue/Cards won't flip

### ISSUE THREAD

**Issue by Kateattardo** [sei-ec-remote/project-1-issues#180]
### What's the problem you're trying to solve?
Cards won't flip to start and move through game.

### Post any code you think might be relevant (one fenced block per file)
```
.cards {
      display: flex;
      flex-wrap: wrap;
      width: 519px;
      height: 50%;
      margin: auto;
      justify-content: center;
      font-size: 48px;
      cursor: pointer;
      background: lightgoldenrodyellow;
  }
  .dogcard {
    padding: 2px 2px;
    position: relative;
    }

  .front, .back {
    backface-visibility: visible;
    transform-style: preserve-3d;
  }

  .front{
    transform: rotateY(0deg);
  }

  .back{
    background-color: #f0f0f0;
    transform: rotateY(180deg);
    transform-origin: center center;
  }


```
 // Flip a card
    function flipCard(card) {
        if (boardLocked || card.classList.contains("flipped")) {
            return;
        }
        card.classList.add("flipped");
        flippedCards.push(card);

        if (flippedCards.length === 2) {
            lockBoard();
            if (checkMatching()) {
                handleMatch();
            } else {
                setTimeout(() => {
                    resetFlippedCards();
                    unlockBoard();
                }, 1000);
            }
        }
    }
    console.log(flipCard)
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at HTMLDocument.<anonymous> (main.js:88:12)

### What is your best guess as to the source of the problem?
Honestly lost on this one

### What things have you already tried to solve the problem?
Implementing the lock board function
and changing the card styling in CSS

### Paste a link to your repository here
https://github.com/Kateattardo/Concentration-A-simple-game.git

**Comment by timmshinbone** [comment]
```
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
at HTMLDocument. (main.js:88:12)
```
Can you show what you're trying to add the listener to on line 88?

**Comment by Kateattardo** [comment]
cards.forEach(function (card) {

**Comment by Kateattardo** [comment]
```js
cards.forEach(function (card) {
        card.addEventListener("click", function () {
            if (!card.classList.contains("flipped") && flippedCards.length < 2) {
                flipCard(card);
            }
        });
    });
    ```

**Comment by timmshinbone** [comment]
Ok, so, what the error and that code tells me is that it doesn't know what `cards` is. Is that an array that's in the global scope? And are those cards associated with DOM elements? Remember that we can only add listeners to things that live on the DOM. Is that loop happening before the cards are attached to the board? Let's see more of the javascript you've written that's associated with the cards.

**Comment by Kateattardo** [comment]
gotcha okay here is my start/ flip card:
```
function startGame() {
        if (gameStarted) {
            return;
        }
        gameStarted = true;
    // Flip a card
    function flipCard(card) {
        if (boardLocked || card.classList.contains("flipped")) {
            return;
        }
        card.classList.add("flipped");
        flippedCards.push(card);

        if (flippedCards.length === 2) {
            lockBoard();
            if (checkMatching()) {
                handleMatch();
            } else {
                setTimeout(() => {
                    resetFlippedCards();
                    unlockBoard();
                }, 1000);
            }
        }
    }
    console.log(flipCard)

**Comment by Kateattardo** [comment]
and my const:
```
document.addEventListener("DOMContentLoaded", function () {
    const cards = document.querySelectorAll(".dogcard");
    const timer = document.getElementById("timer");
    const button = document.querySelector("play-again-button");
    const wrongMessage = document.getElementById("wrong-message");

**Comment by Kateattardo** [comment]
card is the parent of dogCard

**Comment by timmshinbone** [comment]
Ok, that's what's going on here. I think you need to move your `cards` code outside of that event listener and into the global scope. What led to the decision to add a `DOMContentLoaded` event listener?

**Comment by Kateattardo** [comment]
Okay great I will try that now.  Thank you!  At the time I was in a rabbit hole and the research said it that it was best to used practice.... sooooo made sense at the time I guess

**Comment by timmshinbone** [comment]
Ok, let me know how it works out!

**Comment by Kateattardo** [comment]
for sure!
