### ISSUE TITLE
Accidental Matches

### ISSUE THREAD

**Issue by smsgoldberg** [sei-ec-remote/project-1-issues#181]
### What's the problem you're trying to solve?
This game is well on its way to functionality, but I have noticed a particularly obnoxious error. While the match function generally works well, clicking on both the circle itself and the surrounding square will produce a match _with itself_  that is then pushed to the array designated to hold the matched pairs. In other words, you could cheat your way to victory simply by clicking on both the dog picture and its surrounding container in swift succession. I'd like to make this impossible. 

### Post any code you think might be relevant (one fenced block per file)

```js
function evaluatePairs(firstChoiceIdx, secondChoiceIdx, match) {
  console.log('this is evaluate pairs', evaluatePairs);
  console.log('this is firstChoiceIdx', firstChoiceIdx);
  console.log('this is secondChoiceIdx', secondChoiceIdx);
  console.log('this is match', match);
  if (match === true && matchedPairsArray.length <=16) {
    matchedPairsArray.push(firstChoiceIdx);
    matchedPairsArray.push(secondChoiceIdx);
  } else {
    setTimeout(() => {
    showToken(firstChoiceIdx);
    showToken(secondChoiceIdx);
    hideDog(firstChoiceIdx);
    hideDog(secondChoiceIdx);
  }, 1000);
  }
  console.log('this is matched pairs array', matchedPairsArray)
```

```
function populateBoard() {
 //we should probably use forEach to populate the board elements 
  tiles.forEach((circle, circleIdx) => {
    console.log('this is circle', circle);
    console.log('this is circleIdx', circleIdx);
     tiles[circleIdx].style.backgroundImage = shuffledTiles[circleIdx].backgroundImage; 
     tiles[circleIdx].querySelector('img').setAttribute('src', shuffledTiles[circleIdx].backgroundImage);
    hideDog(circleIdx);
    showToken(circleIdx);
  });
    playAgainButton.visibility = 'hidden';
 }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm not seeing an error message, just the duplication of the tile in the array 

### What things have you already tried to solve the problem?
I've tried commenting various lines of code on and off, but have yet to find an effective solution. 

### Paste a link to your repository here
https://github.com/smsgoldberg/StayGolden

**Comment by smsgoldberg** [comment]
I'm realizing this is also a potentially relevant source of code:

```js

 //compare the user's choices
 function compareChoices(firstChoice, secondChoice) {
  if (firstChoice.src === secondChoice.src) {
    console.log('Match');
    match = true;
  } else {
    console.log('Not a match');
    match = false;
  }
   return match;
}
```

**Comment by asands94** [comment]
Are you able to disable clicking on a square that has a visible image showing?

**Comment by smsgoldberg** [comment]
I think I got it! Per your suggestion I tried adding additional conditions to my if block: 

```js

 function compareChoices(firstChoice, secondChoice) {
  if (firstChoice.src === secondChoice.src && firstClickChoiceIdx != secondClickChoiceIdx) {
    console.log('Match');
    match = true;
  } else {
    console.log('Not a match');
    match = false;
  }
   return match;
}
```

This seems to have cleared it up

**Comment by asands94** [comment]
Yay! This is really coming together and I can't wait to see your final version tomorrow!

**Comment by smsgoldberg** [comment]
Thank you! I won't call it beautiful but it's definitely playable (if a little harder than I expected -- 60 seconds goes by fast).
