### ISSUE TITLE
VS Code Debugging

### ISSUE THREAD

**Issue by dn412** [sei-ec-remote/project-1-issues#183]
### What's the problem you're trying to solve?
Endless issues with VS Code that's not translating when I go Live

### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?
Maybe installation problem from the very beginning

### What things have you already tried to solve the problem?
Install a different live server, change my codes around, etc

**Comment by asands94** [comment]
Hey Dani, can we get some more details on the issue? What is the expected behavior versus what is actually happening?

**Comment by dn412** [comment]
> Hey Dani, can we get some more details on the issue? What is the expected behavior versus what is actually happening?

Whenever I go Live, nothing shows from what i've been coding. Both Go Lives are different from each other

**Comment by asands94** [comment]
Does anything show or is it a white screen? if it's a white screen, make sure you have your css and js files referenced in your index.html file

**Comment by dn412** [comment]
On one go live it shows only some of the html and css and the other shows it completely differently. It doesn't even allow the game to be played. I have to open the Go live using a different format. If that makes sense

**Comment by asands94** [comment]
Lets jump into room 15

**Comment by asands94** [comment]
Nevermind, I see you're with Timm!
