### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by timmshinbone** [sei-ec-remote/project-1-issues#186]
### What's the problem you're trying to solve?
trying to see if I need to do github admin stuff

### Post any code you think might be relevant (one fenced block per file)
```js
console.log('hello')
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no errors

### What is your best guess as to the source of the problem?
something happendd

### What things have you already tried to solve the problem?
nothing

### Paste a link to your repository here
link link link

**Comment by nayaba** [comment]
This is my colorful comment.
