### ISSUE TITLE
Having a hard time referring to my array properly to change its values with an event listener

### ISSUE THREAD

**Issue by JohnArochaDev** [sei-ec-remote/project-1-issues#188]
### What's the problem you're trying to solve?

Im trying to change the value in my array based off the ID with event.target to change its value in the array, which will then update its color with my render function
### Post any code you think might be relevant (one fenced block per file)
```js
function initiate() {
    board.forEach((box) => {
        box.addEventListener('click', (e)=>{play(e); console.log(e.target.id)});
    })
    turn = 1
    winner = null
    chart = [
        [0, 0, 0, 0, 0, 0, 0, 0], // col 0
        [0, 0, 0, 1, 1, 1, 1, 0], // col 1
        [0, 0, 0, 0, 0, 0, 0, 0], // col 2
        [0, 0, 0, 0, 0, 0, 0, 0], // col 3
        [0, 0, 0, 0, 0, 0, 0, 0], // col 4
        [0, 0, 0, 0, 0, 0, 0, 0], // col 5
        [0, 0, 0, 0, 0, 0, 0, 0], // col 6
        [0, 0, 0, 0, 0, 0, 0, 0], // col 7
        [0, 0, 0, 0, 0, 0, 0, 0], // col 8
    ]
    render()
}

function renderBoard() {
    chart.forEach((colArr, colIdx) => {
        // console.log('colArr', colArr)
        // console.log('colIdx', colIdx)
        colArr.forEach((cellVal, rowIdx) => {
            // console.log('cellVal', cellVal)
            // console.log('rowIdx', rowIdx)
            const cellId = `v${colIdx}h${rowIdx}`
            // console.log('cellId', cellId)
            const cellEl = document.getElementById(cellId)
            // console.log('cellEl', cellEl)
            cellEl.style.backgroundColor = colors[cellVal]
        })
    })
}

function render() {
    renderBoard()
}
// Learn from this and make a function that changes the number in the array based off the idx
function play(e) {
    e.target.id
    // console.log('this is the current board', board)
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
script.js:101 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at script.js:101:20
    at Array.forEach (<anonymous>)
    at script.js:94:16
    at Array.forEach (<anonymous>)
    at renderBoard (script.js:91:11)
    at render (script.js:107:5)
    at initiate (script.js:87:5)
    at script.js:116:1
```
### What is your best guess as to the source of the problem?

Im not having any issues per-say(even though I have errors its still working lol)

### What things have you already tried to solve the problem?

Several different ways of accessing my array with its specific refrence

### Paste a link to your repository here
https://github.com/jpjpjppj/Battleship

**Comment by nayaba** [comment]
What values do you get when you console.log `cellEl`  and `cellId`?

**Comment by JohnArochaDev** [comment]
when I console log cellVal I get the item I want to change, but its only a variable in that one function. So far Im re-creating it soI have access to it, but im still not understanding why Im getting errors

**Comment by nayaba** [comment]
Can you elaborate more on exactly what you're trying to accomplish and exactly what action results in an error?  Also if you're getting multiple errors, please post them as well.

**Comment by JohnArochaDev** [comment]
So i think I fixed my question about referring to certian information, but what I still need help with are these errors. Ill post it below 

```script.js:131 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at script.js:131:20
    at Array.forEach (<anonymous>)
    at script.js:124:16
    at Array.forEach (<anonymous>)
    at renderBoard (script.js:121:11)
    at render (script.js:137:5)
    at initiate (script.js:117:5)
    at script.js:182:1
```

**Comment by nayaba** [comment]
It looks like the top of the error message is cut off - could you re-post the full message?

**Comment by JohnArochaDev** [comment]
```
script.js:131 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at script.js:131:20
    at Array.forEach (<anonymous>)
    at script.js:124:16
    at Array.forEach (<anonymous>)
    at renderBoard (script.js:121:11)
    at render (script.js:137:5)
    at initiate (script.js:117:5)
    at script.js:184:1
```

**Comment by JohnArochaDev** [comment]
Sorry about that I didn't realize :[

**Comment by nayaba** [comment]
So when I console.log `cellId` I see that the final one is v8h0, which doesn't exist in your html

**Comment by JohnArochaDev** [comment]
Lol that fixed basically everything, I miscounted how many arrays I had haha, I only have one more error left. Its this one
```
script.js:191 Uncaught TypeError: board.addEventListener is not a function
    at script.js:191:7
```

**Comment by nayaba** [comment]
So I see that you used `querySelectorAll` to grab the board.  That is going to return a node list.  `addEventListener` is a method that can only be attached to a single HTML element, not an entire list/array of elements.

**Comment by JohnArochaDev** [comment]
Then What should I do? It needs to be all of the boxes that are selected in board

**Comment by nayaba** [comment]
Remember in the [Connect 4 Code-along](https://github.com/sei-ec-remote/connect4-applepies/blob/main/js/main.js) we used the spread operator `...` to create an array out of a node list:
```js
const markerEls = [...document.querySelectorAll('#markers > div')]
console.log('markerEls \n', markerEls)
```
And then we used a `forEach` method to loop over our array?

```js
function renderControls() {
    playAgainButton.style.visibility = winner ? 'visible' : 'hidden'
    markerEls.forEach((markerEl, colIdx) => {
        const hideMarker = !board[colIdx].includes(0) || winner
        markerEl.style.visibility = hideMarker ? 'hidden' : 'visible'
    })
}
```

**Comment by JohnArochaDev** [comment]
Thank you!
