### ISSUE TITLE
Grid set in CSS not appearing

### ISSUE THREAD

**Issue by Clund1** [sei-ec-remote/project-1-issues#189]
### What's the problem you're trying to solve?
My grid is appearing as a line on the page, when I look at the element highlight it shows the element that 'contains' the grid but the actual 35x35vmin squares are not.

### Post any code you think might be relevant (one fenced block per file)
```HTML
main{
    display: grid;
    grid-template-columns: 30vmin, 30vmin, 30vmin, 30vmin, 30vmin;
    grid-template-rows: 30vmin, 30vmin, 30vmin, 30vmin, 30vmin;
}

main * {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
<img width="555" alt="Screenshot 2023-11-29 at 2 07 09 PM" src="https://github.com/sei-ec-remote/project-1-issues/assets/149333009/bb237a0c-4e62-4aca-b443-66a77f1a1be0">

### What is your best guess as to the source of the problem?
CSS styling

### What things have you already tried to solve the problem?
adjusting size values,  changing from flex to block, adjusting HTML to make sure everything is seperated

### Paste a link to your repository here
[ (https://github.com/Clund1/Project-1---GAME)]

**Comment by JohnArochaDev** [comment]
This is John in room 4, I may be able to help with that I've got my grid working. If you want to come over we can chat :]
