### ISSUE TITLE
CSS layout issue 

### ISSUE THREAD

**Issue by stephanieonyekaba** [sei-ec-remote/project-1-issues#19]
### What's the problem you're trying to solve?

I am trying to align the contents of my page in a block square where the text "Which color doesn't match" is on top of the 4 circles (arranged in a 2x2 format)

### Post any code you think might be relevant (one fenced block per file)
```
//CSS 
''this is the container that holds the circle and text divs
#smallcontainer {
    display: flex;
    align-items:center;
    justify-content: center;
    background-color: rgb(245, 245, 245);
    width: 850px;
    height: 500px;
    border-radius: 75px;
    flex-direction: row;
    align-content: space-around;
    font-size: 50px; 
}

``the circles that were created with a js for loop
.circle {
    display: inline-block;
    background-color: rgb(18, 142, 230);
    height: 200px;
    width: 200px;
    border-radius: 50%;
}

``the text I am trying to align above the circles 
#guessTheCircleHeading {
    display: flex;
    flex-direction: column;
    text-align: center;
}



```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error, but the text and circles are all aligned horizontally in a straight line.

### What is your best guess as to the source of the problem?
The flex display properties of the container and of the items being arranged 

### What things have you already tried to solve the problem?
I have tried changing the display properties of the container that houses the individual elements and the elements themselves 

### Paste a link to your repository here
https://github.com/stephanieonyekaba/Game-Project-/find/main

**Comment by cory-yonomi** [comment]
If the #guessTheCircleHeading is just holding text, it doesn't need to be turned into a flexbox, just the element holding that text and your circles.

Your #smallContainer has a flex-direction of 'row', which is why everything's laying out horizontally.
