### ISSUE TITLE
trying to move the peices

### ISSUE THREAD

**Issue by ItsAlbi007** [sei-ec-remote/project-1-issues#197]
### What's the problem you're trying to solve?
i want to move the checker pieces but i dont know how to put them into places where they belong

### Post any code you think might be relevant (one fenced block per file)
```// document.addEventListener('squares', function () {
//   let blueChecker = document.querySelectorAll('.blueChecker')
//   let redChecker = document.querySelectorAll('.redChecker')

//   blueChecker.forEach(blueChecker => {
//     blueChecker.setAttribute('draggable', true);
// });

//   redChecker.forEach(redChecker => {
//     redChecker.setAttribute('draggable', true);
// });

```

### What is your best guess as to the source of the problem?
i need to make them draggable which i wrote the code but when i go to see if they have that on the inspect they dont have it 

### What things have you already tried to solve the problem?
i dont know bunch of stuff that i have no idea what their purpose is

### Paste a link to your repository here
https://github.com/ItsAlbi007/G-Project

**Comment by timmshinbone** [comment]
I think making these draggable is probably not the right move for version 1, use a system of grid coordinates for placement, similar to the way we handled connect4. 'user selects a checker piece, then a space to move it to, if the checker piece is able to move there, move it there'

**Comment by ItsAlbi007** [comment]
```html
<div class="black box" id="c0r0"></div>
```
i was naming the classes wrong i put 2 classes inside a div
