### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by irishjack490** [sei-ec-remote/project-1-issues#198]
### What's the problem you're trying to solve?
Trying to make my div (with class=box) a button, so that player can click and see whether he has a mine or a number. I have tried adding the <type =button> but it created more squares and messed the whole form up

### Post any code you think might be relevant (one fenced block per file)
```
        </section>
        <section id="board">
          <!--Row4-->
          <div id="c0r4" class="box"></div>
          <div id="c1r4" class="box"></div>
          <div id="c2r4" class="box"></div>
          <div id="c3r4" class="box"></div>
          <div id="c4r4" class="box"></div>
          
          <!--Row3-->
           <div id="c0r3" class="box"></div>
           <div id="c1r3" class="box"></div>
           <div id="c2r3" class="box"></div>
           <div id="c3r3" class="box"></div>
           <div id="c4r3" class="box"></div>
           <!--Row2-->
           <div id="c0r2" class="box"></div>
           <div id="c1r2" class="box"></div>
           <div id="c2r2" class="box"></div>
           <div id="c3r2" class="box"></div>
           <div id="c4r2" class="box"></div>
           <!--Row1-->
          
           <div id="c0r1" class="box"></div>
           <div id="c1r1" class="box"></div>
           <div id="c2r1" class="box"></div>
           <div id="c3r1" class="box"></div>
           <div id="c4r1" class="box"></div>
           <!--Row0-->
           <div id="c0r0" class="box"></div>
           <div id="c1r0" class="box"></div>
           <div id="c2r0" class="box"></div>
           <div id="c3r0" class="box"></div>
           <div id="c4r0" class="box"></div>
          
          
        </section>

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
On developer tools at the bottom I see an issue that says: Page layout maybe unexpected due to quirks mode. 
Not 100% sure if that is related to this

### What is your best guess as to the source of the problem?
 My thinking is perhaps giving another class to div

### What things have you already tried to solve the problem?

adding <type =button> after each div line, but it creates more boxes I don't need

### Paste a link to your repository here

https://github.com/irishjack490/Project-1---Browser-Based-Game

**Comment by timmshinbone** [comment]
Instead of changing their type to a button, you should select them based on their class and add a click event listener to them.
