### ISSUE TITLE
Issue capturing a generated element and making it an array

### ISSUE THREAD

**Issue by da1dude** [sei-ec-remote/project-1-issues#200]
### What's the problem you're trying to solve?

I generated a <span> and added inner text to render dash's on the screen equal to the word length

I now want to capture that element but cannot. I have tried getElementByID and QuerySelectorAll

### Post any code you think might be relevant (one fenced block per file)
```
function renderHiddenWord() {
    for (let i = 0; i < hiddenWord.length; i++) {
        //for each letter in hiddenWord create a span to hold
        //the hiddenWord spaces in the hword element
		let letterSpace = document.createElement("span");
		letterSpace.innerText = '_____ ';
        letterSpace.setAttribute("id", "spaces");
        hword.appendChild(letterSpace);
	}
}
<img width="284" alt="Screenshot 2023-11-30 at 12 37 58 PM" src="https://github.com/sei-ec-remote/project-1-issues/assets/43474094/f8f07aa6-ec55-4c09-ae53-120f8a99d206">

```

### What is your best guess as to the source of the problem?
Not really sure. 

### Paste a link to your repository here
https://github.com/da1dude/spaceman/tree/main

**Comment by timmshinbone** [comment]
ok, share your html so I can see what you're trying to append this to

**Comment by da1dude** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/main.css">
    <script defer src="js/main.js"></script>
    <title>Spaceman</title>
</head>
<body>

    <main class="flx-ctr">
        <h1>SPACEMAN</h1>
        <h2 id="status">STATUS</h2>
        
        <div>
            <form>  
                <input type="text" id="guess" required minlength="1" maxlength="1" onkeydown="return /[a-zA-Z]/i.test(event.key)"/>
                <button id="submit">Submit</button>
            </form>
        </div> 
        <div id="gboard">
                <img id="ship7">
                <img id="ship6">
                <img id="ship5">
                <img id="ship4">
                <img id="ship3">
                <img id="ship2">
                <img id="ship1">
        </div>
        <h2 id="hword"></h2>
        <h2 id="guesses">guesses</h2>
        <button id="reset">RESET</button>
    </main>
</body>
</html>

**Comment by timmshinbone** [comment]
Ok, I'm not sure why it's not working to get that element, try console logging the variable where you're trying to capture it. I think the variable is hword. Console log that and share the results here

**Comment by da1dude** [comment]
main.js:74 this is hword <h2 id=​"hword">​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​</h2>​
main.js:74 this is hword <h2 id=​"hword">​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​</h2>​
main.js:74 this is hword <h2 id=​"hword">​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​</h2>​
main.js:74 this is hword <h2 id=​"hword">​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​</h2>​
main.js:74 this is hword <h2 id=​"hword">​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​<span id=​"spaces">​_​</span>​</h2>​

**Comment by timmshinbone** [comment]
so, what's that console log telling you?

**Comment by da1dude** [comment]
It appears to repeating the span also. Im not sure why.

**Comment by timmshinbone** [comment]
That means the span is actually getting attached to the div, now, let's analyze the code. Why do you think the span is being added multiple times?

**Comment by da1dude** [comment]
Im guessing that has to do with the for loop iterating over the letters in hiddenWord. 
Im thinking there is probably a better way to do this but I cant comeup with it. Im experiencing a similar problem later in the code while iterating over the hidden word and trying to match it to the userGuess.

**Comment by timmshinbone** [comment]
ok cool, next step, slack me and we'll do a 1:1

**Comment by timmshinbone** [comment]
Worked out a direction towards finding a solution in a 1:1
