### ISSUE TITLE
grid container background image isn't displaying

### ISSUE THREAD

**Issue by ariellepollock** [sei-ec-remote/project-1-issues#201]
### What's the problem you're trying to solve?
I'm trying to get a background image set as the background for a grid container.

### Post any code you think might be relevant (one fenced block per file)
```
.viewport {
    grid-area: backdrop;
    margin: 10px 10px 0 10px;
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    grid-template-rows: repeat(4, 1fr);
    grid-template-areas: 
        "item1 . . . item4"
        ". . item2 . ."
        ". . . . item3"
        ". . item5 . .";
    background-image: url(assets/elle.ollo.png);
    background-size: cover;
    position: relative;
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No behavior, image isn't visible.

### What is your best guess as to the source of the problem?
My defined grid areas are interfering?

### What things have you already tried to solve the problem?
I tried using a separate element and use z-index to align. I saw that the colored background will work so I checked my src path. I tried using the image separately with an id.

### Paste a link to your repository here
https://github.com/ariellepollock/project-1-game/blob/main/css/main.css

**Comment by timmshinbone** [comment]
is the image showing up in the elements in the inspector tools?

**Comment by ariellepollock** [comment]
I can see the named container in the elements in the inspector tools but not the image

**Comment by ariellepollock** [comment]
I think I found a different route. I will try that and see if I can solve it. Should I close this and reopen if I still can't achieve what I want?

**Comment by timmshinbone** [comment]
yeah! That sounds good!

**Comment by ariellepollock** [comment]
I think I did it!! I'm just having an issue with sizing but I think I can figure it out :) Will come back and holler if I can't get it right

**Comment by ariellepollock** [comment]
NAILED IT!! Thanks for the moral support
