### ISSUE TITLE
Determine how to get randomized colors matched to squareIdx

### ISSUE THREAD

**Issue by bmaiden** [sei-ec-remote/project-1-issues#203]
### What's the problem you're trying to solve?
Determine how to get randomized colors matched to squareIdx

### Post any code you think might be relevant (one fenced block per file)
```JS
//function -squarePicked- main gameplay function, determines squares selected with a event listener
function squarePicked(event) {
    //get index of square when clicked on
    const squareIdx = parseInt(event.target.id.replace(`sq-`, ''))
    //console.log('squareIdx', squareIdx)     //inspect displays squareIdx
    //get colors for squares
    

    //render updated state
    render()
};
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Question on how to proceed.

### What is your best guess as to the source of the problem?
Question on how to proceed.

### What things have you already tried to solve the problem?
Trying to determine if nested function should be placed or separate function to randomize the colors.

### Paste a link to your repository here
https://github.com/bmaiden/memory-browser-game

**Comment by nayaba** [comment]
I think you're very close here - when you console.log `squareVal` it appears to be null because it's getting it's value from the board array.  If you replace your null values in your board array with numbers, what happens?

**Comment by bmaiden** [comment]
I get colors. So should I write up a separate function outside of the squarePicked function to randomize the colors?

**Comment by nayaba** [comment]
I think you should try that out and see where it takes you, yes 😄

**Comment by bmaiden** [comment]
Thank you. I will write up a separate function to randomize the colors within the 16 squares.
