### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by ItsAlbi007** [sei-ec-remote/project-1-issues#204]
### What's the problem you're trying to solve?
i have to class es in a div and it wont recognize the second class

### Post any code you think might be relevant (one fenced block per file)
```
  <div class="black" class="box" id="c0r0"></div>
      <div class="white" class="box" id="c0r1">
        <div class="blue checker" id="blue-checker-1"></div>
      </div>
```

### What is your best guess as to the source of the problem?

i was thinking of making a div inside of a div but that will ruin almost everything and it will be very very long to write
### What things have you already tried to solve the problem?
i tried to div in a div but then all my boxes started scattering around so is there a simpler way to has my box class work

**Comment by timmshinbone** [comment]
share the css of the class and a screenshot of the browser so I can see the elements

**Comment by ItsAlbi007** [comment]
i dont have it on css idk how to explain to be honest but its okay ill figure it out with tylus later tonight

**Comment by timmshinbone** [comment]
Let's look in a breakout room, I'll slack ya

**Comment by timmshinbone** [comment]
resolved by changing the way class attribute was added in html
