### ISSUE TITLE
Very weird error

### ISSUE THREAD

**Issue by JohnArochaDev** [sei-ec-remote/project-1-issues#209]
### What's the problem you're trying to solve?

Ive got an error that I dont understand
### Post any code you think might be relevant (one fenced block per file)

I have a lot of code, it could be one of many places

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

```
script.js:248 Uncaught RangeError: Maximum call stack size exceeded
    at cTurn (script.js:248:15)
    at retry (script.js:327:9)
    at cTurn (script.js:254:16)
    at retry (script.js:327:9)
    at cTurn (script.js:254:16)
    at retry (script.js:327:9)
    at cTurn (script.js:254:16)
    at retry (script.js:327:9)
    at cTurn (script.js:254:16)
    at retry (script.js:327:9)
```
### What is your best guess as to the source of the problem?

Truly have no clue

### What things have you already tried to solve the problem?

No clue

### Paste a link to your repository here
https://github.com/jpjpjppj/Battleship

**Comment by timmshinbone** [comment]
That means your code is doing too much at once, more than likely you have an infinite loop or something happening, so, find out where that's coming from and change the code to make that infinite loop go away

**Comment by timmshinbone** [comment]
Slack me if you can't find the solution in 10 minutes and I'll come save your computer from exploding

**Comment by JohnArochaDev** [comment]
Oh okay perfect I know what it is then, thanks!
