### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by clds84** [sei-ec-remote/project-1-issues#21]
### What's the problem you're trying to solve?

I'm having and with my canvas sizing that I think might be affecting the interaction of the game. I created some squares for teleporting, and a section of the right side of the canvas doesn't allow the player to stay rendered once I teleport there. At the same time, If I play with my browser window the canvas has more width to the right and I can manage to teleport further back there. If I bring my browser window in, things get really weird and faulty. 

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

N/a
### What is your best guess as to the source of the problem?

Perhaps this has something to do with canvas sizing, but I'm not sure.

### What things have you already tried to solve the problem?
I've played around with the teleport square and I can manage to teleport behind an area that is causing rendering issues. Even
if I move my player to that area without teleporting, it fails to render. I have a series of walls attacking the player, and I 
commented them out thinking maybe there's an issue that they're still there and the detectHit is happening. The main thing
I can reason as being some kind of clue of things being wonky is the canvas game resizing re: the browser window size. I'd 
like some help to deal with that and I'd like to  share my screen to show you exactly what I mean.

### Paste a link to your repository here
https://github.com/clds84/Game-Project-1

**Comment by timmshinbone** [comment]
I need to see code for your canvas sizing and your teleport functions, share it here in a js code block

**Comment by clds84** [comment]
I tried commenting out what we used with canvas crawler and tried something else and that works but the ones commented out only allow me to see about 200 pixels tall. 

This is what I have in CSS for canvas. I've just been working on JS:
```
canvas {
    border: 2px solid rgba(30, 145, 118, 0.599);
    width: 100%;
    height: 100;
}
```

This is the canvas portion in JS:
```
let canvas = document.querySelector('canvas')
//canvas.setAttribute('width', getComputedStyle(canvas)['width'])
//canvas.setAttribute('height', getComputedStyle(canvas)['height'])
canvas.width = window.innerWidth
canvas.height = window.innerHeight
const ctx = canvas.getContext('2d')

```

This is for my teleport function:
```
function Teleport(x,y,width,height,){
    this. x = x
    this.y = y
    this.width = width
    this.height = height
    this.render = function(){
        ctx.fillstyle = 'rgba(145, 30, 40, 0.599)'
        ctx.fillRect(this.x,this.y,this.width,this.height)
    }
}
let teleportBottom = new Teleport(550,900,30,30)
let teleportTop = new Teleport(550,10,30,30)
let teleportLeft = new Teleport(10,450,30,30)
let teleportRight = new Teleport(1120,450,30,30)

```

For detecting teleportation, I haven't figured out a way to go dry yet, but I have this:

```
const detectTeleportation = () => {
    if(player.x < teleportBottom.x + teleportBottom.width
        && player.x + player.width > teleportBottom.x
        && player.y < teleportBottom.y + teleportBottom.height
        && player.y + player.height > teleportBottom.y){
            
            player.alive = false
            player = new Player(1050,400,40,40)
            console.log(player.alive)
        
        } else if(player.x < teleportTop.x + teleportTop.width
        && player.x + player.width > teleportTop.x
        && player.y < teleportTop.y + teleportTop.height
        && player.y + player.height > teleportTop.y){
            
            player.alive = false
            player = new Player(50,450,40,40)
            console.log(player.alive)
        
        } else if(player.x < teleportLeft.x + teleportLeft.width
        && player.x + player.width > teleportLeft.x
        && player.y < teleportLeft.y + teleportLeft.height
        && player.y + player.height > teleportLeft.y){
            
            player.alive = false
            player = new Player(550,50,40,40)
            console.log(player.alive)
        
        } 
        else if(player.x < teleportRight.x + teleportRight.width
        && player.x + player.width > teleportRight.x
        && player.y < teleportRight.y + teleportRight.height
        && player.y + player.height > teleportRight.y){
            
            player.alive = false
            player = new Player(1170,450,40,40)
            console.log(player.alive)
        }

```
I want to include some photos to show what I mean:

This is when I have the browser fairly big. My intention is to have the four teleport squares close to the edge of the canvas but by making the browser very wide on my screen the right teleport squares far from it:

![Screen Shot 2022-02-23 at 3 09 04 PM](https://user-images.githubusercontent.com/99062632/155400410-5f571095-e9ed-407a-8bfd-af31036da93f.png)

This is when I make the browser smaller. The walls that have yet to render render and then stop moving and kind of get stuck over there. Things get weird in the middle too and you can see how that thick wall is stuck there because it's darker since I guess the rendering is happening in the same place?
![Screen Shot 2022-02-23 at 3 09 56 PM](https://user-images.githubusercontent.com/99062632/155400471-38354b77-da9d-4961-a34b-8e446754194b.png)

In this last one, I removed the wall renders to show how when making the browser smaller, I also get a clearRect issue. None of these things happen if the browser is bigger, only the issue that the right side of the canvas, around where the square on the right is, is causing rendering issues for the player, the larger square, either when I move in that space, or teleport to it. That area is roughly at say 900X and all through the y-axis.  

![Screen Shot 2022-02-23 at 3 10 58 PM](https://user-images.githubusercontent.com/99062632/155400639-63913f3e-487c-460c-b895-9b3bd5abd1d5.png)

I was thinking maybe this is has something to do with creating walls, where the height is set to innerHeight. I'll wait to hear from you, but I can try setting those to coordinates instead:

```
let wallOneTop = new Wall(1020,0,50,425,5)
let wallOneBottom = new Wall(1020,500,50,innerHeight,5)
let wallTwoTop = new Wall(1020,0,50,150,2)
let wallTwoBottom = new Wall(1020,250,50,innerHeight,2)
let wallThreeTop = new Wall(1020,0,110,200,2)
let wallThreeMiddle = new Wall(1020,275,110,500,2)
let wallThreeBottom = new Wall(1020,850,110,innerHeight,2)
let destroyWall = new Wall(1020,0,50,1000,2)
```

**Comment by timmshinbone** [comment]
Already I can tell that this code:
```css
canvas {
    border: 2px solid rgba(30, 145, 118, 0.599);
    width: 100%;
    height: 100;
}
```
is jacking up the sizing. You're _stretching_ the canvas to the width and height of the parent container. You'd be better off utilizing a hard coded amount of pixels for your canvas height and width and declaring those inline with your css, something like:
```html
<canvas id="game" height="300px" width="600px"></canvas>
```

Or some other values that work for you. DO NOT WORRY ABOUT MAKING THIS RESPONSIVE. No need for P1, I just wanna see it working.

**Comment by clds84** [comment]
Okay, thanks. I'll try playing around with things some more.

**Comment by clds84** [comment]
Hi Timm,

I spoke with Cory about my issue with a spawning point. The canvas did do the trick from my issue before where things were really getting weird when playing with browser size, but I have a hit detection issue. I'm including a video for you to see what happens on the right side and some code as well that can help shed some light. The right side of the canvas is where my walls render. If I move into the space toward the edge of the canvas where they render, a hit is detected. Cory explained to me that even if they're not rendered, they're occupying that space when I set a variable to a new wall with coordinates. If I change my x coordinate for the walls when I set them to a variable, there is no hit detection, but the walls don't enter the canvas. Cory and I were trying to play around with the conditional statement in the wall function code block as well as the 
x coordinates for the walls, but when one thing works, the other doesn't.

https://user-images.githubusercontent.com/99062632/155589855-cbcd233a-850c-47d3-9014-1b5a4f6358f2.mov

This is my code establishing the wall properties:
```js
function Wall(x,y,width,height,dx) {
    this.x = x
    this.y = y
    this.width = width
    this.height = height
    this.dx = dx
    this.alive = true
    this.render = function (){
       ctx.fillStyle = 'rgba(30, 145, 118, 0.599)'
       ctx.fillRect(this.x,this.y,this.width,this.height,this.dx)
    }
   this.update = function () {
    //    console.log(this.x < 0)
    //    console.log(this.x + this.width)
    //    console.log(canvas.width)
       if (this.x < 0 || this.x + this.width > canvas.width){
           this.dx = -this.dx
       }
       this.x -= this.dx   
           this.render()  
   }
    
}   
```
This is my code for creating the walls and setting them to variables
```js
let wallOneTop = new Wall(949,0,50,425,5)
let wallOneBottom = new Wall(949,500,50,innerHeight,5)
let wallTwoTop = new Wall(949,0,50,150,2)
let wallTwoBottom = new Wall(949,250,50,innerHeight,2)
let wallThreeTop = new Wall(899,0,100,200,2)
let wallThreeMiddle = new Wall(899,275,100,500,2)
let wallThreeBottom = new Wall(899,850,100,innerHeight,2)
let destroyWall = new Wall(949,0,50,1000,2)```js
```
This is my code for hit detection:
```js
const detectHit = () => {    
    for (let i = 0; i < arrayForHit.length;i++){
        if(player.x < arrayForHit[i].x + arrayForHit[i].width
        && player.x + player.width > arrayForHit[i].x
        && player.y < arrayForHit[i].y + arrayForHit[i].height
        && player.y + player.height > arrayForHit[i].y){
            player.alive = false
           // console.log('hit detected', arrayForHit[i])
        }
    }
    
}
```

**Comment by clds84** [comment]
I just wanted to add after testing now that if I play the game until all three walls are moving within the canvas bouncing back and forth, the right side of the canvas doesn't cause a hit detection issue. And strangely enough, with all three walls in the canvas bouncing around, the 4th destroy wall doesn't cause a hit detection when it's yet to come out.
