### ISSUE TITLE
I need some guidance on where to go with this AI

### ISSUE THREAD

**Issue by JohnArochaDev** [sei-ec-remote/project-1-issues#211]
### What's the problem you're trying to solve?

Im running into issues left and right, Ive made HUGE progress but I really need a hand deciding where to go from here

### Post any code you think might be relevant (one fenced block per file)
I need some code help but really I just need advice on what to do

### Paste a link to your repository here
https://github.com/jpjpjppj/Battleship

**Comment by JohnArochaDev** [comment]
The AI program is way more complex than I initially thought, and I need to know if im so deep that I need to finish it (And maybe a guide on my gameplan to do it) Or know if I should leave it where it is and get to polishing.

**Comment by JohnArochaDev** [comment]
Thanks in advance!

**Comment by timmshinbone** [comment]
Ok, brainstorm session incoming.

**Comment by JohnArochaDev** [comment]
Thank you!
