### ISSUE TITLE
assigning randomized color choices to variable, squareColor

### ISSUE THREAD

**Issue by bmaiden** [sei-ec-remote/project-1-issues#218]
### What's the problem you're trying to solve?
Assigning randomized color choices to variable, squareColor

### Post any code you think might be relevant (one fenced block per file)
```JS
/*----- state variables -----*/
let squareColor;

// function -randomColors- randomize colors for squares
function randomColors() {
  for (let i = 0; i < squareEls.length; i++) {
    const randomIndex = Math.floor(Math.random() * colors.length);
    squareColor = colors[randomIndex];
    colors.splice(randomIndex, 1);
    // console.log(squareColor);                 //here gives all colors
    // return (squareColor[randomIndex]);        //here gives one color with console log outside function
    // return (squareColor[randomIndex], i);     //here gives one color with console log outside function
  }
}

randomColors();
console.log(squareColor);         //here gives one color for the return statement within the function
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
returning only one color versus an array of colors

### What is your best guess as to the source of the problem?
?

### What things have you already tried to solve the problem?
moving "squareColor = colors[randomIndex];" under splice statement.

### Paste a link to your repository here
https://github.com/bmaiden/memory-browser-game/commits/main

**Comment by Clund1** [comment]
What does your colors index look like?

**Comment by bmaiden** [comment]
const colors = [
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "pink",
  "darkgray",
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "pink",
  "darkgray",
];

**Comment by timmshinbone** [comment]
Where are you using the squareColor variable to apply the color?

**Comment by bmaiden** [comment]
Want to use it in the the squarePicked function.

**Comment by bmaiden** [comment]
Sorry when the square is picked.

**Comment by timmshinbone** [comment]
I should have stated more clearly, share the function where that's happening. Sorry about the miscommunication!

**Comment by bmaiden** [comment]
I want to use the squareColor within this function.
```
//function -squarePicked- determines squares selected with a event listener
function squarePicked(event) {
  //get index of square when clicked on
  const squareIdx = parseInt(event.target.id.replace(`sq-`, ""));
  // console.log('squareIdx:', squareIdx)     //console displays squareIdx
  //changed board array null to numbers and colors display on board.
  //change color of square when clicked on

  //render updated state
  render();
}
```

**Comment by bmaiden** [comment]
I am struggling here, been working on this aspect for 1 1/2 days now.

**Comment by bmaiden** [comment]
I am not sure how to proceed with the coding I have. Help.

**Comment by bmaiden** [comment]
Thank you, Nabila!! You went above and beyond, it's very much appreciated. Your approach on walking me through my coding challenge and explain in detail what changes were needed and why, makes me feel better prepared to finish this project. Thank you again!
