### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by johnzwiss** [sei-ec-remote/project-1-issues#22]
### What's the problem you're trying to solve?
Rendering random platforms and having them fall 

### Post any code you think might be relevant (one fenced block per file)
```
`let platformA ={
    x: 10,
    y: -20,
    height: 10,
    width: 70,
    yVelocity: 3, 
}    
let platformB ={
    x: 90,
    y: -120,
    height: 10,
    width: 70,
   yVelocity: 3, 
}    
let platformC ={
    x: 170,
    y: -220, 
    height: 10,
    width: 70,
    yVelocity: 3, 
}    
let platformD ={
    x: 250,
    y: 0,
    height: 10,
    width: 70,
    yVelocity: 3, 
}    
let platformE ={
    x: 330,
    y: -100,
    height: 10,
    width: 70,
    yVelocity: 3, 
}    
let platformF ={
    x: 410,
    y: -200,
    height: 10,
    width: 70,
    yVelocity: 3, 
}    
//left and right side platforms 
let platArrayA = [platformA, platformB, platformC]
let platArrayB = [platformD, platformE, platformF]

 //render canvas    
function rendercanvas(){
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, 500, 800);
}
// render player 
function renderplayer(){
    ctx.fillStyle = "green";
    ctx.fillRect(player.x, player.y, player.width, player.height);
    }
//creating random platforms 
function createPlatforms(){
    let i = Math.floor(Math.random() * 3)
    ctx.fillStyle = "brown";
    ctx.fillRect(platArrayA[0].x, platArrayA[0].y, platArrayA[0].width, platArrayA[0].height);
    ctx.fillRect(platArrayB[0].x, platArrayB[0].y, platArrayB[0].width, platArrayB[0].height);
    ctx.fillRect(platArrayA[2].x, platArrayA[2].y, platArrayA[2].width, platArrayA[2].height);
    ctx.fillRect(platArrayB[2].x, platArrayB[2].y, platArrayB[2].width, platArrayB[2].height);
    ctx.fillRect(platArrayA[1].x, platArrayA[1].y, platArrayA[1].width, platArrayA[1].height);
    ctx.fillRect(platArrayB[1].x, platArrayB[1].y, platArrayB[1].width, platArrayB[1].height);
      }`
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

N/A
### What is your best guess as to the source of the problem?
I think I need to use a constructor class but then I don't know how to call it in order to continuously create platforms 

### What things have you already tried to solve the problem?
Tried using arrays, tried creating a constructor class. 

### Paste a link to your repository here
https://github.com/johnzwiss/game-project

**Comment by tkolsrud** [comment]
I think what may help is to make the platforms a class, and then give them a render object that you can run in the game loop

**Comment by tkolsrud** [comment]
So `platformE` would extend the `platform` class, and then at a set interval it could run `platformE.render()`, whether inside the game loop or just independently when the page loads/game starts

**Comment by johnzwiss** [comment]
How would it then render the individual platforms as they drop? 

I had tried something similar earlier where the platforms were on a separate loop and would only update their position ever 2 seconds. It would then be erased by the game loop every 60 milliseconds.

**Comment by johnzwiss** [comment]
```
 class Platform {
    constructor(x, y, color, height, width) {
        this.x = (Math.random() * 500)
        this.y = 0,
        this.color = "brown",
        this.height = 10,
        this.width = 70
        this.speed = 0
    }
    render () {
        // ctx.fillStyle will determine the color(or style) of your element
        ctx.fillStyle = this.color
        // ctx.fillRect will draw a rectangle on the canvas
        ctx.fillRect(this.x, this.y, this.height, this.width)
    }
``` `

**Comment by johnzwiss** [comment]
So this should render a platform at a random spot on the top of my canvas, but then how do I continue to have the game move it down smoothly?

**Comment by tkolsrud** [comment]
You've got some different options for working that out. My first thought would be some kind of conditional that resets the height whenever it reaches a certain depth, or some kind of boolean that calls the render method recursively.
