### ISSUE TITLE
Make the cells so they cannot be played again.

### ISSUE THREAD

**Issue by bmaiden** [sei-ec-remote/project-1-issues#223]
### What's the problem you're trying to solve?
Once a match has been determined, figuring out how to make the cells so they cannot be played again.

### Post any code you think might be relevant (one fenced block per file)
```JS
/*----- state variables -----*/
let board; //an array
let squareColor = [];
let secondMove = true;
let squareOne;
let squareTwo;
let matchesMade = null;
let firstSquare = null;
let secondSquare = null;

function handleMove(event) {
  !secondMove ? (firstSquare = event.target) : (secondSquare = event.target);
  secondMove = !secondMove;
  if (secondMove === false) {
    squareOne = event.target.classList[1];
  } else {
    squareTwo = event.target.classList[1];
    if (squareOne === squareTwo) {
      // event.target.removeEventListener("click", handleMove)
      // firstSquare.removeEventListener("click", handleMove)
      // secondSquare.removeEventListener("click", handleMove)
      matchesMade += 2;

    } else {
      setTimeout(() => {
        firstSquare.style.backgroundColor = "";
        secondSquare.style.backgroundColor = "";

        secondMove ? (firstSquare = event.target) : (secondSquare = event.target);
        console.log("Not a match reset squares", squareOne, squareTwo); //inspect displays no match
      }, 2000);
    }
  }
}


```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
not seeing any unexpected behavior, trying to figure out how to make the cells so they cannot be played again.

### What is your best guess as to the source of the problem?
remove the event listener for the matching squares

### What things have you already tried to solve the problem?
      // event.target.removeEventListener("click", handleMove)
      // firstSquare.removeEventListener("click", handleMove)
      // secondSquare.removeEventListener("click", handleMove)

### Paste a link to your repository here
https://github.com/bmaiden/memory-browser-game

**Comment by nayaba** [comment]
Your code looks great and you're definitely on the right track with your firsSquare and secondSquare and removing the event listener!  The first thing we need to consider is that the event listener that has been added is actually `squarePicked` (which then calls the `handleMove` function).  So you must remove the _same_ event listener that was added (i.e. `squarePicked`).

Which brings us to a slight complication.  There is a single event listener for the _entire_ board.  Once you remove the event listener from `firstSquare` or `secondSquare` the whole board will be unclickable.  So you'll need to refactor the very last line of your code.  I will let you work on figuring that out for a while, but I will mention that you'll need to use something like `querySelectorAll` and an iterator method like `forEach`.

**Comment by bmaiden** [comment]
Still need assistance.

**Comment by nayaba** [comment]
Can you provide an update on the code you've edited so far?

**Comment by bmaiden** [comment]
```JS
/*---- event listeners -----*/
//click on square to make a move
document.getElementById("board").addEventListener("click", squarePicked);
document.getElementById("board").addEventListener("click", handleMove(firstSquare));
document.getElementById("board").addEventListener("click", handleMove(secondSquare));


function handleMove(firstSquare, secondSquare) {
  return function curried_func(event) {
    !secondMove ? (firstSquare = event.target) : (secondSquare = event.target);
    // console.log(secondMove)                //truthy
    //prevent more than two clicks by toggling (hide or show) second move
    secondMove = !secondMove;
    // console.log(secondMove)                  //inspect displays value
    // console.log('bang', !secondMove)         //inspect displays value using the bang operator
    // console.log (event.target.classList)     //inspect displays color associated with square clicked
    if (secondMove === false) {
      squareOne = event.target.classList[1];
      console.log(squareOne); //inspect displays color of square
    } else {
      squareTwo = event.target.classList[1];
      console.log(squareTwo); //inspect displays color of square
      if (squareOne === squareTwo) {
        // event.target.removeEventListener("click", handleMove)
        // firstSquare.removeEventListener("click", handleMove(firstSquare))
        // secondSquare.removeEventListener("click", handleMove(secondSquare))
        matchesMade += 2;
        console.log("It matches", matchesMade, squareOne, squareTwo); //inspect displays if match
      } else {
        setTimeout(() => {
          firstSquare.style.backgroundColor = "";
          secondSquare.style.backgroundColor = "";

          secondMove
            ? (firstSquare = event.target)
            : (secondSquare = event.target);
          console.log("Not a match reset squares", squareOne, squareTwo); //inspect displays no match
        }, 1000);
      }
    }
  }
};

**Comment by bmaiden** [comment]
Was thinking trying to pass the variables as an argument would be easier but am stuck again on how to proceed. When I uncomment removeEventListener for firstSquare and secondSquare I get the below error.

<img width="1028" alt="image" src="https://github.com/sei-ec-remote/project-1-issues/assets/148794472/fc761d71-b94c-4c8d-aabb-38201b53dcfd">

**Comment by bmaiden** [comment]
Here is what I was looking at. Article link: https://stackoverflow.com/questions/256754/how-to-pass-arguments-to-addeventlistener-listener-function

![image](https://github.com/sei-ec-remote/project-1-issues/assets/148794472/1d1ce3a5-ba24-4ffa-b583-a66f7b0236b4)

**Comment by nayaba** [comment]
Good updates.  Rather than having three event listeners though, let's try and re-factor one event listener:

```js
document.getElementById("board").addEventListener("click", squarePicked);
```

into another event listener that will iterate over the board and get  _each individual square_ and add an event listener to it, like this

```js
const squares = document.querySelectorAll('#board > div')
console.log(squares)
squares.addEventListener("click", squarePicked)
```

Like I mentioned before when you remove the event listener, like you have in this commented out code inside your handleMove function:

```js
firstSquare.removeEventListener("click", handleMove(firstSquare))
```

you need to remove the same event listener callback function that you added --> well we added squarePicked, didn't we?  So _that's_ what we'll need to remove, and we'll want to remove it from firstSquare and secondSquare, but not the whole board (otherwise we wouldn't be able to click on _anything_).  Lastly, when we remove an event listener, we don't need to pass any arguments to the callback function, or even invoke it.  So just like our parenthesis in our `addEventListener` look like this `("click", squarePicked)`, it will look the same when we `removeEventListener`.

**Comment by bmaiden** [comment]
New coding with error message:
```JS
/*---- event listeners -----*/
//click on square to make a move
// document.getElementById("board").addEventListener("click", squarePicked);
document.getElementById("board").addEventListener("click", function () {
  const squares = document.querySelectorAll('#board > div')
  console.log("squares event listener",squares)
  squares.addEventListener("click", squarePicked)
});
```

![image](https://github.com/sei-ec-remote/project-1-issues/assets/148794472/8fccf7b2-77bf-4c83-9bc7-25a639aa1b7a)

**Comment by bmaiden** [comment]
Adding it to the if statement:
```JS
      if (squareOne === squareTwo) {
          const squares = document.querySelectorAll('#board > div')
          console.log("squares event listener",squares)
          squares.addEventListener("click", squarePicked)
        // event.target.removeEventListener("click", handleMove)
        // firstSquare.removeEventListener("click", handleMove(firstSquare))
        // secondSquare.removeEventListener("click", handleMove(secondSquare))
        matchesMade += 2;
        console.log("It matches", matchesMade, squareOne, squareTwo); //inspect displays if match
```

get error message:
![image](https://github.com/sei-ec-remote/project-1-issues/assets/148794472/421a6643-29f7-469e-995b-33ec796df4fb)

**Comment by nayaba** [comment]
Go ahead and delete this line:
```js
document.getElementById("board").addEventListener("click", function () {
```
as well as it's closing curly bracket.  We're replacing it, not adding to it.

**Comment by bmaiden** [comment]
John & Jacob have tried assisting me and we still can not get the squares to be un-clickable. Could I get a 1:1 meeting?

**Comment by bmaiden** [comment]
Changing from making matches to a time limit.

**Comment by bmaiden** [comment]
Tylus assisted with making the cells so they cannot be played again.
