### ISSUE TITLE
CSS Image Overlaying

### ISSUE THREAD

**Issue by Jlarranaga** [sei-ec-remote/project-1-issues#224]
### What's the problem you're trying to solve?
I have a video background then I want another image on top of that in a div then the card image on top of that. But when that happens the paper image disappears. Also I cant center the title and button. 

### Post any code you think might be relevant (one fenced block per file)
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/f05ceb2d-b12d-47ed-86c7-06d2574a9aa0)

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error messages

### What is your best guess as to the source of the problem?
Either z-index or the position style is wrong. And the object-fit style options. 

### What things have you already tried to solve the problem?
asked class mates, google, try to debug the best I can. Tried multiple different styling options. 

### Paste a link to your repository here
https://github.com/Jlarranaga/Project1-WAR

**Comment by Jlarranaga** [comment]
Also when I add the card back-red image from the JS code. The paper image on the player deck disappears... along with another paper image

**Comment by nayaba** [comment]
In regards to your first question, I believe what you want is to be targeting the `divs` within the `#card` element and then giving them a background image (in your css).

As for the card backs - I'm not able to recreate this error.  Are you applying a `brick-red` class to your elements via javascript?  If so, perhaps this class is also being applied to the paper?

**Comment by Jlarranaga** [comment]
There are no divs in the card element. The cards are coming from a seperate CSS class. The cardStarter class. 

I don't follow... what do you mean brick-red class?

**Comment by nayaba** [comment]
First of all my bad - I meant back-red class!

Second, these are the divs I'm referring to.  They are children of the cards section, right?
```html
      <div id="playerDeck"><img src="images/Medieval-DeckHolder.png" alt="Deck Background" id="playerDeckBackground"></div>
      <div id="battlePlayerCard"></div>
      <div id="computerDeck"></div>
      <div id="battleComputerCard"></div>
      <div id="battleResult"><img src="/images/Battle Scroll.png" alt="Message Scroll"></div>
```

**Comment by Jlarranaga** [comment]
Yes in the JS file the red-back class is being applied. 
and yes those divs will contain the card images but the cards are coming from the cardstarter class
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/3da32360-8842-43e2-8a3a-0cf57259bd5d)

**Comment by Jlarranaga** [comment]
And this is where in JS the back-red class gets applied. 
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/54361f2e-8565-440f-93cb-655c511dc5d3)

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/d15ac8c2-befd-4f56-ba74-4e725a096390)
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/6c2afc51-bb06-474a-9485-1005bf605d6b)
