### ISSUE TITLE
movement

### ISSUE THREAD

**Issue by ItsAlbi007** [sei-ec-remote/project-1-issues#228]
### What's the problem you're trying to solve?
i need some sort of gameplan for the checker to hop over the opponent checker if thre is an opening and for that opponent to get eliminated from the game  

### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?
 i need to somehow id the square that's behind the opponent and jump over it and eliminate it 

### Paste a link to your repository here
https://github.com/ItsAlbi007/G-Project

**Comment by nayaba** [comment]
So I see that you're using some math to check for diagonals.
```js
      const diagonalOne = document.querySelector(`#c${col -1}r${row +1}`)
      const diagonalTwo = document.querySelector(`#c${col -1}r${row -1}`)
```

Is it possible to check for diagonals from `diagonalOne` and `diagonalTwo`?  After which you can determine if there is an opening and if so, allow the checker piece to occupy that opening?

See if you can implement that first, then you can start to tackle removing the other player's "jumped" piece.
