### ISSUE TITLE
Audio is being unpredictable

### ISSUE THREAD

**Issue by JohnArochaDev** [sei-ec-remote/project-1-issues#229]
### What's the problem you're trying to solve?

My background audio works sometimes and wont other times
### Post any code you think might be relevant (one fenced block per file)
```html
        <audio src="audio/backgroundsound.mp3" autoplay>
                <embed 
                src="audio/backgroundsound.mp3" 
                loop="true" 
                hidden="true" 
                autostart="true">
        </audio>
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
none

### What is your best guess as to the source of the problem?
no clue ive been trying to figure it out

### What things have you already tried to solve the problem?

everything online

### Paste a link to your repository here
https://github.com/jpjpjppj/Battleship

**Comment by nayaba** [comment]
Is this audio meant to be playing the entire time, or only when a square is clicked on?

**Comment by nayaba** [comment]
It could be that chromium browsers do not allow autoplay.  It's not a best practice to autoplay audio, as there are people who use screen readers who need to be able to hear the screen reader over any audio in order to interact with the site.  You might consider creating a button to start audio.

**Comment by JohnArochaDev** [comment]
Thanks!

**Comment by JohnArochaDev** [comment]
Ill try that

**Comment by JohnArochaDev** [comment]
Can you hop in a room with me? Im really struggling with this
