### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by daenamcclintock** [sei-ec-remote/project-1-issues#23]
### What's the problem you're trying to solve?
I am trying to get the game screen to appear when the start button is pushed. I have been able to make the start screen disappear, but have been unable to have the game screen simultaneously appear.

### Post any code you think might be relevant (one fenced block per file)
```js
function gameStart() {
    gamePlay = true;
    startScreenContainer.style.display = 'none';
    gamePlayContainer.style.removeProperty('display');

    // let backgroundImg = document.createElement('body');
    // backgroundImg.id = 'background-img'
    // backgroundImg.style.backgroundImage = 'url("/Users/daenamcclintock/sei/projects/game-project/imgs/Blackjack-Table.png")';
    // backgroundImg.style.backgroundRepeat = 'no-repeat';
    // backgroundImg.style.backgroundSize = 'fill';
    // backgroundImg.style.display = 'contents';
    
    // let hitButton = document.createElement('button');
    // hitButton.id = 'hit-button'
    // hitButton.style.backgroundColor = 'red';
    // hitButton.style.color = 'white';
    // hitButton.style.fontWeight = 'bold';
    // hitButton.style.padding = '5px 20px 5px 20px';
    // hitButton.style.display = 'contents';
    
    // let holdButton = document.createElement('button');
    // holdButton.id = 'hold-button'
    // holdButton.style.backgroundColor = 'green';
    // holdButton.style.color = 'white';
    // holdButton.style.fontWeight = 'bold';
    // holdButton.style.padding = '5px 20px 5px 20px';
    // holdButton.style.display = 'contents';
    
    // let doubleButton = document.createElement('button');
    // doubleButton.id = 'double-button'
    // doubleButton.style.backgroundColor = 'blue';
    // doubleButton.style.color = 'white';
    // doubleButton.style.fontWeight = 'bold';
    // doubleButton.style.padding = '5px 20px 5px 20px';
    // doubleButton.style.display = 'contents';
    
    // let splitButton = document.createElement('button');
    // splitButton.id = 'split-button'
    // splitButton.style.backgroundColor = 'black';
    // splitButton.style.color = 'white';
    // splitButton.style.fontWeight = 'bold';
    // splitButton.style.padding = '5px 20px 5px 20px';
    // splitButton.style.display = 'contents';
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
There is no error message in the console. The gamePlayContainer just is not appearing when I remove the 'display' style property that was initialized to "none".

### What is your best guess as to the source of the problem?
I'm honestly not sure. I've tried so many different ways to make the new screen appear including creating the entire screen from scratch using DOM code (see commented out code above) and nothing has seemed to be working.

### What things have you already tried to solve the problem?
I have tried creating DOM elements that will be created in the same function that is used to start the game when the gameStart button is pressed.
I also tried creating the elements within a div in my HTML and initializing the display to 'none' then accessing the display and changing it to 'contents' when the gameStart function is called.

### Paste a link to your repository here
https://github.com/daenamcclintock/game-project

**Comment by timmshinbone** [comment]
What's the logic in changing the display style to none when the gameStart is called? Wouldn't you want to change that display style? Maybe it'd be easier if you set up a "hidden" class that has display style none, and you change the class of the game window when the game starts?

**Comment by daenamcclintock** [comment]
Cory helped me resolve this issue. It was a simple change of an HTML id from the body to a div tag.
