### ISSUE TITLE
Set Interval Issues

### ISSUE THREAD

**Issue by Jlarranaga** [sei-ec-remote/project-1-issues#233]
### What's the problem you're trying to solve?
set interval is delaying the message by one full click of the button. It wont display the correct message until you click the button again but ny the time that happens we need a new message

### Post any code you think might be relevant (one fenced block per file)
```
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/ba1ed48b-7874-4dbb-93f8-f6a000dd4ed4)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

No error message
### What is your best guess as to the source of the problem?

something with the setinetrval method
### What things have you already tried to solve the problem?

google and researching more

### Paste a link to your repository here
https://github.com/Jlarranaga/Project1-WAR

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/ba1ed48b-7874-4dbb-93f8-f6a000dd4ed4)

**Comment by nayaba** [comment]
Have you tried changing the interval time?  Also, is the interval even necessary, or can the message appear instantaneously?

**Comment by Jlarranaga** [comment]
The interval is for aesthetic reasons. and yes but it delays when it starts.

**Comment by nayaba** [comment]
Sorry if I'm misunderstanding, but changing the time from 300 to maybe 150 doesn't help?

**Comment by Jlarranaga** [comment]
let me try

**Comment by Jlarranaga** [comment]
actually... im sorry. its not the set interval. i changed my code and now its not working right. I will debug it.
