### ISSUE TITLE
Centering Cards

### ISSUE THREAD

**Issue by Jlarranaga** [sei-ec-remote/project-1-issues#234]
### What's the problem you're trying to solve?
Center the game cards on the image background

### Post any code you think might be relevant (one fenced block per file)
```

```
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/0e64299a-ab9d-49fc-bd5c-75c96903f668)

![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/c16b0058-b3c5-44e6-bf2e-2e9e67992f4c)

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

No error message
### What is your best guess as to the source of the problem?

either with the card class or something in my CSS
### What things have you already tried to solve the problem?

google, and trial and error

### Paste a link to your repository here
https://github.com/Jlarranaga/Project1-WAR

**Comment by timmshinbone** [comment]
Try adding a little padding on the side that is too far over and see how that reacts, maybe share a screenshot if it goes wonky

**Comment by Jlarranaga** [comment]
I think i got it close enough
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/0b574d11-9b5a-4584-823d-a469adbff31c)

**Comment by Jlarranaga** [comment]
ok thats done

**Comment by Jlarranaga** [comment]
Ok now i need to center my 3 cards for war. but are they all on top of eachother? 
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/05c8eeaa-2ec7-4834-a4bd-7c9a92f853a3)

**Comment by Jlarranaga** [comment]
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/b328ab7f-eeee-402f-b384-a27165906513)

**Comment by timmshinbone** [comment]
Hard to say if that's the case without further review. We can take a look at this in a 1:1 right after deployment party

**Comment by Jlarranaga** [comment]
sounds good! Thank you!

**Comment by Jlarranaga** [comment]
Ok, so i decided to make an image of three cards to make life easier and now its small. I'm messing with it more but it wont get bigger. If there arent enough pixels will it stay small? 

![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/2efef6f3-ad49-4bf1-b967-4cec25449df7)
![image](https://github.com/sei-ec-remote/project-1-issues/assets/149622991/9902c818-23b7-409c-8719-36cb347c1e6c)

**Comment by timmshinbone** [comment]
We resolved this by fixing the original png file to be a little bigger and to go all the way to the edge
