### ISSUE TITLE
eliminating opponents

### ISSUE THREAD

**Issue by ItsAlbi007** [sei-ec-remote/project-1-issues#235]
### What's the problem you're trying to solve?
im trying to make the play to disappear when it jumps over

### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?
i need to somehow have the box  it gets jumped over that checker will disappear until i reset the whole game or something  

### Paste a link to your repository here
https://github.com/ItsAlbi007/G-Project

**Comment by timmshinbone** [comment]
Share the code that's being used to display the pieces on the board with a brief explanation. Share the code being used to make the 'jump' move.
