### ISSUE TITLE
when Visibility is changed in JS = undefined

### ISSUE THREAD

**Issue by Clund1** [sei-ec-remote/project-1-issues#241]
### What's the problem you're trying to solve?
Its giving an error on initialization where the visibility of the div contents should be disappearing after 5 seconds.
The visibility is declared in the CSS but its unable to be changed by the JS?

### Post any code you think might be relevant (one fenced block per file)
stated visibility in CSS
```CSS
.goblin{
    border: .2vmin solid brown;
    border-radius: .75vmin;
    visibility: visible;
}
```
```JS
    forest.generateHidingSpots() //This generates random spawn of goblins on forest
    goblinEl.forEach((tile) =>{
            id = tile.id;
            tileArrPosition = forest.goblins[parseInt(id[1])][parseInt(id[3])]; // takes ID of each goblin space to formulate reference
            console.log(tileArrPosition);
            tile.style.backgroundColor = FORESTLOOKUP[tileArrPosition]; //uses FORESTLOOKUP to ref. background color/url choice
    })
setTimeout(hide,5000); //5 seconds to memorize then hide
}

//HIDES CHOICES
function hide(){
    goblinEl.style.visibility = "hidden";
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
![Screenshot 2023-12-05 at 3 43 14 PM](https://github.com/sei-ec-remote/project-1-issues/assets/149333009/d232ed67-b2b5-4c1c-b2ba-fa91cffb5cd2)

### What is your best guess as to the source of the problem?
Something is overwriting something or visibility isnt declared correctly?

### What things have you already tried to solve the problem?
looked it up on MDN and W3, tried using ```display:"none"``` but that removes the outline(which I don't want)

### Paste a link to your repository here
https://github.com/Clund1/Project-1---GAME

**Comment by timmshinbone** [comment]
Console log the `goblinEl` and show me what that is here

**Comment by Clund1** [comment]
<img width="532" alt="Screenshot 2023-12-05 at 4 17 00 PM" src="https://github.com/sei-ec-remote/project-1-issues/assets/149333009/0ee41a1f-534e-4d3e-9115-89d0f4a6a635">

**Comment by timmshinbone** [comment]
ok! That's why it's saying `goblinEl.style` is undefined, because goblinEl is ACTUALLY goblinEls, a nodeList with multiple elements, who all have their own individual styles. You can target specific ones to change their style using array syntax(`goblinEl[2].style` for example)

**Comment by timmshinbone** [comment]
which means goblinEl should be named goblinEls, with the s indicating plurality

**Comment by Clund1** [comment]
refactored for plurality and I'm still getting the same error as above on the same line

goblinEls logs the same as well
