### ISSUE TITLE
audio

### ISSUE THREAD

**Issue by RyanCLuis** [sei-ec-remote/project-1-issues#246]
### What's the problem you're trying to solve?
so i added an eventlistener to add sound to my game, everything is working, but was wondering why im getting a error message .

### Post any code you think might be relevant (one fenced block per file)
```js
function renderBoard() {
    document.getElementById("mind-count").innerText = minds
    document.getElementById("head").addEventListener("click", setHead)
    setMinds()
    // populate my tiles using a for loop
    for (let r = 0;r < rows; r++) {
        let row = []
        for (let c = 0; c < columns; c++) {
            // making a div tag in HTML
            let tile = document.createElement("div")
            tile.id = `${r}-${c}`
            tile.addEventListener("click", tileClicked)
            // this is an event listener to play music on tile click
            tile.addEventListener("click", playMusic)
            document.getElementById("tiles").append(tile)
            row.push(tile)
        }
        board.push(row)
    }
}
```
```js
function playMusic () {
    let audio = new Audio("soundEffects/gun.mp3")
    audio.play()
}
```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

![image](https://github.com/sei-ec-remote/project-1-issues/assets/150068816/0ad5c759-dd16-4018-ba50-662df7a6e6fd)
### Paste a link to your repository here
https://github.com/RyanCLuis/Minesweeper

**Comment by timmshinbone** [comment]
You can ignore that for now, if it's not breaking anything it should be fine

**Comment by timmshinbone** [comment]
If it's absolutely killin ya, try adding this to the head:
```html
<link rel="shortcut icon" href="#">
```

**Comment by RyanCLuis** [comment]
ty @timmshinbone its not killing me, was just wondering why
