### ISSUE TITLE
Shuffle Function is not running

### ISSUE THREAD

**Issue by Tessabaxter12** [sei-ec-remote/project-1-issues#249]
### What's the problem you're trying to solve?
Trying to shuffle the array of the front images

### Post any code you think might be relevant (one fenced block per file)
```js
function shuffleCards() {
  for(Let [i] = cards.length -1; i > 0; i--) {
    let randomIndex = Math.floor(Math.random() * (i+1));
    cards[randomIndex].name.order = i;
    cards[i].name.order = randomIndex;
  }
}
```
### What is your best guess as to the source of the problem?
Not calling the front of the image correctly

### What things have you already tried to solve the problem?
Researching and MDN

### Paste a link to your repository here
https://github.com/Tessabaxter12/Memory_Game

**Comment by timmshinbone** [comment]
add a comment above each line in that function describing what each line is supposed to be doing and share that here as a reply
