### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-1-issues#25]
### What's the problem you're trying to solve?

I can't get my counter to become a global variable.

### Post any code you think might be relevant (one fenced block per file)

```js
const starCollected = () => {
    for (let i = 0; i < stars.length; i++) {
        if (
            stars[i].x < player.x + player.width &&
            stars[i].x + stars[i].width > player.x &&
            stars[i].y < player.y + player.height &&
            stars[i].y + stars[i].height > player.y
        ) {
            console.log("COLLECTED STAR")
            // ctx.clearRect(0, 0, game.width, game.height)
            // return Star.alive = false
            // counter++
            // console.log(counter)
            //~~~~~~~~~ retry ~~~~~~~~~~~~
             stars.splice(stars)
             counter++
            //  if (counter === 2) {
            //      console.log("YOU WIN!")
                // return
            // }
        }
    }
}

// console.log(counter)
let counter = 0
let pressedJump = false
let frame = 0
let gamespeed = 2

const gameLoop = () => {
    ctx.clearRect(0, 0, game.width, game.height)
    player.update()
    player.render()
    spawnStars()
    starCollected()
    // if (starCollected()) {
    //     counter++
    //     console.log(counter)
    // }
    spawnObstacles()
    detectHit()
    if (player.alive === false) {
        console.log("GAMEOVER")
        //insert game over text
        return
    }
    requestAnimationFrame(gameLoop)  
    frame ++ 
    // console.log(frame)
}
gameLoop();

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

I was expecting to be able to use my counter variable inside my gameloop, the error told me the variable counter hasn't been declared.

### What is your best guess as to the source of the problem?

I'm making my counter variable a local variable for my collecting stars functions

### What things have you already tried to solve the problem?

I have tried putting my function inside my game loop instead but I still can't figure it out.

### Paste a link to your repository here

https://github.com/ivycle94/Project-1

**Comment by tkolsrud** [comment]
So in this case you'd want to move those variable declarations to the top of the file. Javascript will hoist functions from any location, but variables have to be declared _before_ you use them.

**Comment by ivycle94** [comment]
I have tried that, but I still couldn't get my game to end. Is there a way I can share my screen to show the multiple things I've tried that I couldn't get to work?

**Comment by ivycle94** [comment]
Dorieann came in a break room with me and helped me fix the issue. It was a syntax error.
