### ISSUE TITLE
content is larger than the screen 

### ISSUE THREAD

**Issue by FartuunH** [sei-ec-remote/project-1-issues#251]
### What's the problem you're trying to solve?
to see all the content in the page i have to scroll down

### Post any code you think might be relevant (one fenced block per file)
```
body{
height: 100vh; 
font-weight: bold;
font-family: Arial, Helvetica, sans-serif;
background-color: rgb(31, 30, 30);
overflow-x: hidden;

}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
i have to scroll to see all the buttons and keyboard

### What is your best guess as to the source of the problem?

the body size is not adjusting with the screen
### What things have you already tried to solve the problem?

changed the body size to 100vh to 100%
to 400px

### Paste a link to your repository here
https://github.com/FartuunH/Wordle

**Comment by timmshinbone** [comment]
Try making the body size 90% of the screen, either `90vh` or `90%`

**Comment by FartuunH** [comment]
Thanks Tim, fixed it was the content div not the body
