### ISSUE TITLE
the checkers get combined 

### ISSUE THREAD

**Issue by ItsAlbi007** [sei-ec-remote/project-1-issues#252]
### What's the problem you're trying to solve?

my checkers somehow they get connected together and they disappear 
### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?

something might be wrong with my checkforskip or handleclick 
### What things have you already tried to solve the problem?

i console.log everything but i cant figure out what its going on 

### Paste a link to your repository here
https://github.com/ItsAlbi007/G-Project

**Comment by timmshinbone** [comment]
My brother in christ, please I am begging you to share some code.

**Comment by ItsAlbi007** [comment]
> My brother in christ, please I am begging you to share some code.

my bad my bad i got you in a second
