### ISSUE TITLE
Trouble with git 

### ISSUE THREAD

**Issue by spenserg92** [sei-ec-remote/project-1-issues#253]
### What's the problem you're trying to solve?
trying to push some changes through to main.

### Post any code you think might be relevant (one fenced block per file)
```

```

### What is your best guess as to the source of the problem?
something to do with branching?

### Paste a link to your repository here
https://github.com/spenserg92/Memory-Game

**Comment by timmshinbone** [comment]
share screenshot of your terminal

**Comment by spenserg92** [comment]
![Screenshot 2023-12-06 at 4 01 52 PM](https://github.com/sei-ec-remote/project-1-issues/assets/149332042/df422987-c0ed-422a-9c7d-bf7934dc6665)

**Comment by spenserg92** [comment]
I deleted the other branches thinking that would help but it is still doing that. So I only have the main branch

**Comment by timmshinbone** [comment]
ok, `git pull origin main`, then push to main

**Comment by spenserg92** [comment]
Great thanks!
