### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by AOehmann239** [sei-ec-remote/project-1-issues#28]
### What's the problem you're trying to solve?
--Trying to get the obstacles to move at an established speed on repeat

--Question for the hit detection re the way Timm showed yesterday changing the detectHit to taking a param thing but can you make it a class so anything with the class of say obstacle to include all the obstacles?  So that way I dont have to do if conditions for every individual obstacle.

### Post any code you think might be relevant (one fenced block per file)
```
Gave the obstacle a speed property in the constructor and gave the car a speed of 1 when I called it but I think I dont understand how speed works.  

`js
if (
    player.x < thing.x + thing.width &&
    player.x + player.width > thing.x &&
    player.y < thing.y + thing.height &&
    player.y + player.height > thing.y
  ) {
    thing.alive = false;`

```

### What is your best guess as to the source of the problem?
Something wrong with my understanding of how to 

### What things have you already tried to solve the problem?
Searched a couple youtube tutorials

### Paste a link to your repository here
https://github.com/AOehmann239/game-project

**Comment by tkolsrud** [comment]
included x-axis delta in the `render` method
