### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by AOehmann239** [sei-ec-remote/project-1-issues#32]
### What's the problem you're trying to solve?

1-Want to collapse the obstacles into a 'thing' within the hit detection to detect a hit with any of the obstacles instead of having to declare an if for each of the (maybe add the obstacles to a class and modify the class given the levelup condition?)
2- Should I put the different obstacles in an array?  Would that benefit me in any way?
3-Having the obstacles able to be referenced as a whole would also allow me to increase the speed for all at once by a certain factor?  given the level up?

### Post any code you think might be relevant (one fenced block per file)
```
`js`
//here's where I want the detection to be global for all obstacles
const detectHit = () => {
  if (
    car1.x < frog.x + frog.width &&
    car1.x + car1.width > frog.x &&
    car1.y < frog.y + frog.height &&
    car1.y + car1.height > frog.y
  ) {
    frog.alive = false;
  }
};


class Obstacle {
  constructor(x, y, color, width, height, speed, type) {
    this.x = x;
    this.y = y;
    this.color = color;
    this.width = width;
    this.height = height;
    this.speed = speed;
    this.type = type;
  }
  render = function () {
    ctx.fillStyle = this.color;
    ctx.fillRect(this.x, this.y, this.width, this.height);
    this.x = this.x + this.speed;
  };
}

```

### What things have you already tried to solve the problem?
Tried changing the car1. etc down in the detectHit() to thing and the parameter in the function to thing as well, that gave an error

### Paste a link to your repository here
https://github.com/AOehmann239/game-project

**Comment by tkolsrud** [comment]
I believe to set the obstacles to a "thing", you need to add the obstacles to an array, set that array to a variable, and then insert that variable as an argument into your hit detection function*

So like push the cars into an array, `cars` and then run `detectHit(cars)`

**Comment by AOehmann239** [comment]
tried doing the whole carsArray passed into the detectHit() and it didnt work

**Comment by AOehmann239** [comment]
Needed to loop through each individual item of the array with a for loop and compare it to the frog dimensions
