### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by jscodeguy** [sei-ec-remote/project-1-issues#34]
### What's the problem you're trying to solve?
I haven't been able to fix my collision for my objects

### Post any code you think might be relevant (one fenced block per file)
```js
const detectDrPepperHit = () => {
  if (
    player.x < drPepper.x + drPepper.width &&
    player.x + player.width > drPepper.x &&
    player.y < drPepper.y + drPepper.height &&
    player.y + player.height > drPepper.y &&
    isGloved === true
  ) {
    drawPunch();
    drPepper.alive = false;
    document.getElementById("status").textContent = "You punch a dr Pepper!";
  } else if (
    player.x < drPepper.x + drPepper.width &&
    player.x + player.width > drPepper.x &&
    player.y < drPepper.y + drPepper.height &&
    player.y + player.height > drPepper.y &&
    isGloved === false && drPepperDirection === 'down'
  ) {
    player.x -= 50;
    player.y += 50
    playerHealth -= 10;
    document.getElementById("status").textContent =
      "You got punch by a drPepper!";
  } else if (
    player.x < drPepper.x + drPepper.width &&
    player.x + player.width > drPepper.x &&
    player.y < drPepper.y + drPepper.height &&
    player.y + player.height > drPepper.y &&
    isGloved === false && drPepperDirection === 'up'
  ) {
    player.x -= 50;
    player.y -= 50
    playerHealth -= 10;
    document.getElementById("status").textContent =
      "You got punch by a drPepper!";
  }
  else if (playerHealth === 0) {
    document.getElementById("status").textContent = "you die by a dr Pepper!";
  }
};
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm only able to detect a collision only in the top of the object

### What is your best guess as to the source of the problem?
I believe that the problem is in the pixel area I'm selecting to trigger my collision

### What things have you already tried to solve the problem?
I've tried moving around the x y height and width properties to try and get different results but it just shifts my detection point off of the object

### Paste a link to your repository here
https://github.com/jscodeguy/Shanes-Game-Project

**Comment by tkolsrud** [comment]
For some reason x and y axis are inverted inside of the canvas board, so hit detection conditionals had to be edited
