### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by lyee197** [sei-ec-remote/project-1-issues#38]
### What's the problem you're trying to solve?
I input my drawWalls function into the gameLoop. I understand the problem and the reason for why drawWalls keeps repeating and loading I just don't know exactly how to fix it.

### Post any code you think might be relevant (one fenced block per file)
```js
let walls = [
    wallOne, wallTwo, wallThree, wallFour, wallFive,
    wallSix, wallSeven, wallEight, wallNine, wallTen,
    wallEleven, wallTwelve, wallThirteen, wallFourteen, wallFifteen,
    wallSixteen, wallSeventeen, wallEighteen, wallNineteen, wallTwenty,
    wallTwentyone, wallTwentyTwo, wallTwentyThree, wallTwentyFour, wallTwentyFive,
    wallTwentySix, wallTwentySeven, wallTwentyEight, wallTwentyNine, wallThirty,
    wallThirtyOne, wallThirtyTwo, wallThirtyThree, wallThirtyFour, wallThirtyFive,
    wallThirtySix, wallThirtySeven, wallThirtyEight, wallThirtyNine, wallFourty,
    wallFourtyOne, wallFourtyTwo, wallFourtyThree, wallFourtyFour, wallFourtyFive,
    wallFourtySix, wallFourtySeven, wallFourtyEight, wallFourtyNine, wallFifty,
    wallFiftyOne, wallFiftyTwo, wallFiftyThree, wallFiftyFour, wallFiftyFive,
    wallFiftySix, frontT, frontB, backT, backB,
    topW, botW]
// Runner.detectWall(walls[i])]
const drawWalls = () => {
    for (let i = 0; i < walls.length; i++) {
        walls[i].render()
        console.log('this wall was rendered: ' + walls[i])
        // Runner.detectWall(walls[i])
    }
}
drawWalls()
const stopGameLoop = () => {clearInterval(gameInterval)}

document.addEventListener('DOMContentLoaded', function () {
    // document.addEventListener('keydown', movementHandler)
    gameInterval
})
const gameLoop = () => {
    if (end.alive) {
        detectHit()
    }
    ctx.clearRect(0, 0, game.width, game.height)
    movement.textContent = player.x + ' , ' + player.y
    if (end.alive) {
        end.render()
    }
    player.render()
    // drawWalls()
    player.movePlayer()
}
let gameInterval = setInterval(gameLoop, 60)
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
When I load the page, I see that the walls render indefinitely. I'm not sure if that's a problem or may crash the computer

### What is your best guess as to the source of the problem?
I'm guessing it's because it's in the game loop but i only want it to render once instead of indefinitely

### What things have you already tried to solve the problem?
I tried taking the function out and put it in global but nothing appears.

### Paste a link to your repository here
[Game Project](https://github.com/lyee197/game-project/tree/walls)

**Comment by timmshinbone** [comment]
Liam are you still working on this? If not, please add a brief description of the solution and close the issue.

**Comment by lyee197** [comment]
I am not working on this anymore.  I was helped yesterday with the reason why it kept looping and that it won't hinder the game.
