### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by thefrostyausty** [sei-ec-remote/project-1-issues#39]
### What's the problem you're trying to solve?
I'm trying to establish the scores for my player 1 and 2. While establishing the values, it would return 'null' on the value/variable itself

### Post any code you think might be relevant (one fenced block per file)
```js
const p1Score = document.getElementById('player1')
console.log('what is p1score returning', playerMessage)
const p2Score = document.getElementById('player2')

```
```html
<div class="players-container">
        <p id="player1">Player1</p>
        <p id="player2">Player2</p>
    </div>

```
### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
app.js:177 Uncaught ReferenceError: p1Score is not defined
    at displayScores (app.js:177:41)
    at app.js:181:1

### What is your best guess as to the source of the problem?
I've looked and I literally have no guess at all of what my problem could be.

### What things have you already tried to solve the problem?
tried changing from querySelector to getElementbyID even changing if it had single or double quotes, or using the Id identifier '(#)'

### Paste a link to your repository here
https://github.com/thefrostyausty/Project-1-Austin.git

**Comment by timmshinbone** [comment]
Can you share the code where you're trying to print `p1Score`? (should be line 177 so I'd like to see the surrounding code as well)

**Comment by thefrostyausty** [comment]
```js
const displayScores = () => {
    console.log('inside displayScores', p1Score)
    p1Score.innerText = `Player 1: ${player1Score}`
    p2Score.innerText = `Player 2: ${player2Score}`
}
displayScores();
```
