### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by ivycle94** [sei-ec-remote/project-1-issues#4]
### What's the problem you're trying to solve?

I can't get the obstacles of my game to move across the x axis.

### Post any code you think might be relevant (one fenced block per file)
```js
class Obstacles {
    constructor(x, y, color, height, width) {
        this.x = x,
        this.y = y,
        this.color = color,
        this.height = height,
        this.width = width,
        this.alive = true,
        this.moveObstacles = function () {
            if (this.x < 0) {
                this.x -= 1
            }
        },
        this.render = function () {
            ctx.fillStyle = this.color
            ctx.fillRect(this.x, this.y, this.height, this.width)
        }
    } 
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

I was trying to get the obstacle to move from 960 px to 0 px across the x axis, towards my player model (ball)

### What is your best guess as to the source of the problem?

I don't think I used the correct logic, or the syntax is wrong.

### What things have you already tried to solve the problem?

I tried make the obstacles x value inside the moveObstacles function "-1", but nothing happened. Afterwards I tried putting it into an if statement, but it still didn't work. 

### Paste a link to your repository here

https://github.com/ivycle94/Project-1

**Comment by ivycle94** [comment]
Yes, I tried calling it within my gameLoop function.

**Comment by timmshinbone** [comment]
```js
this.moveObstacles = function () {
            if (this.x < 0) {
                this.x -= 1
            }
        }
```
This function is saying 'if x is less than 0', are you sure you don't want to make it 'if less is greater than 0'?

**Comment by cory-yonomi** [comment]
Got that sorted right before you commented! Also worked on an interval question. Marking this closed
