### ISSUE TITLE
game project issue - change background image on click 

### ISSUE THREAD

**Issue by steviemilitello** [sei-ec-remote/project-1-issues#47]
### What's the problem you're trying to solve?

change the background on click of the button

### Post any code you think might be relevant (one fenced block per file)
```js

const questBackground0 = document.body.style.backgroundImage = url("/images/tavern.jpeg")
const questBackground1 = document.body.style.backgroundImage = url("/images/tavernbarrel.jpeg")

// change background on click

const changeBackground = () => {
    document.body.style.backgroundImage = url("")
    document.body.style.backgroundRepeat = "no-repeat"
    document.body.style.backgroundSize = "cover"

}

// quests

const beginQuest = () => {
    document.body.appendChild(questBackground0)
    message.innerText = "Choose your Path!"
    button1.addEventListener("click", goToQuest1, changeBackground(questBackground1))
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

url is not defined

### What is your best guess as to the source of the problem?

not sure, it may have something to do with how the changeBackground and questBackground0 is working in the function

### What things have you already tried to solve the problem?

changed scope of various elements from inside function to global, modified changeBackground function, invoked changeBackground function when DOM content is loaded

### Paste a link to your repository here

(https://github.com/steviemilitello/project1)

**Comment by tkolsrud** [comment]
It looks like your variable is nesting `document.body.style.backgroundImage` inside of `document.body.style.backgroundImage`. You should be able to just set `questBackground` to the url

**Comment by tkolsrud** [comment]
And then modify your `changeBackground` function to take a parameter and insert it into the "url" portion of background image

**Comment by steviemilitello** [comment]
thank you, i'll try that! i'll let you know how it goes!
