### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by curiouslearner999** [sei-ec-remote/project-1-issues#5]
### What's the problem you're trying to solve?
Board does not generate 2 at random tile when I game loads

### Post any code you think might be relevant (one fenced block per file)
```
const createBoard = () => {
        for(let i = 0; i < width*width; i++) {
            tile = document.createElement('div')
            tile.innerHTML = ""
            gameBoard.appendChild(tile)
            tiles.push(tile)

            // generate()

            // generate()
        }
    }     
    createBoard()

    // function to generate random 2 on the board
    const generate = () => {
        let randomNumber = Math.floor(Math.random()*tiles.length)
        if (tiles[randomNumber].innerHTML === "") {
           tiles[randomNumber].innerHTML = 2
        } else {
            generate()
        }
        
    }
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
when I call generate within createBoard get an error can not access generate before initialization. CreateBoard  does not create 16 tiles on the board but creates 1

### Paste a link to your repository here
https://github.com/curiouslearner999/Game-Project-1

**Comment by tkolsrud** [comment]
It looks like because `createBoard` is using `generate` when it's defined, `generate` isn't being hoisted. So if you just move the `generate` definition above `createBoard` it will run

**Comment by DoireannJane** [comment]
Also, i think innerHTML has to take 2 as a string?

**Comment by timmshinbone** [comment]
innerHTML requires a string of html, something like:
```js
`<p>something</p>`
```

You might want to consider innertext if the text is all you're trying to change/add
