### ISSUE TITLE
No player movement

### ISSUE THREAD

**Issue by jadenRuplal** [sei-ec-remote/project-1-issues#50]
### What's the problem you're trying to solve?
I'm trying to get my player one object which is a square to move when pressing the arrow key

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I don't have errors, I put a test to see if the key is working and it is but its not doing what I want

### What is your best guess as to the source of the problem?
something with my defining of player one isn't working

### What things have you already tried to solve the problem?
I can't think of any solutions 

### Paste a link to your repository here
https://github.com/jadenRuplal/Actual-Project-1.git

**Comment by timmshinbone** [comment]
Share the code for your player creation, and share the code that takes in key input and makes something happen.

**Comment by jadenRuplal** [comment]
I figured out the problem, I need to create a gameLoop as it only runs my code once
