### ISSUE TITLE
Game project issue - clear canvas element after player "collects"

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-1-issues#52]
### What's the problem you're trying to solve?
After the player collects an item, I need it to disappear from the canvas 

### Post any code you think might be relevant (one fenced block per file)
```JavaScript 
const detectHit = () => {
   
    if (player.x < star.x + star.width && player.x + player.width > star.x && player.y < star.y + star.height && player.y + player.height > star.y) {
        console.log('we have a hit')
        ctx.clearRect(0, 0, game.width, game.height)
        score += 10
        document.getElementById('points').textContent= score
        statusWindow.textContent = 'You collected a star!'
    }
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message. The element keeps raising the score instead of just doing it the one time I intended.

### What is your best guess as to the source of the problem?
I am not clearing it properly form canvas

### What things have you already tried to solve the problem?
Tried looking up removing elements from canvas, tried ctx.clearRect(x,x,x,x) 

### Paste a link to your repository here
https://github.com/shaialoni/SEIR-6-6-Project-1.git

**Comment by timmshinbone** [comment]
How/Where are you displaying them on the canvas, share the code for that

**Comment by shaialoni** [comment]
```JavaScript
const gameLoop = () => {
    
    if (score < 100) {
        detectHit()
    } else {
        statusWindow.textContent = 'You Won!'
    }
    ctx.clearRect(0, 0, game.width, game.height)
    player.render()
    setInterval(star.render(), 5000)
    
}
```

**Comment by timmshinbone** [comment]
Consider where your objects/elements live, and maybe you need another method for displaying them. Think about this, if you have all your objects live in some array, then you can loop over that array and render each of those items, then, if that item gets spliced or popped from the array, it'll no longer appear. So, the pseudo code might look like this:

- stars live in an array, when they are created, they are added to starArr
- loop over starArr and call render method for each of them(inside the game loop)
- if star is collected(on collision) that star gets removed from starArr
- What happens next?

**Comment by shaialoni** [comment]
So would I need a separate game loop to render and eliminate stars and any other objects that aren't the player?

**Comment by timmshinbone** [comment]
You would need to figure out how and when to run the 'rendering loop' INSIDE of the game loop

**Comment by shaialoni** [comment]
I have the rendering inside the game loop already, that's what I shared above......?
I will try to create separate processes for the rendering of the items and see if I can combine them, but still not clear on how to make just the specific item disappear after collecting

**Comment by timmshinbone** [comment]
That's the idea behind storing the items in the array, and rendering based on the array. If the items are in the array, then they show up on the page, as soon as the item is removed from the array, they are no longer rendering. Spend some time playing with it and let me know how it goes
