### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by tylly** [sei-ec-remote/project-1-issues#55]
### What's the problem you're trying to solve?
I am trying to loop through an array of objects and remove the elements that lack an image url (these array elements are all objects that have "image" keys, but the value of the ones i'm trying to remove are listed as '')

### Post any code you think might be relevant (one fenced block per file)
```
Here is an example of one of the elements in question

image: Array(4)
0: {size: 'small', #text: ''}
1: {size: 'medium', #text: ''}
2: {size: 'large', #text: ''}
3: {size: 'extralarge', #text: ''}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I have tried running a for loop that splices these elements but they still remain

### What is your best guess as to the source of the problem?
I might not be targeting the object correctly
Additionally, an iterator method would probably be a better option here, but it would still work the same...hence my confusion.

### What things have you already tried to solve the problem?
for (let i = 0; i < topAlbums.length; i++){
      if (topAlbums[i].image[2]['#text'] === false || undefined || null || ''){
        topAlbums.splice(i, 1)
      }
    }

### Paste a link to your repository here
https://github.com/tylly/Music-Genius

**Comment by mattkeane-ga** [comment]
What happens when you remove elements from an array while you iterate over it?

I think your idea for an iterator method might be a good choice. Try to think of one that returns only the elements that fit a given criterion...

**Comment by tylly** [comment]
I got it!! Thank you Matt. This is what I used

 topAlbums = data.topalbums.album.filter((hasImage) => {
       return hasImage.image[2]["#text"].startsWith('https')
    })
