### ISSUE TITLE
Support with refining collision detection

### ISSUE THREAD

**Issue by nickesparza** [sei-ec-remote/project-1-issues#58]
### What's the problem you're trying to solve?
I have a workable solution for detecting collision in a 2D space. However, it is inexact, and I'm trying to lock it down to ensure no unintended movement is allowed.

### Post any code you think might be relevant (one fenced block per file)
Here is how I am detecting collision right now. The Player object and the Wall objects are all the same size, 50x50:
```
        class Player {
            constructor(x, y) {
                this.x = x,
                this.y = y,
                this.lastX = null,
                this.lastY = null
```
the player class stores a 'lastX' and 'lastY' variable to determine their last position before a movement key is pressed
```
        const movementHandler = (e) => {
            switch (e.keyCode) {
                case (87): // W
                case (38): // up arrow
                    // this moves the player up
                    player.lastY = player.y
                    player.lastX = player.x
                    player.y -= 50
```
in the movement handler, the function updates lastX and lastY before moving the player
```
                this.blockPlayer = function () {
                    if (player.x === this.x && player.y === this.y) {
                        player.y = player.lastY
                        player.x = player.lastX
                    }
                }
```
wall objects have this function that checks every frame if the player is inside it, and resets them to their last X and Y position.
```
        const detectEdge = () => {
            if (player.x < 0) {
                player.x = 0
            } else if (player.y < 0) {
                player.y = 0
            } else if (player.x + player.width > canvas.width) {
                player.x = canvas.width - player.width
            } else if (player.y + player.height > canvas.height) {
                player.y = canvas.height - player.height
            }
        }
```
I also have a function that detects if the player goes off the screen, to reset them
```
const playID = setInterval(() => {
            // render and collision and scoring functions that push information to DOM elements
            ctx.clearRect(0, 0, canvas.width, canvas.height)
            // then, draw the map
            wallObj.forEach(wall => {
                wall.render()
                wall.blockPlayer()
            })
            // then, detect if the player is outside the bounds of the canvas and reset them if necessary
            detectEdge()
            // then, render the player
            player.render()
```
inside the game loop, I do all edge and collision detection, and then render the player

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
The issue I am seeing is that if a movement key is held down, the player is able to move quickly through objects. They are stopped by the detectEdge function since it runs afterward, but it does not stop them from getting inside the wall objects. I also noticed that double inputs (such as left and up simultaneously) allow the player to move into solid objects as well.

### What is your best guess as to the source of the problem?
My best guess is that the movement inputs are being read faster than the game loop is running, which lets the player object move and update their coordinates before the game has time to check if they're somewhere they aren't supposed to be.

### What things have you already tried to solve the problem?
The player was actually able to get offscreen before I moved the detectEdge function after the wall check function while writing this issue. So that's resolved, but I'm not sure how to fix this additional collision issue beyond increasing the rate that the game loop runs, which may not even resolve it depending on how quickly the key inputs are being read.

### Paste a link to your repository here
https://github.com/nickesparza/ga-1-project-burger (current work is on the experimental branch)

**Comment by nickesparza** [comment]
UPDATE: changing 'keydown' to 'keyup' in the movement event listener does resolve this, but it feels a little awkward for the player to not move until the key is released.

**Comment by scarletpuma** [comment]
This is a really great rundown of how collision detection works in canvas: https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/Collision_detection

And this goes really in depth on the physics of it: https://spicyyoghurt.com/tutorials/html5-javascript-game-development/collision-detection-physics

**Comment by nickesparza** [comment]
I did read the MDN breakout game but was having a hard time applying the principles because in their example the ball is not directly under the player's control and is not listening for inputs, just purely the collision with a brick. I will check out the second article now!

**Comment by scarletpuma** [comment]
Was that any help at all?

**Comment by nickesparza** [comment]
A little, but it's very physics-heavy and seems like a bit of overkill for what I'm looking for. Right now I'm hoping to find a way to check if two edges are next to each other and if so, stop the player from moving in that direction. I may end up reworking movement to be more like what Timm showed us in the advanced canvas lesson, so I'm not out of ideas yet.

**Comment by scarletpuma** [comment]
Okay! Let me know if you need anything.

**Comment by nickesparza** [comment]
I fixed this using a modified version of the code shown on this replit: https://replit.com/talk/learn/Basic-Platformer-With-Javascript-and-HTML/7509

Since there is no gravity in my game, I simplified the checks and applied a version of the right-left collision to up and down as well. Seems to work now with no issues!
