### ISSUE TITLE
Issue with height and width using method CanvasRenderingContext2D.fillRect()

### ISSUE THREAD

**Issue by rsm-dnierman** [sei-ec-remote/project-1-issues#6]
### What's the problem you're trying to solve?

I am trying configure the size of my Caterpillar

### Post any code you think might be relevant (one fenced block per file)
**class creation:**
```js
class interactiveElement {
    constructor(x,y,height,width,imgUrl, opacity) {
        this.x = x,
        this.y = y,
        this.height = height,
        this.width = width,
        this.imgUrl = imgUrl,
        this.opacity = opacity,
        this.render = function() {
            ctx.fillStyle = 'green' // change this later
            // ctx.fillRect will draw a rectangle on the canvas
            ctx.fillRect(this.x, this.y, this.height, this.width)
        }
```
**Instance of class creation:**
```js
// create Caterpillar
let Caterpillar = new interactiveElement(100,50,10,10,"placeholder image url",1)
```

**Method of class being called upon page content load:**
```js
document.addEventListener('DOMContentLoaded', function() {
    Caterpillar.render()
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Unexpected behavior: when height = width for the parameters of .fillrect I am getting a rectangle instead of a square.. Somehow how height shows up on the screen greater that width  --> represented by a vertical rectangle

### What things have you already tried to solve the problem?
 - looked up the method on mdn: [https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillRect](url)

### Paste a link to your repository here
[https://github.com/dnierman0920/game-project-Caterpillar.git](url)

**Comment by DoireannJane** [comment]
Hm is it rendering partially off of your game board?

**Comment by rsm-dnierman** [comment]
I changed everything to 10 and it is still a rectangle.. I think I am confused on how the x,y, width and height all come into play or maybe there is a bug with my context

```js
let caterpillar = new interactiveElement(10,10,10,10,"green")

```

still a rectangle

<img width="491" alt="Screen Shot 2022-02-22 at 9 08 58 AM" src="https://user-images.githubusercontent.com/40249436/155182614-5fe4e038-faa7-4329-aca6-9b2d130f730b.png">

**Comment by rsm-dnierman** [comment]
I don't think it is. here is more code related to the gameBoard

```js
//globals for items on the screen that will need to be referenced
const glassJar = document.getElementById('canvasGlassJar')
console.log("glassJar element, ",glassJar)

// we need to get the game's context, which will allows to specify where to put things
// and how big to make them
const ctx = glassJar.getContext('2d')
```

**Comment by tkolsrud** [comment]
Have you tried correcting for y value and height? aka if the height is 10px you'd actually want to deduct 10px from the y value to make it render in the correct place

**Comment by timmshinbone** [comment]
@dnierman0920 add the solution to this issue

**Comment by rsm-dnierman** [comment]
The solution:

Using **inline styling** within the **index.html file** and setting the height and width using **pixels**:

```html
  <canvas id="canvasGlassJar" class="jar" height='500px'% width='500px';></canvas>
  ```
