### ISSUE TITLE
Game project issue - on re rendering, item re spawn in the same coordinates

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-1-issues#62]
### What's the problem you're trying to solve?
When re rendering, item spawns in the same place

### Post any code you think might be relevant (one fenced block per file)
```JavaScript
const randX = () => Math.floor((Math.random()* 500))
const randY = () =>  Math.floor((Math.random()* 500))

let player = new PlayerCrawler(20, 20, 'blue', 20, 20)
let star = new Crawler(randX(), randY(), 'yellow', 5, 5)
let bomb = new Crawler(randX(), randY(), 'red', 10, 10)
let medPac = new Crawler(randX(), randY(), 'white', 15, 5)

const gameLoop = () => {
    ctx.clearRect(0, 0, game.width, game.height)
    
    if (star.alive) {
        star.render()
        detectHit(star)
        
    }    
    if (bomb.alive) {
        bomb.render()
        detectHit(bomb)
    } 
    if (medPac.alive) {
        medPac.render()
        detectHit(medPac)
    } 
    player.render()
    
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error

### What is your best guess as to the source of the problem?
Not sure - the function that generates the random # for the coordinates should pull a new number each time

### What things have you already tried to solve the problem?
Creating a function that re generates a random number

### Paste a link to your repository here
https://github.com/shaialoni/SEIR-6-6-Project-1

**Comment by aishcann** [comment]
Hey Shai! A couple clarifying questions - what is the "item" that is supposed to be in a different location each time? Also, have you tried console.logging `randX` and `randY` to ensure they are giving you the type of output you are looking for?

**Comment by shaialoni** [comment]
The item is one of the three items im spawning (star, bomb, medpac) - did not try console.log in the loop, i tried entering the function as is in the console, and it is giving me a random number each time, but I can add it to the loop and see

**Comment by aishcann** [comment]
You can also `console.log(star, bomb, medPac)` and see what info is being generated.

**Comment by shaialoni** [comment]
working on it now, stay tuned...

**Comment by shaialoni** [comment]
so from what I can see (its spamming the console way too fast to be able to do anything with it) is that it's repeating the same coordinates (which we knew, but now it's confirmed).
I guess what im a little fuzzy on, is if I have in the render function item(x,y,color,w,h) and I am populating the x and the y with a function - what would "freeze" the function causing it to generate the same number again and again instead of re running the math random?

**Comment by aishcann** [comment]
What I'm thinking now is the issue happens when you instantiate the objects `star`, `bomb` and `medPac`. Their initial values are given with the random numbers that are being generated. But nothing is happening to make those values change.

If you need those values to change, you could add a method to the objects that would change their X and Y coordinates when the function is called.

**Comment by shaialoni** [comment]
or after "using" the item is there away to completely erase it so when it gets re rendered it's forced to re generate the coordinates?

**Comment by aishcann** [comment]
Before I answer this, what do you mean by re-render? Do you mean refreshing the page, clicking a button to restart the game, or anything else?

Also there will be a delay in me getting back to you - we have a staff meeting at 3pm and then I have another meeting after.

**Comment by shaialoni** [comment]
item gets used - alive status gets set to false and now it's gone.
I have an external timer to reset the alive status back to true.
so now the game loop wil re render(?) the item once it reads the new alive status as true again.....
it makes sense in my head :)

**Comment by shaialoni** [comment]
ok, figured it out.
I am re generating the crawler in the detect function, this way it does not mess with the positioning (which happens if you try to declare in loop)
