### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by LarryMays92** [sei-ec-remote/project-1-issues#63]
### What's the problem you're trying to solve?
My Console Is Not Doing Anything or Responding 

### Post any code you think might be relevant (one fenced block per file)
```
// MAKE THE CARDS USING ARRAYS TO GROUP EM at first i made 52 card what a waste of time 
const SUITS = ["♦","♥","♣","♠"]
const VALUES = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"]

// define the deck and what it will consists of 
class Deck {
    constructor(cards = cleanDeck()) {
        this.cards = cards
    }
}
//define the card and what it will consist of 
class Card {
    constructor(suit, value) {
        this.suit = suit
        this.value = value
    }
}

// function to create the deck each deck has 52 cards
// loop through the two arrays to get a card and those cards will create the Deck so 
const cleanDeck = () => {
    return SUITS.flatMap(suit => {
        return VALUES.map(value => {
            return new Card(suit, value)
        })
    })
}

const newDeal = new Deck()
console.log(newDeal.cards)

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no error messages all green

### What is your best guess as to the source of the problem?
Im Not sure at all partnerd with classmates who also werent able to see why 

### What things have you already tried to solve the problem?
ive tried disconnected my wifi turning off live and going live again 

### Paste a link to your repository here
(https://github.com/LarryMays92/projectOne.git)

**Comment by scarletpuma** [comment]
Can I see an example of what your console looks like when you try to run it?

**Comment by LarryMays92** [comment]
hey i think i have them linked in correctly in my html 
let me check that out 
i for got to link my pages to my js after i restarted the third time i believe

**Comment by LarryMays92** [comment]
oh my god smh thats exactly what it was i see all my cards now thank you !

**Comment by LarryMays92** [comment]
thanks got it figured out and moving forward
