### ISSUE TITLE
Random Word Generator word checker conflict

### ISSUE THREAD

**Issue by tzou2024** [sei-ec-remote/project-1-issues#66]
### What's the problem you're trying to solve?
Sometimes the random word API i am using will generate a word that then doesn't register as a valid word when routing it to a dictionary API. I am trying to recursively generate words and check them before hand with the dictionary API but it isn't working so fat

### Post any code you think might be relevant (one fenced block per file)
my current code for generating a random word
```
function generateWord() {
    return fetch(`https://random-word-api.herokuapp.com/word?length=${lettercount}`).then(function(response) {
        return response.json();
    }).then(function(json) {
        return json;
    });
}

function getRandomWord(){
    generateWord().then(function(result) {
        //console.log(result)
        word = result[0].toUpperCase();
    })
    
    fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`) //1️⃣ 
    .then(function(response) {// 2️⃣ 
        if (!response.ok) {// 3️⃣ 
            throw Error(response.statusText);//4️⃣ 
        }
        return response.json();
    }).then(function(response) {
        console.log("All good!")
    }).catch(function(error) { //5️⃣ 
        console.log('404 retry : '+ error);// 6️⃣ 
        getRandomWord()
    });
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
I'm getting a 404 for my dictionary API fetch when checking the word in the dictionary

### What is your best guess as to the source of the problem?
I guess I'm not checking the word beforehand right, maybe my recursion is messed up?
### What things have you already tried to solve the problem?
I tried the recursion but it's not rly working and that's all I've tried. I don't want to use a different API because these two api's i haven't had to make an account for. Or maybe I don't understand what the real problem is

### Paste a link to your repository here
https://github.com/tzou2024/wordle

**Comment by tzou2024** [comment]
I think that something is weird with asynchronous updating, i added some checks and when i generate a new word a bunch of times and log the return, I noticed that it's one word behind

**Comment by scarletpuma** [comment]
Could you send links to the documentation for the APIs you're using?

**Comment by tzou2024** [comment]
Dictionary API: https://dictionaryapi.dev/

Random Word API: http://random-word-api.herokuapp.com/home

**Comment by tzou2024** [comment]
My idea was to generate a word and immediately check it in the dictionary, if it doesn't work then regenerate another word, so then it's guaranteed to check again if a player guesses it. But, there are word's in the random word API i.e unbid or fetus that don't have endpoints in the dictionary and my regeneration catch isn't catching it

**Comment by scarletpuma** [comment]
My best guess is that it's related to the APIs -- let me check back in with you in a bit

**Comment by tzou2024** [comment]
I guess I don't understand how asynchronous things work...my checker is now making my word generator stuck in an infinite 404 loop

**Comment by tzou2024** [comment]
```
function generateWord() {
    return fetch(`https://random-word-api.herokuapp.com/word?length=${lettercount}`).then(function(response) {
        return response.json();
    }).then(function(json) {
        return json;
    });
}

function getRandomWord(){
    generateWord().then(function(result) {
        //console.log(result)
        word = result[0].toUpperCase();
        console.log("word is: ", word)
    })
    
    fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`) //1️⃣ 
    .then(function(response) {// 2️⃣ 
        if (!response.ok) {// 3️⃣ 
            throw Error(response.statusText);//4️⃣ 
        }
        return response.json();
    }).then(function(response) {f
        console.log(response)
        console.log("All good!")
    }).catch(function(error) { //5️⃣ 
        console.log('404 retry : '+ error);// 6️⃣ 
        //getRandomWord()
    });
}
```

This now generates a word but upon checking gives 404 retry : ReferenceError: f is not defined

**Comment by scarletpuma** [comment]
`        return response.json();
    }).then(function(response) {f`
That's where the issue is for that one ^

**Comment by tzou2024** [comment]
Ah totally missed that!

The infinite loop error was because I need to build in a delay for the promise to fulfill:
```
function generateWord() {
    return fetch(`https://random-word-api.herokuapp.com/word?length=${lettercount}`).then(function(response) {
        return response.json();
    }).then(function(json) {
        return json;
    });
}

function getRandomWord(){
    generateWord().then(function(result) {
        //console.log(result)
        word = result[0].toUpperCase();
        console.log("word is: ", word)
    })
    setTimeout(()=>{
    fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`) //1️⃣ 
    .then(function(response) {// 2️⃣ 
        if (!response.ok) {// 3️⃣ 
            throw Error(response.statusText);//4️⃣ 
        }
        console.log("Fetching")
        return response.json();
    }).then(function(response) {
        console.log(response)
        console.log("All good!")
    }).catch(function(error) { //5️⃣ 
        console.log('404 retry : '+ error);// 6️⃣ 
        getRandomWord()
    })}, 500);
}
```

Now it can resurse properly but I have a problem where the word checker checks one behind the word generator...and the checker keeps building on itself i.e fetches 1 word 4 times then 5 times ect.

**Comment by tzou2024** [comment]
I found this: https://rapidapi.com/wakey7dev-voGD0mGppH/api/wordle-creator-tools/

Which is working quite well but it only allows 200 requests per month for free so I guess I'll go easy on the testing.
