### ISSUE TITLE
Game project issue - reset buttomn

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-1-issues#67]
### What's the problem you're trying to solve?
when I stop the game loop on a win scenario or a lose scenario I want to have a button to reset the game back to the beginning conditions and reset the game loop.

### Post any code you think might be relevant (one fenced block per file)
```JavaScript
// this is how I stop the game
const stopGameLoop = () => {clearInterval(gameInterval)}

//This is the reset button function - my thought process was to reset all the variables that cause a game over scenario, and restart the game loop (gameInterval variable) that was stopped by the gameStopLoop function
resetButton.addEventListener('click', function() {
    score = 0
    scoreBoard.textContent= `score: ${score}`
    player.hitPoints = 100
    healthBar.textContent= `health: ${player.hitPoints}`
    statusWindow.textContent = 'Game On!'
    document.addEventListener('DOMContentLoaded', function () {
        gameInterval
    })
    
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error. Score and health are reset, but movement functionality isn't restored

### What is your best guess as to the source of the problem?
I missed something obvious.....

### What things have you already tried to solve the problem?
the function in the resetbutton listener

### Paste a link to your repository here
https://github.com/shaialoni/SEIR-6-6-Project-1.git

**Comment by aishcann** [comment]
Clarifying questions: What is the "movement functionality"? Can you screenshot the part in your code where this exists?

**Comment by shaialoni** [comment]
```JavaScript
class PlayerCrawler {
    constructor(x,y, color, width, height, hitPoints) {
        this.x = x,
        this.y = y,
        this.color = color,
        this.width = width,
        this.height = height,
        this.hitPoints = 100
        this.alive = true,
        this.speed = 15,
        this.direction = {
            up: false,
            down: false,
            left: false,
            right: false
        }
    }
    
    setDirection = function (key) {
        if (key.toLowerCase() == 'w') {this.direction.up = true}
        if (key.toLowerCase() == 'a') {this.direction.left = true}
        if (key.toLowerCase() == 's') {this.direction.down = true}
        if (key.toLowerCase() == 'd') {this.direction.right = true}
        
        
    }
    
    unSetDirection = function (key) {
        if (key.toLowerCase() == 'w') {this.direction.up = false}
        if (key.toLowerCase() == 'a') {this.direction.left = false}
        if (key.toLowerCase() == 's') {this.direction.down = false}
        if (key.toLowerCase() == 'd') {this.direction.right = false}
        
    }

    movePlayer = function () {
        if (this.direction.up) {
            this.y -= this.speed
            if (this.y <= 0) {
                this.y = 0
            }
        }
        if (this.direction.left) {
            this.x -= this.speed
            if (this.x <= 0) {
                this.x = 0
            }
        }
        if (this.direction.down) {
            this.y += this.speed
            if (this.y + this.height >= game.height) {
                this.y = game.height - this.height
            }
        }
        if (this.direction.right) {
            this.x += this.speed
            if (this.x + this.width >= game.width) {
                this.x = game.width - this.width
            }
        }
    }

    render = function () {
        ctx.fillStyle = this.color
        ctx.fillRect(this.x, this.y, this.width, this.height)
    }
}
```

**Comment by aishcann** [comment]
Thank you! So when you talk about movement functionality being restored, what specific things are you looking to reset? Is it the movement direction?

**Comment by shaialoni** [comment]
no, just his ability to move.
When game over, you can't move the player.
When I reset, all the stats get reset, but player still can't move...

**Comment by aishcann** [comment]
Okay. So what conditions have to be present for the player to be able to move?

**Comment by shaialoni** [comment]
Well...... the game starts with the ability to move - in the game loop the player gets rendered, and right away i call the move player function
(sorry for the slow response, im in Beth's class)

**Comment by aishcann** [comment]
Okay if you are in class focus on that. You can return to the issue once you are finished.

**Comment by aishcann** [comment]
I want you to think about these things once you get out:

1) what are the player defaults (the values) that are set before the game begins? 
2) what values are changed once the game starts / the user plays?

In that thinking you may see what else needs to be reset in your `resetButton` event listener.

**Comment by shaialoni** [comment]
that was my thought process - to reset all the conditions that brought the gamestop function to work. I must have missed something, I will work on something else and try to get back to it with a fresh outlook.....

**Comment by shaialoni** [comment]
ok, still no go :(
I tried also clearing the canvas, although the canvas gets cleared every loop start so I don't think I should call that in the event listener

**Comment by shaialoni** [comment]
Honestly - at this point I think I'm just going to make this button refresh the page....... I spent too much time on this.......
I don't track scores or anything that has to be maintained between games so im not losing anything important by refreshing...

**Comment by shaialoni** [comment]
With the help of some good friends, we were able to figure it out.
Instead of re calling the variable that runs the game loop, we re assigned the same original value to it.
I am not 100% sure honestly why it worked and the other method didn't but i will take the win and move on...

**Comment by aishcann** [comment]
Oh, great!
