### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by tzou2024** [sei-ec-remote/project-1-issues#70]
### What's the problem you're trying to solve?
I have issues deploying my website, my config file with my API key is not being recognized

### Post any code you think might be relevant (one fenced block per file)
```
I have a config file in my git ignore with my API key in my working branch
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
tzou2024.github.io/:18          GET https://tzou2024.github.io/wordle/config.js net::ERR_ABORTED 404
app.js:17 Uncaught ReferenceError: config is not defined

### What is your best guess as to the source of the problem?
I'm guessing something weird about gitignore and online hosting?

### What things have you already tried to solve the problem?
I tried opening a live server in my gh-pages branch that worked fine, so I don't really know why the online version wouldn't work

### Paste a link to your repository here
https://github.com/tzou2024/wordle

**Comment by timmshinbone** [comment]
Let's look together in a breakout room

**Comment by timmshinbone** [comment]
resolved by unhiding config file
