### ISSUE TITLE
Game project issue - difficulty buttons only work to increase difficulty

### ISSUE THREAD

**Issue by shaialoni** [sei-ec-remote/project-1-issues#71]
### What's the problem you're trying to solve?
I have three difficulty buttons - they work by decreasing the time interval of the bombs spawn time. They work as expected when I am decreasing the intervals, but when I try to increase it back they do not react.

### Post any code you think might be relevant (one fenced block per file)
```JavaScript
easyButton.addEventListener('click', () => {
    bombTiming = 5000
    setInterval(() => {bomb.alive = true}, bombTiming)
    console.log('This is bomb timing', bombTiming)
})
harderButton.addEventListener('click', () => {
    bombTiming = 2500
    setInterval(() => {bomb.alive = true}, bombTiming)   
    console.log('This is bomb timing', bombTiming) 
})
nutsButton.addEventListener('click', () => {
    bombTiming = 500
    setInterval(() => {bomb.alive = true}, bombTiming)
    bomb.render()
    console.log('This is bomb timing', bombTiming)
})
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
No error message. When console logging the updated value, it prints the expected number, but the actual item does not change the spawning speed as expected.

### What is your best guess as to the source of the problem?
Not sure, since it works to increase the speed but not decrease

### What things have you already tried to solve the problem?
Re calling the setInterval function after re assigning the new value to the variable

### Paste a link to your repository here
https://github.com/shaialoni/SEIR-6-6-Project-1

**Comment by scarletpuma** [comment]
Sorry, just to clarify, does it not work when you're increasing it or is decreasing it the issue?

**Comment by shaialoni** [comment]
when I use it to speed it up, it works.
When I try to use it to slow it back down, it does not work...

**Comment by shaialoni** [comment]
Worked on this issue last night with Cody and Alo, and we couldn't figure out what was causing this behaviour.... especially since the functions WORK to increase the generation speed (by decreasing the time interval) but doesnt work to decrease the speed (by increasing the time interval)

**Comment by timmshinbone** [comment]
Shai, when we talked yesterday, you were planning to rework those functions to restart the game. Consider when your gameloop stops and starts, and utilize that functionality to make these three individual restart buttons. If the generation speed starts at the rate you've set for each of these functions, then that's all you need.

**Comment by shaialoni** [comment]
I did that...... it didnt reset the interval for the bomb generation
I even added a clear interval in each button. 
Nada...
