### ISSUE TITLE
Loading images via drawImage causes flickering and slows everything down

### ISSUE THREAD

**Issue by nickesparza** [sei-ec-remote/project-1-issues#73]
### What's the problem you're trying to solve?
I am trying to get images drawing on my canvas in order to create artwork for the player and environment. However, the recommended method I've found is both causing flickering on every frame update, and slowing down the response time of all other elements in the canvas too.

### Post any code you think might be relevant (one fenced block per file)
within the player's render function, there is an image being created, setting a source file, and then waiting until the image loads to draw it on the canvas. Forgive the typo in the filename:
```
                this.render = function () {
                    let image = new Image()
                    image.src = '/imgs/textImage.png'
                    image.onload = function () {
                        console.log(`coordinates are: ${this.x}, ${this.y}`)
                        ctx.drawImage(image, player.x, player.y)
                    }
```
I also noticed that setting the drawImage coordinates to this.x and this.y caused the image to be drawn at 0,0 on the canvas instead of on the player, and it wouldn't follow the movement. Hence why I had to use a specific variable name.

I should probably also mention I'm rendering using setInterval rather than requestAnimationFrame.

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Once drawn, the image flickers rapidly. Also, despite being ahead of other graphical elements in the render queue, it is still being drawn last and on top of everything. There is also noticeable delay in drawing other player elements which create the illusion of those elements "chasing" the player object as it moves, rather than being anchored to it. Furthermore, all of this is even messing up the game timer, which doesn't actually reach 0 before the timeout function fires to end the game.

### What is your best guess as to the source of the problem?
I'm pretty sure the issue is with the .onload function - presumably, loading an image from a file takes a bit longer than simply drawing a rectangle with the canvas context, and so everything later in the render queue is being delayed.

### What things have you already tried to solve the problem?
I have tried declaring the new Image outside of the loop to see if that will speed things up, but since the .onload function still needs to be within the render function, it hasn't made a noticeable difference.

### Paste a link to your repository here
https://github.com/nickesparza/ga-1-project-burger

**Comment by nickesparza** [comment]
Oh I should probably also mention I'm rendering using setInterval rather than requestAnimationFrame.

**Comment by timmshinbone** [comment]
Might be trying to load the image too many times and slowing things down. I'd recommend loading the image at the start, and hiding it, then calling it where needed (the render function) and using that function to 'unhide' it. Let me know if that make sense or not

**Comment by nickesparza** [comment]
I think this is where I was headed, just a little unclear about where I should declare the new image elements. I assume the goal is to include a drawImage inside the render function that isn't also trying to load the image at the same time?

**Comment by nickesparza** [comment]
Well, I think I was getting two possible solutions crossed. This is apparently solved by moving the image variable declaration outside of the render function and then forgoing the .onload entirely and just drawing the image directly.
