### ISSUE TITLE
Check-in regarding game progress

### ISSUE THREAD

**Issue by christian-the-brewer** [sei-ec-remote/project-1-issues#74]
### What's the problem you're trying to solve?
Just want to check in and make sure I am on track. Wondering what to focus the rest of my effort on

### Post any code you think might be relevant (one fenced block per file)
```

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
no errors

### What is your best guess as to the source of the problem?
no problems

### Paste a link to your repository here
https://github.com/christian-the-brewer/Goblin_Story

**Comment by timmshinbone** [comment]
alright, let's take a look in a 1:1
