### ISSUE TITLE
Game project issue Terrance Wells

### ISSUE THREAD

**Issue by SunGod7** [sei-ec-remote/project-1-issues#77]
### What's the problem you're trying to solve?
when i press the start button the timer starts but the game doesn't start until i press the answer keys.

### Post any code you think might be relevant (one fenced block per file)
```
function startGame(){

document.getElementById("startBtn").disabled = true;
  //  

    //sets timer
    let timeDisplay = document.getElementById("timeDisplay");
    timeDisplay.hidden = false
    
    timerInterval = setInterval(function() {
    timeLeft -= 1;
    timeDisplay.innerHTML = "Time left: " + timeLeft;
    
    
    
    // stops timer
    if (timeLeft == 0 || score == gameWon) {
        clearInterval(timerInterval);

     } 
  
   
        if (timeLeft == 0) { 
          let YouLose = document.getElementById('gameOver').textContent = 'You lose!!!!'
          console.log(YouLose)
    }
    
  },1000)

```

### What is your best guess as to the source of the problem?
it was working right until i added the win and lose conditions

### What things have you already tried to solve the problem?

i tried reconfigure everything

### Paste a link to your repository here
https://github.com/SunGod7/project1-gameT.Wells.git

**Comment by scarletpuma** [comment]
Do you mind pushing up your code so I can have a better look at what may be going on?

**Comment by SunGod7** [comment]
Do you have it

**Comment by scarletpuma** [comment]
There's still nothing in your app.js in the repo link you sent

**Comment by SunGod7** [comment]
When I push I can’t automatically merge

**Comment by scarletpuma** [comment]
I didn't realize you were working on a separate branch, my bad! Let me look over it really quick

**Comment by scarletpuma** [comment]
[You may want to take a look at this.](https://codepen.io/awkay/pen/ExzGea)

I think simplifying it may make your life a little easier. Try console logging the answer after you make a choice so that you can see if the game is functioning properly once you click the timer button.

**Comment by SunGod7** [comment]
i moved  nextQuestion() inside the startGame function. for some reason it worked. thank you, on to the next issue
