### ISSUE TITLE
Game project issue : Bullets are too fast??

### ISSUE THREAD

**Issue by Rando-cal** [sei-ec-remote/project-1-issues#78]
### What's the problem you're trying to solve?
The tank I have shoots a projectile in a parabolic shape. The X and Y for the bullet are generated before hand given a angle and velocity and position.

The projectile shoots, but is choppy in terms of its visuals. It is not smooth.

### Post any code you think might be relevant (one fenced block per file)
```
Main loop has : setInterval(gameLoop, 65)

Each bullet has its own render in the main loop

Making bullet trajectories based on angle,  velocity... :

const makeBulTrajArray = (x,y,angle, power) => {

    const bulletTrajArrayX = []
    const bulletTrajArrayY = []

    let para = parabolicFunction(x,y,angle,power,0)
    let totalTime = para[3]

    const trajectoryFrames = totalTime / .001 

    for (let i = 0; i < trajectoryFrames; i++){
        bulletTrajArrayX.push(getX(angle,power,i,0,x))
        bulletTrajArrayY.push(getY(angle,power,i,0,y))
    }
    return [bulletTrajArrayX,bulletTrajArrayY]
    
}

This is the FIRING trigger that sets off the fire render:

const fireIt = () => {
    
    let bulletTraj = makeBulTrajArray(tank1.x,canvasYToRealY(tank1.y),tank1.angle, tank1.power)

    let paraBolics = parabolicFunction(tank1.x,canvasYToRealY(tank1.y),tank1.angle,tank1.power, canvasYToRealY(tank1.y))

    let fltTime = paraBolics[3]
    forLength = fltTime / (frameLength * .001)

    // LOOP KINDA WORKS. Have to stop it once its finished its fltTime
    let localIterator = 0

    
    let timerID = undefined
    console.log("timerID:"+timerID)    
    
    const localLoop = () => {

    
        bullet1.show = true 
        bullet1.x = bulletTraj[0][localIterator]
        bullet1.y = realYToCanvasY(bulletTraj[1][localIterator])
        
        localIterator++

    }

      const localClock = () => {
        
        let intervalID = setInterval(localLoop,frameLength)
   
        timerID = intervalID

    }


localClock()
playerChanger()
}


```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
NA

### What is your best guess as to the source of the problem?
Something to do with how many X,Y coordinates are in bullet x,y position array to loop through. Also, the main loop "refresh" time.

### What things have you already tried to solve the problem?
I've tried adjusting the number of frames per bullet path. Also, tried adjusting the main loop frame. It doesn't seem to smooth it out.
I'd like to try and use the similar method for smoothing over of the hero in the Ogre canvas project but I'm not sure how to implement that with a preset X,Y position coordinates for the projectile ballistics...

### Paste a link to your repository here
https://github.com/Rando-cal/ItsOver

**Comment by timmshinbone** [comment]
Share the class used to create the projectiles. Is your motion set up like we did the first day of canvas, or is it set up like the advanced canvas lesson?

**Comment by Rando-cal** [comment]
class ItsOverEntity {

    // attributes that are variable, go in the constructor function
    constructor(x, y, color, width, height, angle, power, show) {

        // define here: what the object will be made of
        this.x = x,    
        this.y = y,  // HAS TO STORE AS CANVAS Y, then convert when needed
        this.color = color,
        this.width = width,
        this.height = height,
        this.angle = angle,
        this. power = power, 
        this.show = show,

        this.health = 100

        // we can also add methods
        // here our method will be render
        this.render = function() {
            // here, we will se the fillstyle and the fillrect

            ctx.fillStyle = this.color
            ctx.fillRect(this.x, this.y, this.width, this.height)
        }
    }
}

**Comment by Rando-cal** [comment]
I'm not using the "always moving" technique because the bullets are not controlled by user input. The bullet motion positions are all generated once the 'fire' button is pressed.
