### ISSUE TITLE
Problem with canvas collision

### ISSUE THREAD

**Issue by jscodeguy** [sei-ec-remote/project-1-issues#8]
### What's the problem you're trying to solve?
I'm trying to get my object to move on its own and respond to barriers

### Post any code you think might be relevant (one fenced block per file)
```js
const borderLeftHit = () => {
    if (sprite.x < borderLeft.x + borderLeft.width
        && sprite.x + borderLeft.width > borderLeft.x
        && sprite.y < borderLeft.y + borderLeft.height
        && sprite.y + borderLeft.height > borderLeft.y
        && spriteDirection === 'left'){
            spriteDirection = 'right'
        }
}
const borderRightHit = () => {
    if (sprite.x < borderRight.x + borderRight.width
        && sprite.x + borderRight.width > borderRight.x
        && sprite.y < borderRight.y + borderRight.height
        && sprite.y + borderRight.height > borderRight.y
        && spriteDirection === 'right'){
            spriteDirection = 'left'
        }
}
const spritePath = () => {
    if (spriteDirection === 'right'){
        sprite.x += 15
    }
    else if (spriteDirection === 'left') {
        sprite.x -= 15
    }
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
My object isn't having any sort of collision with the borders and is just cruisin off the screen

### What is your best guess as to the source of the problem?
my conditionals to switch directions

### What things have you already tried to solve the problem?
creating variables and functions to try and guide the object and collision very intentionally and still having unpredicted response

### Paste a link to your repository here
https://github.com/jscodeguy/Shanes-Game-Project

**Comment by tkolsrud** [comment]
Ah usually that's because the amount you're incrementing the movement is skipping over the limit. So if your x axis limit is 101, but you're moving your character 2 units at a time, it'll jump over the edge and never react to hitting the side of the gameboard

**Comment by jscodeguy** [comment]
changed the movement increment to 1 px and still having the same issue, could be a problem with registering my borders as objects on screen?
