### ISSUE TITLE
Game project issue Terrance Wells

### ISSUE THREAD

**Issue by SunGod7** [sei-ec-remote/project-1-issues#82]
### What's the problem you're trying to solve?

reset button only resets the timer not the score
### Post any code you think might be relevant (one fenced block per file)
```
const reStart = () => {
  document.getElementById("scoreBrd").value= ''
  
  startBtn.disabled = false;
    clearInterval(timerInterval);
    timeLeft = 26;
     //score 
    //scoreBrd = ""
    gameOn = true;
    startGame()
    //return(score = 0)
    //resetScore()
    
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

when i hit the reset button the game restarts but the score keeps adding
### What is your best guess as to the source of the problem?

i need to reconfigure the code 
### What things have you already tried to solve the problem?

moving the call function for startGame , creating a function to reset score

### Paste a link to your repository here
https://github.com/SunGod7/project1-gameT.Wells.git

**Comment by mattkeane-ga** [comment]
How are you tracking the score your code?

**Comment by scarletpuma** [comment]
I think you're on the right track with resetting the score. Can we see how you were trying to reset it?

**Comment by SunGod7** [comment]
scoreBrd.addEventListener("click", enGmFunc);


function enGmFunc() {
       score = 0
}

**Comment by SunGod7** [comment]
im tracking the score with my check score function

**Comment by mattkeane-ga** [comment]
It looks you have a variable for your score called `score`, is this correct? If so, I don't see anything in your `reStart` function that changes that.

**Comment by SunGod7** [comment]
when i put score = 0 nothing change. when i console log it  inside or outside of the function nothig happens

**Comment by mattkeane-ga** [comment]
Try changing this line
```
document.getElementById("scoreBrd").value= ''
```
to
```
document.getElementById("scoreBrd").innerText = ''
```

**Comment by SunGod7** [comment]
that hides the score but when the game restarts the scores still the same

**Comment by mattkeane-ga** [comment]
Did you include `score = 0` in your `reStart` function?

**Comment by SunGod7** [comment]
i put score = 0 in the starGame function and it work but im going to move it down there before something else goes wrong. thankyou

**Comment by SunGod7** [comment]
thank you
