### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by zyaffee** [sei-ec-remote/project-1-issues#95]
### What's the problem you're trying to solve?
I get a "reference error: document not defined" when calling
const foo = document.createElement('bar')

### Post any code you think might be relevant (one fenced block per file)
```
// create the game map
const createMap = () => {
    // ...
    // create the div to house the map
    const gameMap = document.createElement('div')    // LINE 38, REFERENCED IN ERROR MESSAGE
    gameMap.setAttribute('id', 'Game-Map')
    // ...
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?

reference error: document not defined 38:21, function call at 62:1

### What is your best guess as to the source of the problem?
maybe the DOM isn't loaded yet when the function is called

### What things have you already tried to solve the problem?
placing the assignment inside and outside of the function it's part of, making sure <script> in the HTML is proper
googled around to find the above best guess explanation

### Paste a link to your repository here
https://github.com/zyaffee/Baraka

**Comment by kestler01** [comment]
hey Zach, is this still a blocker for you ? 
if so, would you share your html page in a code block

**Comment by zyaffee** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baraka</title>
    <script src="./js/app.js" defer></script>
    <link rel="stylesheet" type="text/css" href="./css/style.css">
</head>
<body>
    
</body>
</html>`

**Comment by zyaffee** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baraka</title>
    <script src="./js/app.js" defer></script>
    <link rel="stylesheet" type="text/css" href="./css/style.css">
</head>
<body>
    
</body>
</html>

**Comment by zyaffee** [comment]
should I post my full .js? it's not that big, just classes and functions

**Comment by kestler01** [comment]
yes please

**Comment by zyaffee** [comment]
```

// class for each map node
class Territory {
    constructor (mapId, population, abundance) {
        this.mapId = mapId,
        this.population = population,
        this.abundance = abundance
    }
    owner = ''
    unitsPresent = []
    adjacents = []
}

class Unit {
    constructor (type, location) {
        this.type = type,
        this.location = location
    }
    owner = ''
    strength = 1
    upkeepCost = 0
}

// random number from min to max inclusive
const randomRange = (min,max) => {
    return Math.floor(Math.random() * (max + 1 - min) + min)
}


// create the game map
const createMap = () => {
    // an array of all Territories
    let mapArray = []

    // used to give identity each territory for lookup
    let mapNum = 0

    // create the div to house the map
    const gameMap = document.createElement('div')
    gameMap.setAttribute('id', 'Game-Map')

    // create each row of territories in map
    for (let i = 0; i < randomRange(4,7); i++) {
        const mapRow = document.createElement('div')
        mapRow.classList.add('map-row')

        // create each territory
        for (let j = 0; j < randomRange(1,5); j++) {
            // Create territory DOM element
            const territoryDiv = document.createElement('div')
            territoryDiv.classList.add('territory')
            territoryDiv.setAttribute('id', mapNum)

            // Create territory object
            const territoryObj = new Territory (mapNum, randomRange(3,5), randomRange(3,5))
            mapArray.push(territoryObj)
            mapNum++
            // TO DO TO DO TO DO !!!!!!!!!!! CREATE STARTING PEASANTS IN THIS NEW TERRITORY EQUAL TO POPULATION
        }
    }
}

createMap()
console.log(gameMap)
// console.log(mapArray)

**Comment by zyaffee** [comment]
I tried placing the const gameMap assignment outside the function again and this time it worked. Really unsure what happened. Also, shouldn't it still be reachable if I declare from within the function anyway?

**Comment by kestler01** [comment]
interesting - come on over to room 10 and lets talk about it 😁

**Comment by kestler01** [comment]
scoping issue
