### ISSUE TITLE
Can't get my dog to move

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-1-issues#96]
### What's the problem you're trying to solve?
I'm trying to get a character to move to a new location

### Post any code you think might be relevant (one fenced block per file)
```
dog.updatePosition = function () {
    const diffX = pooSpot1.x - dog.x;
    const diffY = pooSpot1.y - dog.y;
    if(diffX > 0)
        dog.x += 3;
    else 
        dog.x -= 3;
    if(diffY > 0)
        dog.y += 3;
    else
        dog.y -= 3;
}

dog.updatePosition()```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
My dog character isn't moving

### What is your best guess as to the source of the problem?
I think it's probably because the youtube tutorial I'm following did something to their code I didn't see.

### What things have you already tried to solve the problem?
I've stared at my code and can't figure out whats going on.



### Paste a link to your repository here[
](https://github.com/hewinsonj/PooPicker-Game)

**Comment by scarletpuma** [comment]
It looks like you're trying to use syntax for switch instead of the functions you're used to. Try adding some curly brackets to that function!

**Comment by kestler01** [comment]
is this still active 😁 ?

**Comment by hewinsonj** [comment]
I figured it out! Thanks guys!

**Comment by kestler01** [comment]
awesome - would you mind posting a brief summary of the solution and closing the issue ? 
( ideally with the "close with comment " button )

**Comment by hewinsonj** [comment]
Oops I didn't mean to close it like that.
I had to call the function in the game loop.

**Comment by hewinsonj** [comment]
I had to call the function in the game loop.
