### ISSUE TITLE
Can't get the middle card to center-bottom

### ISSUE THREAD

**Issue by melsil11** [sei-ec-remote/project-1-issues#97]
### What's the problem you're trying to solve?
I have three cards towards the bottom of the screen. I was able to line up the left and right card but I can't seem to center the middle card. 

### Post any code you think might be relevant (one fenced block per file)
```.gameboard{
    position: relative;
    display: flex;
    justify-content: center;
    height: auto;
    min-height: 500px;
    width: auto;
    border: 5px solid;
    padding: 20px; 
    
}

#match-card{
    position: absolute;
    /* display: inline-block; */
    justify-content: center;
    margin-left: auto;
    margin-right: auto;
    /* width: 10%; */
    /* margin: 20px 450px 10px 840px; */
}
    
.cards {
   position: absolute;
   /* display: inline-block;  */
   /* justify-content: center; */
    /* object-position: bottom; */
   bottom: 225px;
}

#faceCard1 {
    position: absolute;
    right: 300px;
}

#faceCard2 {
    position: absolute;
    justify-content: center;
    margin-left: auto;
    margin-right: auto;
    /* object-position: center; */
    /* right: 0; */
    /* left: 10px; */
    
}

#faceCard3 {
    position: absolute;
    left: 300px;
}

```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
when I try to adjust it left it move right and vice versa.

### What is your best guess as to the source of the problem?
I think it might be the way I have assigned them to the parent div.

### What things have you already tried to solve the problem?
I have change the container type, I have tried left and right margins, positions, auto margins, justified content. Looked online and tried suggested settings. 

### Paste a link to your repository here
https://github.com/melsil11/Find-the-Puppy

**Comment by scarletpuma** [comment]
You have to put flex on the smaller divs as well. It doesn't inherit the way a lot of other CSS properties do. So, having it on the parent div only makes that parent div flex. If you want to use flexbox on those child divs, they need to have _display: flex_ as well

**Comment by melsil11** [comment]
I put flex on all the child divs, but it is still acting the same 
.gameboard{
    position: relative;
    display: flex;
    justify-content: center;
    height: auto;
    min-height: 500px;
    width: auto;
    border: 5px solid;
    padding: 20px; 
  
}

#match-card {
    display:flex;
    position: absolute;
    /* display: inline-block; */
    justify-content: center;
    margin-left: auto;
    margin-right: auto;
    /* width: 10%; */
    /* margin: 20px 450px 10px 840px; */
}
    
.cards {
   position: absolute;
   display:flex;
   /* display: inline-block;  */
   /* justify-content: center; */
    /* object-position: bottom; */
   bottom: 225px;
}

#faceCard1 {
    display: flex;
    position: absolute;
    right: 300px;
}

#faceCard2 {
    display: flex;
    position: absolute;
    /* justify-content: center; */
    /* margin-left: auto;
    margin-right: auto; */
       
}

#faceCard3 {
    display: flex;
    position: absolute;
    left: 300px;
}
