### ISSUE TITLE
Can't stop dog from interacting twice with one element 

### ISSUE THREAD

**Issue by hewinsonj** [sei-ec-remote/project-1-issues#98]
### What's the problem you're trying to solve?
The element I'm trying to render when a hit is detected renders for a sec then disappears again.

### Post any code you think might be relevant (one fenced block per file)
```
     if(    dog.x < thing.x + thing.width 
            && dog.x + dog.width > thing.x
            && dog.y < thing.y + thing.height
            && dog.y + dog.height > thing.y ) {
                thing.alive = true
                thing.render()
            }```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
Element appears and disappears very quickly

### What is your best guess as to the source of the problem?
I think the dog is interacting twice with element.


### What things have you already tried to solve the problem?
I've tried only allowing a detect hit when element is alive=false in many ways 


### Paste a link to your repository here[
](https://github.com/hewinsonj/PooPicker-Game)

**Comment by kestler01** [comment]
it does sound like we have a multiple interactions here. Do you have your collision detector make the object stop at the point of contact so that we aren't perpetually having collisions on every game 'tick'

**Comment by hewinsonj** [comment]
No, I have it moving to the next element when it interacts with the previous element. It does the same thing with the next element and keeps moving.  The goal is to not allow it to detect a hit while the element is alive.

**Comment by kestler01** [comment]
why don't you come to room 40 are you can show me what's going on in more detail

**Comment by hewinsonj** [comment]
sorry didn't mean to cut you off

**Comment by kestler01** [comment]
all good - So - now this issue is resolved, post a brief summary of the solution and close it please 😁

**Comment by hewinsonj** [comment]
Had to post an if statement in my game loop to render the pooSpot when ever it's alive value is set to true instead of in my hit detection function. 
Thanks Andrew!
