### ISSUE TITLE
Game project issue

### ISSUE THREAD

**Issue by ange1026** [sei-ec-remote/project-1-issues#99]
### What's the problem you're trying to solve?
I made a 6x7 grid but is not showing correctly on the browser.

### Post any code you think might be relevant (one fenced block per file)
```
.board {
    align-items: center;
    margin: 5px;
    display: grid;
    width: 100%;
    /* background-color: aqua; */
    padding: 10px;
    grid-template-columns: repeat(6, 130px);
    grid-template-rows: repeat(7, 80px); 
    justify-content: center;
    padding: 20px;
}
```

### If you see an error message, post it here. If you don't, what unexpected behavior are you seeing?
It's only showing the horizontal lines

### What is your best guess as to the source of the problem?
Maybe not a correct alignment 

### What things have you already tried to solve the problem?
I tried different sizes of margin, padding, width...

### Paste a link to your repository here
https://github.com/ange1026/Game-Project

**Comment by scarletpuma** [comment]
Honestly, for now, it may be better to stick with flexbox instead of grid. It'll be a bit easier to manage. Also, you used _justify-content_ and that is a flexbox property so that may be why things aren't displaying the way you expected

**Comment by ange1026** [comment]
Okay thanks!
